### ISSUE TITLE
CMake Build and Windows Build

### ISSUE THREAD

**Issue by KubaO** [verilator/verilator#2065]
I'm working on a CMake build that works on Windows as well as Unix, supporting both mingw and MSVC on Windows.  I'm submitting work in small chunks in separate PRs.

The branch I do the work in is https://github.com/KubaO/verilator/tree/cmake-win-build

- [x] Successful verilator and coverage build under mingw and MSVC.
- [x] Unity builds work and are handled by cmake (requires cmake 16+).
- [x] MinGW Windows build under Travis
- [ ] MSVC build under Travis
- [ ] Generate release binaries for Windows, and generate release artifact
- [ ] Run tests on Windows

**Comment by wsnyder** [comment]
Seems unlikely this is going to get enough attention to get completed, feel free to reopen if otherwise.
