### ISSUE TITLE
Unpacked array with -1 range is not traced correctly.

### ISSUE THREAD

**Issue by yTakatsukasa** [verilator/verilator#2090]
During working on https://github.com/verilator/verilator/pull/2066#issuecomment-570889581,
I found a issue on tracing unpacked array.

signal like below:

> logic [7:0]       unpacked_array[-2:0];

has only the following entry in VCD.

>   $var wire  8 # unpacked_array [7:0] $end
>   $var wire  8 % unpacked_array(0) [7:0] $end

Negative index seems to have trouble.

The trouble happens on the latest stable branch.
I added a testcase here https://github.com/yTakatsukasa/verilator/commit/1e1cfbb6c35dbb86a3e73592cab23f41fb03a42d . so bad my perl script :(

**Comment by wsnyder** [comment]
Long ago when Verilator didn't support negative indices, -1 was selected to mean no vector in the trace library.  verilated/*vcd and fst need changes to presumably pass a new bool flag indicating vector is present.

If you'd like to fix this let me know, otherwise I'll get to it shortly.
