### ISSUE TITLE
Clarification on --public-flat-rw

### ISSUE THREAD

**Issue by nanduraj1** [verilator/verilator#2107]
If I understand correctly, `--public-flat--rw` will make writes to any variable/wire propagate appropriately. But see the wave I got 

### Test
```systemverilog
module t();

    logic a;
    logic b;

    assign b=a;

endmodule
```
### Wave
![image](https://user-images.githubusercontent.com/48233402/72277385-d3b30180-3657-11ea-8134-4403e5a47990.png)

### Question

 1. Is this a bug, or am I missing something?
 2. Is it possible make an interface instance public_rw by something like  `Bus b1 () /*verilator public_flat_rw @(posedge i_clk or negedge i_clk) */ ;`

**Comment by wsnyder** [comment]
Making a signal public makes the value changable from outside, but this is not a "force" so the assignment on the next eval will simply replace whatever values tyou drive in.  Basically what can be changed through public is a flop with a conditional enable that is "off":

    always_ff
        if (write_enable_generally_zero)  sig_to_be_public <= data;
