### ISSUE TITLE
Document --xml fields

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#2124]
We should document the --xml output format.

One alternative would be a docs/xml.adoc, but perhaps better to make a real XML schema with documentation tags. We can then validate the XML output against the schema.

@pieter3d #2122

**Comment by pieter3d** [comment]
I'll look into this

**Comment by pieter3d** [comment]
Hmm, so writing a complete schema starts to approach the complexity of the SystemVerilog syntax in BNF form. Is that worthwhile?

**Comment by wsnyder** [comment]
Good point, perhaps we just make an .adoc describing the general concept, plus say fl is deprecated, the loc format, and how datatype ids reference later nodes?

**Comment by wallento** [comment]
Hi, I have a dtd on my disk. Is this useful?

**Comment by wallento** [comment]
Oh, sorry, I have to take it back. Seems I deleted the branch (accidentally perhaps..)

**Comment by wsnyder** [comment]
Closed by #2136
