### ISSUE TITLE
FST: enums in structs with --trace-structs not dumped as expected

### ISSUE THREAD

**Issue by fsiegle** [verilator/verilator#2139]
I recently played around with FST dumps as I would like to see enums as strings. Directions and types are outputted correctly, however, enums are just shown as vectors. A possible reason might be that the enums are inside of structs. I use both the `--trace-structs` and `--trace-fst` switches.

**Comment by wsnyder** [comment]
Problem was indeed enums in structs; note --trace-structs is required to see enums in structs. Fixed in 8f0e8e06965beac7b786801d0880876ce5f60bb1
