### ISSUE TITLE
Compilation breaks with bad code: assigning to 'CData' (aka 'unsigned char') from incompatible type 'CData [3]'

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#2142]
```
./Vtest_bench.cpp:1470:19: error: assigning to 'CData' (aka 'unsigned char') from incompatible type 'CData [3]'
        = vlTOPp->test_bench__DOT____Vcellinp__x____pinNumber3;
          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I couldn't minimize a testcase.

verilator-4.026

**Comment by wsnyder** [comment]
Look for something where pin3 on your testbench is connecting an array or wide to non-array or something like that.  Also try -Oi.  This might be a case where the code is bad but an error is missing, see if it runs in other simulators.

**Comment by yurivict** [comment]
I found the mistake. It was that a wire with a mismatching dimension was connected to the module. I just couldn't reduce the case.

**Comment by wsnyder** [comment]
Really should be reported as a lint error, but reporting similar problems is already on the list.
