### ISSUE TITLE
CFG_CXXFLAGS_STD_NEWEST isn't set to the newest C++ version

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#2147]
Verilator installs the file share/verilator/include/verilated.mk with
```
# Select newest language
CFG_CXXFLAGS_STD_NEWEST = -std=gnu++14
```
but the latest C++ is ```c++2a```.

**Comment by wsnyder** [comment]
gnu++14 is the newest currently supported due to SystemC limitations.

**Comment by wsnyder** [comment]
See #1339 and configure.ac
