### ISSUE TITLE
Access to the # modules

### ISSUE THREAD

**Issue by hounaidarekik** [verilator/verilator#2164]
Hi,
As far as i understand, we can just declare the Top Module and use eval() method but in my case i want to access to modify bus,  initialize them, initialize the clock and reset;
Is it possible to access to the # generated modules or i can just do modification in input and launch the eval() method every time.
There is useful links for my problem.
Thanks a lot for your help

**Comment by wsnyder** [comment]
You modify inputs and call eval()
