### ISSUE TITLE
Why do t_vgen and t_flag_make_cmake fail instead of skip on missing install?

### ISSUE THREAD

**Issue by forensicgarlic** [verilator/verilator#2174]
I just made a clean install with ./configure --enable-longtests and ran the tests, and got failures at the end related to missing an install of cmake and the perl module Bit::Vector. However, I see all the tests requiring vcddiff and systemC were skipped instead of erroring out. Why not skip running these tests instead of erroring?

**Comment by wsnyder** [comment]
Seems a reasonable improvement, perhaps you could submit a pull request to fix these?

**Comment by forensicgarlic** [comment]
ok, will do.
