### ISSUE TITLE
how to enbale VL_DEBUG_IF message

### ISSUE THREAD

**Issue by fuyong10** [verilator/verilator#2175]
Find VL_DEBUG_IF message could be quite useful to understand the eval() flow, but after the following trial, the message could not print in runtime:

verilator ... -CFLAGS "+DVL_DEBUG'
obj_dir/Vtop +verilator+debug

find several run programs under $VERIALTOR_ROOT/bin, maybe I should try with other program instead of verialtor?

**Comment by fuyong10** [comment]
In another small test case, the following works:
verilator ... -CFLAGS "+DVL_DEBUG'
obj_dir/Vtop +verilator+debug

The one that does not show is based on the dpi_compile_master case.

**Comment by wsnyder** [comment]
I didn't think GCC accepted "+D" to make a define, it's "-D".  What to look at is the "gcc" line that is printed when you run "make" - see if it has the CFLAGS you requested attached or not.

**Comment by wsnyder** [comment]
Assuming you figured this out.
