### ISSUE TITLE
 Unable to execute this g++ -L$SYSTEMC_LIBDIR ../sc_main.o Vour__ALL*.o verilated.o -o Vour -lsystemc

### ISSUE THREAD

**Issue by Sangs19** [verilator/verilator#2179]
make -j -f Vour.mk ../sc_main.o verilated.o

is giving a statement of

make: no rule to make target '../sc_main.o'

Also with g++ -L$SYSTEMC_LIBDIR ../sc_main.o Vour__ALL*.o verilated.o
-o Vour -lsystemc getting error ../sc_main.o no such file

**Comment by wsnyder** [comment]
Probably because you don't have a sc_main.cpp or at least not one in that directory?

**Comment by Sangs19** [comment]
> Probably because you don't have a sc_main.cpp or at least not one in that directory?

Is it sc_main.cpp or sc_main.o in above cmd? Also how to generate sc_main.o file?

I am in learning stage and following the verilator manual

**Comment by wsnyder** [comment]
The manual creates it, perhaps you missed that step.

**Comment by Sangs19** [comment]
> make -j -f Vour.mk ../sc_main.o verilated.o
> 
> is giving a statement of
> 
> make: no rule to make target '../sc_main.o'
> 
> Also with g++ -L$SYSTEMC_LIBDIR ../sc_main.o Vour__ALL*.o verilated.o
> -o Vour -lsystemc getting error ../sc_main.o no such file

Thanks for solving the query. Now I am getting error as -lsystemc cannot be found
