### ISSUE TITLE
module port parameter type redeclaration gives "syntax error, unexpected TYPE-IDENTIFIER, expecting IDENTIFIER" error

### ISSUE THREAD

**Issue by hdzhangdoc** [verilator/verilator#2195]
![image](https://user-images.githubusercontent.com/43007864/77221302-8f763d00-6b83-11ea-96c1-18b25c86c6ee.png)
![image](https://user-images.githubusercontent.com/43007864/77221311-a4eb6700-6b83-11ea-919d-7a6bf30d7a2a.png)
![image](https://user-images.githubusercontent.com/43007864/77221318-b03e9280-6b83-11ea-86ed-67bfda459b33.png)

module axi_cut and axi_cut_intf  codes are in the same file，could you help to resolve this error？

**Comment by wsnyder** [comment]
You didn't show it but I'm pretty sure earlier there was a declaration of resp_t in the upper scope.  So this is saying it is unexpecting redeclaring a type identifier as another type.  Redeclaring like this is probably confusing code, but legal.

Fixed in git towards 4.032.
