### ISSUE TITLE
Package Resolutions error out when embedded within a typedef

### ISSUE THREAD

**Issue by drissos** [verilator/verilator#2202]
Package resolution seems to error out whenever it is embedded within a typedef. This small testcase should demonstrate it (https://github.com/drissos/verilator/tree/pkg-resolution-bug). We currently use the work around of importing pkg1::uint8_t directly, but that causes namespace pollution, which is undesirable.

**Comment by wsnyder** [comment]
This is a IEEE 1800 specification bug. Their grammar for enum_base_type does not allow a package.  I checked and at least one other simulator supports this, so might as well do likewise.

Fixed in git towards 4.032.  Thanks for your report & good test case.
