### ISSUE TITLE
Expose VPI cbNextDeadline

### ISSUE THREAD

**Issue by mballance** [verilator/verilator#2204]
https://github.com/verilator/verilator/blob/590b1853d00714a369abfd80e237a8440d04a37c/include/verilated_vpi.cpp#L424

Verilator's VPI implementation includes a cbNextDeadline() method that returns the time of the next VPI callback. Currently this method is neither exposed via a header file, nor used by the implementation. I believe this API would be quite useful to integrations (ie C++ testbenches) that need to support VPI (thinking of cocotb, specifically). Any objections to exposing this in verilated_vpi.h? If not, I'll put in a PR.

Thanks,
Matthew

**Comment by wsnyder** [comment]
Sure, please make a pull request for this & please add or improve a test to appease code coverage.

**Comment by wsnyder** [comment]
Closed with pull #2212.
