### ISSUE TITLE
Duplicate declaration of TYPEDEF error when typedef in a generate for

### ISSUE THREAD

**Issue by hdzhangdoc** [verilator/verilator#2205]
If I moved the typedef statement out of the for loop，the error diappeared，is it a bug？The source code can be compiled pass under VCS.

![image](https://user-images.githubusercontent.com/43007864/77619530-5a972b00-6f73-11ea-8344-33f53a0bdb50.png)

![image](https://user-images.githubusercontent.com/43007864/77619567-6d116480-6f73-11ea-85a2-b454a56ce24b.png)

314   for (genvar t = 0; t < AxiMaxReads; t++) begin: gen_read_upsizer
315     r_state_t r_state_d;
316     r_state_t r_state_q;
317
318     // Are we idle?
319     assign idle_read_upsizer[t] = (r_state_q == R_IDLE);
320
321     struct packed {
322       ar_chan_t ar         ;
323       logic ar_valid       ;
324       logic ar_throw_error ;
325       slv_r_chan_t r       ;
326       logic r_valid        ;
327       burst_len_t burst_len;
328       size_t orig_ar_size  ;
329     } r_req_d, r_req_q;

**Comment by wsnyder** [comment]
Confirmed.

**Comment by wsnyder** [comment]
Thanks for your report.   Fixed in git towards 4.032.
