### ISSUE TITLE
Casex gives unsupported 4-state numbers

### ISSUE THREAD

**Issue by hdzhangdoc** [verilator/verilator#2216]
Hello, When compiling systemverilog, I met an error report:
![image](https://user-images.githubusercontent.com/43007864/78094954-69189300-7408-11ea-9296-68d02f925d95.png)
src code is below:
![image](https://user-images.githubusercontent.com/43007864/78095004-82b9da80-7408-11ea-8067-9da20a7554e0.png)
could we support it？

**Comment by wsnyder** [comment]
This should work, please post a minimum self-runable test case showing this as text (not graphics), thanks.

**Comment by wsnyder** [comment]
Doubt it's this, but found and fixed a case where converting to real numbers would give this error; pull from git to see if that was it.

**Comment by wsnyder** [comment]
If you have a test case please post it, otherwise closing as need test.

**Comment by hdzhangdoc** [comment]
> Doubt it's this, but found and fixed a case where converting to real numbers would give this error; pull from git to see if that was it.

Hello，this probelm appears again under version 0529 master， could you help
to solve it？

**Comment by wsnyder** [comment]
Please post a test case, thanks.

**Comment by wsnyder** [comment]
Please post a test case that is self contained, that is code and a command line that gives the exact error, a code snip isn't enough, thanks.
