### ISSUE TITLE
split_var should be supported in configuration files

### ISSUE THREAD

**Issue by marcowidmer** [verilator/verilator#2219]
#2066 added the split_var metacomment. Is it possible to also add this to the configuration file parser? I would like to write something like

```
`verilator_config
split_var -module "<modulename>" -var "<varname>"
```

**Comment by wsnyder** [comment]
Agreed. Perhaps you could please submit a pull request to document this and also #2220?  Thanks

**Comment by marcowidmer** [comment]
To clarify: This is not a documentation issue, but a feature request. The feature is currently not implemented.

**Comment by wsnyder** [comment]
Thanks for you work on this, looking forward to future contributions from you.
