### ISSUE TITLE
Configuration file documentation: -signal should be -var

### ISSUE THREAD

**Issue by marcowidmer** [verilator/verilator#2220]
#2102 added new supported attributes to the configuration file. Some of them were documented incorrectly: clock_enable, clocker, no_clocker, isolate_assignments, sc_bv and sformat do not expect `-signal "<signame>"`, but rather `-var "<varname>"`.

**Comment by wsnyder** [comment]
Agreed. Perhaps you could please submit a pull request to document this and also #2219?  Thanks
