### ISSUE TITLE
Can you get a signals width from the c++ harness

### ISSUE THREAD

**Issue by Thonner** [verilator/verilator#2283]
Hi!

I am using Verilator to build an emulator for a processor. I am emulating an external memory with a simple c array. I need to allocate memory for this array. I would like to width of the address signal for memory allocation, as the processor can be configured for different size external memories. I was wondering if there is a get this from the verilator generated code? something like

```cpp
int addr_width = c->io_SRamCtrl_ramOut_addr.width();
```
I thought that there is a good chance since i can see the size from the generated .h file:
VL_OUT(io_SRamCtrl_ramOut_addr,**19**,0);
I appreciate the help - Thank you!

**Comment by wsnyder** [comment]
In theory you can get it through VPI access.

However it's probably easier if you don't mind changing the design to just have either

     output addr_width; initial addr_width = $bits(io_SRamCtrl_ramOut_addr);

or if there's a parameter with the width, mark the parameter verilator_public (either in sources or a .vlt file), then the output C file will make an enum constant for the parameter value.
