### ISSUE TITLE
Reading signed nets in C++ gives unsigned result.

### ISSUE THREAD

**Issue by jshaker000** [verilator/verilator#2290]
Signed top level ports do not read back as signed in c++, rather they still come back as signed.

This isnt behavior Id expect, so I would hope for a fix or a warning. (Otherwise I need to know each of the net itwidths to correctly interpret).

Additionally, it seems like inputs are unsigned based off of 32 bits, but outputs are unsigned based on their parameter width.

Attached is a minimum example.
[signed_test.zip](https://github.com/verilator/verilator/files/4543495/signed_test.zip)

To expand: it is not difficult to make a routine to retinterpet an unsigned number of a known width to a signed number of the same width (or vice versa), but since verilator has this knowledge it would be nice if I could tke advantage of it (even if it isnt by default). 

Ie tb->i_a.to_signed()

or something, rather than returning the raw bits with no further informaton on their interpretation.

**Comment by wsnyder** [comment]
Thanks for your report, I can see how this might be unexpected.

For speed, Verilator assumes you have only unsigned types as there is no fast representation of arbitrary width signed types, and needs to continue to do so.  I've committed making this clearer in the documentation:

```
Signals are the smallest of 8-bit unsigned chars (equivalent to uint8_t),
16-bit unsigned shorts (uint16_t), 32-bit unsigned longs (uint32_t), or
64-bit unsigned long longs (uint64_t) that fits the width of the signal.
Generally, you can use just uint32_t's for 1 to 32 bits, or vluint64_t for
1 to 64 bits, and the compiler will properly up-convert smaller entities.
Note even signed ports are declared as unsigned; you must sign extend
yourself to the appropriate signal width.

Signals wider than 64 bits are stored as an array of 32-bit uint32_t's.
Thus to read bits 31:0, access signal[0], and for bits 63:32, access
signal[1]. ...
```
