### ISSUE TITLE
make test fails if perl is not at /usr/bin/perl

### ISSUE THREAD

**Issue by timsnyder** [verilator/verilator#2305]
I'm trying to create a conda-forge recipe for verilator so that it can be installed using the conda package manager.

conda-forge tries to satisfy all dependencies in `$PREFIX`.  As such `/usr/bin/perl` doesn't exist on it's build host.

I will submit a PR that does the search and replace of `/usr/bin/perl` to `/usr/bin/env perl` (while also correctly handling `-w` in the shebang).

**Comment by wsnyder** [comment]
Sorry, should have checked this earlier, but you missed a bunch, please grep again making sure to be using master.

**Comment by timsnyder** [comment]
Ooh.  I should have checked that earlier too.  Will rerun my greps and oneliners again on master and open a new PR.
