### ISSUE TITLE
Support DPI open array arguments with more than 3 unpacked dimensions

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#2313]
The standard allows for more than 3 unpacked dimensions to be used for DPI open array arguments. The current implementation in Verilator is only compatible with up to 3 unpacked dimensions. This issue is just to track the missing feature, I personally don't have an immediate need for this.

**Comment by wsnyder** [comment]
Think I'm going to close this - other simulators seem to have similar limits; when someone needs it here can open an issue (if ever happens).
