### ISSUE TITLE
Low-Hanging Fruit

### ISSUE THREAD

**Issue by stephenry** [verilator/verilator#2323]
I would like to become acquainted with Verilator's internals and make a start on some further contributions. I have been working through the "Good First Issue" tags and would like more. It would be great if someone would identify some further, relatively straight-forward tasks that would be suitable for someone with only introductory knowledge of the codebase.

**Comment by wsnyder** [comment]
Awesome, love the help, awesome!

#2324, #2325, #2326, #2327 added, more to come.
