### ISSUE TITLE
Support display/scan %u/%x

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#2324]
We should implement display/scan %u and %x.

These [sv-tests](https://github.com/SymbiFlow/sv-tests) fail as %u/%x are not supported.

* generated/ivtest/scanu__fscanf_u.v
* generated/ivtest/scanu__sscanf_u.v
* generated/ivtest/scanz__fscanf_z.v
* generated/ivtest/scanz__sscanf_z.v

Todo:

1. Add test_regress tests for %u/%x and make sure expected values match what another simulator e.g. Icarus outputs.

2. Update src and include files to support these.  As Verilator runtime doesn't support tristates, the tristate part of %x would just be zero/ignored.

**Comment by wsnyder** [comment]
Attn @stephenry this is one close to your current & appreciated efforts.

**Comment by stephenry** [comment]
I'll take a look at it. Thanks.

**Comment by wsnyder** [comment]
Thanks for your work on this.
