### ISSUE TITLE
Support $writememb

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#2329]
Currently only $writememh (hex) is supported, we should also support $writememb (binary) for compliance.

Need to clone the current hex format test(s), update src/ methods, and verilated.cpp implementation.

**Comment by FanShupei** [comment]
I'd like to work on this. Since I'm new to verilator codebase, it may take me some time to finish it.

**Comment by wsnyder** [comment]
@FanShupei thanks for looking into this - no rush.  Please feel free to ask questions, it should be fairly straight forward since readmemb already works so you can follow a similar pattern.  Please also make sure to update the tests also to check these files, e.g. by adding test cases similar to writememh.

**Comment by wsnyder** [comment]
Thanks for your contributions on this - hope you'll consider more.
