### ISSUE TITLE
compile uvm-systemc

### ISSUE THREAD

**Issue by ruiqicao** [verilator/verilator#2341]
Still, I have some questions about compiling uvm-systemc. When I pass the command"make -j -C obj_dir/ -f Vtop.mk Vtop", Verilator reported error, such as " *** Unsupported: GNU Make cannot build in directories containing spaces". I checked the verilator include file, but I don't know the reason about this error.
Could anybody give some hints?

**Comment by wsnyder** [comment]
Your current directory (e.g. what 'pwd' prints) or the directory you told Verilator to use presumably contains spaces, don't do that.

**Comment by ruiqicao** [comment]
Got it. And I would like to know if there is an uvm library. Because when I include <uvm>, it shows that no such file or directory.

**Comment by ruiqicao** [comment]
like doing this: #include <uvm>

**Comment by wsnyder** [comment]
Verilator does not come/is not related to SystemC UVM, sorry but I do not use it, and don't know how to install it, but suspect you can search online for assistance.

**Comment by ruiqicao** [comment]
I understand. Thank you.
