### ISSUE TITLE
how to compile for multithreading

### ISSUE THREAD

**Issue by ayewinoung** [verilator/verilator#2383]
How may we help - what is your question?
Hi 
 I've been using Verilator for over 2 years, and its been one of the best tool to co-simulate, RTL, SystemC, SW( HAL, Driver, Application), and want to express my deepest thank you for the team and community.  Best of all its 'very fast' and 'free'.
The question I have is, I want to use multithreading with Verilator to take it to next level using -std=c++11.
Its *not* to speed up SystemC/RTL simulation, but to invoke Reference Models in C/C++ run along side SystemC/RTL in different OS thread(s), so overall system level validation is reduced. 
System level validation architecture is such that, inside a SystemC SC_THREAD, invoke a clean function to execute Reference model.
As experiment, when I compile my working code with "CPPFLAGS += -std=c++11", it will no longer link with following errors:

"Undefined symbols for architecture x86_64:
  "sc_core::sc_api_version_2_3_2_cxx201103L<&(sc_core::SC_DISABLE_VIRTUAL_BIND_UNDEFINED_)>::sc_api_version_2_3_2_cxx201103L(sc_core::sc_writer_policy)", referenced from:"

1. Do I need to recompile Verilator with -std=c++1, or SystemC or both ?
2. Any thoughts/pointers?

Thanks in advance.

**Comment by wsnyder** [comment]
Glad Verilator is useful to you.

This error seems related to the SystemC internals so don't think it has any connection to Verilator.  I haven't seen this error, but trying to recompile with the same compiler seems a good idea.

BTW note Verilator does support having separate models running on separate threads; be sure to use "--threads 1" to say you want thread safty, but no inter-model threading.

Closing as this seemed a question, but if there's more feel free to discuss.
