### ISSUE TITLE
functions in generate C++ files

### ISSUE THREAD

**Issue by fuyong10** [verilator/verilator#2392]
some of the functions are named as _settle_* such as settle__TOP__2, some are combo_*, such as _combo__TOP__4, although seems like they are all for combine logic. So any rules in the naming?

**Comment by wsnyder** [comment]
Generally "combo" for combinatoric logic, "settle" for combo logic in initial blocks, "initial" for initial blocks, "sequent" for flops on one clock, "multiclk" for flops on multiple clocks (see V3Order.cpp).  However these names are really internal-only and might vary from these rules based on later optimizations, you certainly shouldn't use them for any tooling.
