### ISSUE TITLE
Is it okay if dumped vcd file size is about 20GB for simple addition operation?

### ISSUE THREAD

**Issue by NazerkeT** [verilator/verilator#2416]
Hi, there.
I am using Ariane core for self-education, and, for now, successfully "verilated" it using `make verilate` and `make verilate DEBUG=1` using Verilator 4.014 version in Ubuntu 18.04 machine. Simulation results on terminal seem okay, print results are as expected for simple c=a+b addition. Nevertheless, `dump.vcd` and `trace_hart_00.dasm` are too big, 20GB and 53.6MB each respectively. Is it okay? Basically, I have searched around and found that VCD files are generally larger than other waveform log files. Nevertheless, 20GB for a single addition seems too large for me. GTKWave has stalled too before opening. Should I compress VCD format or are there any other advice on this matter? Or, in this case, does too large VCD file point to some bug from my side?  

I would be very happy about any comments on this matter.

**Comment by wsnyder** [comment]
You can see if FST is smaller, should be.

However it is not unusual for traces to be very large and too large to trace an entire design for an entire simulation run.  Generally you'll need to decide on a time frame of interest and only trace around that time.
