### ISSUE TITLE
Consider adding a glossary to the manual

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#2439]
Related to #2437 but this is more of a "new feature". It would be worth considering inclusing a glossary in the manual to define standard terms like "verilator" "Verilator" "verilate (verb)" "verilated" "Verilated" "model" "run-time library" "compile" "simualtor (in the context of verialtor <-> contrast with model)", "<whatever we call the user written C wrapper>" and similar, and then use them consistently throguhout the project. I myself have most of them figured out by now but it would have been helpful a few months back, maybe it would help others.

**Comment by wsnyder** [comment]
I have a perhaps unreasonable objection to glossaries, as believe they aren't commonly read or referenced.  Instead I prefer to define terms when first referenced.  I've committed fixes defining the terms in that manor.

Of course comments on these changes, or general feeling that a traditional glossary is preferable are welcome.
