### ISSUE TITLE
perl-doc missing in apt package list

### ISSUE THREAD

**Issue by sea212** [verilator/verilator#2444]
Hello. Since is this my first contribution, I'll share my name here. I'm called Harald Heckmann. I added my name to the contribution list as suggested.

OS: Ubuntu 20.04 LTS (Focal Fossa)
Verilator version: master on Jun 25, 16:56 GMT+1, commit 0cdc2e038cad19beee6ece3878c62a3e30fdbdc1
Bug: since **perl-doc** is not included in the provided apt package list, the verilator help **verilator --help** can't be presented properly.

Fix: #2445

Cheers
Harald

**Comment by wsnyder** [comment]
Seems perfectly reasonable, thanks for your first contribution - hope to see more!
