### ISSUE TITLE
got floating point exception when $signed(0x80000000) / $signed(0xffffffff)

### ISSUE THREAD

**Issue by kuopinghsu** [verilator/verilator#2460]
I got floating point exception (core dump) on the following test code.

```
module test;
    reg [31: 0] a;
    reg [31: 0] b;
    reg [31: 0] r;

always @*
begin
    r = $signed(a) / $signed(b);
    $display("%08x", r);
end

initial
begin
    a = 32'h80000000;
    b = 32'hffffffff;
end

endmodule
```

**Comment by wsnyder** [comment]
Thanks for the good test case.

Made sense that -MAXINT/-1 gives an exception as can't be represented.

Fixed in git (to give zero) towards version 4.038.

**Comment by kuopinghsu** [comment]
Thanks for the quick response. The operation VL_MODDIVS_III & VL_MODDIVS_QQQ have the same issues.

**Comment by wsnyder** [comment]
Good point, modulus fixed too.
