### ISSUE TITLE
FILE NOT FOUND 

### ISSUE THREAD

**Issue by thejas5432** [verilator/verilator#2463]
Thanks for taking the time to report this.

Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)

V3Lexer_pregen.yy.cpp:369:10: fatal error: FlexLexer.h: No such file or directory

What 'verilator --version' are you using?  Did you try it with the git master version?
verilator-4.038

I facing issues in the file. Could please let me know how to install it.

**Comment by gezalore** [comment]
Please install the prerequisites:
https://www.veripool.org/projects/verilator/wiki/Installing
It seems like you are missing libfl-dev
