### ISSUE TITLE
Regression in member selection of interface arrays

### ISSUE THREAD

**Issue by fordred-imc** [verilator/verilator#2468]
Commit [d42f9c095b4b13267f156062600dc99a377bab50 ](https://github.com/verilator/verilator/commit/d42f9c095b4b13267f156062600dc99a377bab50) caused a regression accessing members of an interface that uses the array method `my_if [N]`

This issue is reported:
` Member selection of non-struct/union object 'ARRAYSEL' which is a 'IFACEREFDTYPE'`

Array method `my_if[0:N-1]` still works as expected.
[](url)

**Comment by wsnyder** [comment]
Thanks for the good test, fixed in git towards 4.039.

**Comment by fordred-imc** [comment]
Thank you for fixing it so quickly
