### ISSUE TITLE
Module parameters of different bit-width get conflated

### ISSUE THREAD

**Issue by abirkmanis** [verilator/verilator#2484]
Given that SystemVerilog seems to respect bit-width of parameters (e.g., it's possible to use $bits on them), I would expect instances of the same module differing only by bit-width of a parameter value to be distinct.
Verilator seems to conflate them (likely by caching on bit-agnostic parameter values).

How to reproduce:
```
module bus(input clk);
  socket #(3'b000) s0();
  socket #(3'b010) s1();
  socket #(2'b10) s2();
  socket #(2'b11) s3();

  always_ff @ (posedge clk) begin
    $finish;
  end
endmodule

module socket #(addr)();
  initial
    $display("bits %d, addr %b", $bits(addr), addr);
endmodule
```

Output:
```
bits           3, addr 000
bits           3, addr 010
bits           3, addr 010
bits           2, addr 11
```
The middle two instances get conflated, apparently because they only differ by a bit-width of their only parameter.

Using Verilator 4.020 devel rev v4.020-13-g58a42834.

If this is by specification, would be nice to generate a warning when merging instances, and an error when using $bits on a parameter.

**Comment by wsnyder** [comment]
Thanks for the good test case and correct diagnosis. Fixed in git towards eventual 4.040 release.
