### ISSUE TITLE
Support spaces between the special symbol ` and the variable name when using macro variables

### ISSUE THREAD

**Issue by phantom-killua** [verilator/verilator#2496]
Hi,

I would like to add support for spaces between the special symbol ` and the variable name when using macro variables, because it increases verilator tool compatibility and the other simulator allows this. What do you all think?

Best Regards
killua

**Comment by wsnyder** [comment]
IEEE does not allow a space between ` and the macro name.  I don't believe supporting IEEE-illegal syntax like this is in the greater interest.  Thanks for asking though, it's interesting to know some vendor decided to do something so unusual in case it comes up.
