### ISSUE TITLE
The graph seems like a little bit strange for me

### ISSUE THREAD

**Issue by simdream** [verilator/verilator#2520]
Just trying to understand how the graph looks like in V3Order, I have the simple test case:

module DUT (clk, in1, out);
input clk, in1;
output out;
reg out;
   always @(posedge clk) out <= in1;
endmodule

On the bottom left of the attached picture, TOP->in1 has PRE and POST are output of the yellow "ALWAYS". This is one that is not easily understood. Shouldn't TOP->in1 as input to the "ALWAYS"? 

And what "PORD" stands for?

Thanks a lot,
 

![dotfile](https://user-images.githubusercontent.com/34676461/91302104-cd8f1280-e75a-11ea-892d-4f6c0b73d737.jpg)

**Comment by wsnyder** [comment]
It's the PREORDER edge - please see the comments in V3Order.cpp
