### ISSUE TITLE
OSX C++11 compile issue with hier builds

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#2523]
After converting to C++11, OSX seems to fail on the hier tests:

https://travis-ci.com/github/verilator/verilator/jobs/378752101

"Undefined symbols for architecture x86_64:

I suspect there's some inconsistent compiler flags or some such.

@yTakatsukasa mind taking a look please?

**Comment by yTakatsukasa** [comment]
Of course!
gezalore advised me how to debug on travis in https://github.com/verilator/verilator/issues/2517#issuecomment-682024747
