### ISSUE TITLE
/*verilator public*/ on parameter and -G on command line

### ISSUE THREAD

**Issue by agoessling** [verilator/verilator#2561]
When the -G{parameter}={value} is passed to verilator on the command line the public parameter (specified by /*verilator public*/) no longer generates the associated header file where the value can be found.  Is this intended behavior?  Is there a way to prevent the generated files from changing based on the presence of the -G flag?

I ask because my test bench uses the public parameter in order to correctly test the module.  I realize I could pass the parameter into the test bench itself with a #define, but I would like the test bench to behave the same whether or not the parameter is the default or being overridden.  Therefore, always utilizing the verilator public parameter is the preferred solution.

**Comment by wsnyder** [comment]
Indeed, thanks for the report, fixed.
