### ISSUE TITLE
Calling a function on an object inside a package will some times result in an internal error

### ISSUE THREAD

**Issue by PeterMonsson** [verilator/verilator#2565]
In the t_convert2string.* files in pull request #2564, I get an internal error when lpcm_pkg is not imported:

%Error: Internal Error: t/t_convert2string.v:68:9: ../V3Width.cpp:4729: Node has no type
                                                 : ... In instance t.test
   68 |       s = tr.convert2string();
      |         ^
                        ... See the manual and https://verilator.org for more assistance.
%Warning: vlt/t_convert2string: Exec of perl failed: %Error: Internal Error: t/t_convert2string.v:68:9: ../V3Width.cpp:4729: Node has no type

vlt/t_convert2string: %Error: Exec of perl failed: %Error: Internal Error: t/t_convert2string.v:68:9: ../V3Width.cpp:4729: Node has no type
vlt/t_convert2string: FAILED: Exec of perl failed: %Error: Internal Error: t/t_convert2string.v:68:9: ../V3Width.cpp:4729: Node has no type
==SUMMARY: Passed 0  Failed 1  Unsup 0  Time 0:00
==SUMMARY: Passed 0  Failed 1  Unsup 0  Time 0:00

If lpcm_pkg is imported (as indicated in the comments) the test passes fine.

**Comment by wsnyder** [comment]
It wasn't resolving the called method's data types before the method call.  The import just changed the internal ordering to avoid this.
