### ISSUE TITLE
Class member struct compilation error

### ISSUE THREAD

**Issue by nndurj** [verilator/verilator#2567]
in the code snippet, WDT >= 5 fails to compile. PFA log.
```systemverilog
module t (
    input v_clk
);

    localparam WDT=5; // WDT >= 5 fails. WDT <= 4 passes

    typedef struct packed {
        logic [WDT-1:0] data;
    } [15:0] w_t;

    class WrReqQ;
        w_t w;
    endclass

endmodule
```
[log.txt](https://github.com/verilator/verilator/files/5276784/log.txt)

**Comment by wsnyder** [comment]
Fixed, thanks for the report.  The class support is new-ish so might be more stuff similarly.
