### ISSUE TITLE
UINFO

### ISSUE THREAD

**Issue by simdream** [verilator/verilator#2575]
How to turn on the UNIFO printed messages? I have " --debug --dump_treei 9", but guess the options are not right. 

ex: UINFO(1, "Option --verilate: Start Verilation\n");

**Comment by wsnyder** [comment]
Added this to docs/internals.adoc:

=== Debug Levels

The "UINFO" calls in the source indicate a debug level. Messages level 3 and below are globally enabled with `--debug`. Higher levels may be controlled with `--debugi <level>`.  An individual source file levels may be controlled with `-debugi-<srcfile> <level>`.  For example `--debug --debugi 5 --debugi-V3Width 9` will use the debug binary at default debug level 5, with the V3Width.cpp file at level 9.
