### ISSUE TITLE
Simulation failed on macOS

### ISSUE THREAD

**Issue by chenguokai** [verilator/verilator#2580]
Thanks for taking the time to report this.

> Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)

When using `sbt` and choosing `verilator` as a backend, the compile fails for lack of `Verilated::flushCall()`

```
/usr/bin/clang++  -I.  -MMD -I/opt/local/share/verilator/include -I/opt/local/share/verilator/include/vltstd -DVM_COVERAGE=0 -DVM_SC=0 -DVM_TRACE=1 -faligned-new -fbracket-depth=4096 -fcf-protection=none -Qunused-arguments -Wno-parentheses-equality -Wno-sign-compare -Wno-uninitialized -Wno-unused-parameter -Wno-unused-variable -Wno-shadow     -Wno-undefined-bool-conversion -O1 -DTOP_TYPE=VSoC -DVL_USER_FINISH -include VSoC.h  -std=gnu++14 -Os -c -o VSoC__ALL.o VSoC__ALL.cpp
/.../chisel-template/test_run_dir/Xim.SoC_Main8780741/SoC-harness.cpp:99:14: error: no member named 'flushCall' in 'Verilated'
  Verilated::flushCall();
  ~~~~~~~~~~~^
1 error generated.
make: *** [SoC-harness.o] Error 1
make: *** Waiting for unfinished jobs....
```

> What 'verilator --version' are you using?  Did you try it with the git master version?

Verilator 4.100 2020-09-07 rev v4.040-74-g16fba5948

Have not tried master yet

> Would you be willing to try to fix Verilator yourself with assistance?

Of course :-)

Edit:

A quick and dirty fix is appending the missing `flushCall` method from old versions to `include/verilated.h`

```
static void flushCall()  VL_MT_SAFE {
        VerilatedLockGuard lock(m_mutex);
        // if (s_flushCb) (*s_flushCb)();
        fflush(stderr);
        fflush(stdout);
}
```

**Comment by wsnyder** [comment]
Chisel is calling an internal function which got removed in a later version.  We probably should have kept that function for compatibility. If you can update to git head, this is fixed.
