### ISSUE TITLE
Compilation time

### ISSUE THREAD

**Issue by agrobman** [verilator/verilator#2600]
Hi @wsnyder,

Appears that our (EH2) configuration define (-set fpga_optimize=1) increases compilation time (GCC part) pretty significantly
from 5min to ~30min. This is counterintuitive . This define removes clock gating logic in our register slices to speed up FPGA
synthesis. This is really strange! Could you, please, investigate?

**Comment by wsnyder** [comment]
This doesn't take long for me.  Please modify verilator_ext_test's t/t_cores_eh2_cmark.pl to show the issue as as perhaps I'm setting the flag incorrectly.

**Comment by agrobman** [comment]
OK, we found that the reason for that slow compile was GCC -O2 bug. Replacing it to -Os brought compilation time to normal ~4-5min.
this is GCC bug reference:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97623

the EH2 Makefile need to be patched as:
VERILATOR_MAKE_FLAGS = OPT_FAST="-Os"

**Comment by wsnyder** [comment]
As above, thanks for holding in there while this was tracked down.
