### ISSUE TITLE
3order.cpp comments

### ISSUE THREAD

**Issue by simdream** [verilator/verilator#2606]
In V3Order.cpp header part:

```
//      For comb logic
//          For comb logic
//              Add vertex for this logic
//              Add edge logic_consumed_var->logic_vertex
//              Add edge logic_vertex->logic_generated_var
```

I think there is another edge also generated:

`               " logic_generated_var_POST -> logic_vertext " 
`

Just confirm and maybe change the comments in header.

**Comment by simdream** [comment]
Similarly for Assign Post.

**Comment by wsnyder** [comment]
Confirmed, if you end up with other edits please feel free to make a pull request even if only for comments like these.
