### ISSUE TITLE
prof-cfunc

### ISSUE THREAD

**Issue by simdream** [verilator/verilator#2610]
What are the correct way to make profile in single thread?

This is what I did :
1. add --prof-cfunc in verilator comand
2. obj_dir/V<TOP>.mk: add "-pg" as CXXFLAGS
3. run obj_dir/V<DUT> 

We are expecting a file called gmon.dat being generated but it is not there. Maybe something missing?

**Comment by wsnyder** [comment]
You also need "-pg" in LDFLAGS.

**Comment by wsnyder** [comment]
Closing as pretty sure that's the problem, but feel free to ask more here if not!

**Comment by simdream** [comment]
thanks. So any chance to add -pg into CXXFLAGS and LDFLAGS in generated .mk file? Might be some reason to leave it for users manually change the Makefile?

**Comment by wsnyder** [comment]
Use

     verilator ...  -CFLAGS '-pg' -LDFLAGS '-pg'
