### ISSUE TITLE
In which case consumed_var_PREVAR could be used?

### ISSUE THREAD

**Issue by simdream** [verilator/verilator#2617]
In V3Order.cpp:
//          For Logic
//              Add vertex for this logic
//                  Add edge logic_sensitive_vertex->logic_vertex
//                  Add edge logic_generated_var_PREORDER->logic_vertex
//                      This ensures the AssignPre gets scheduled before this logic
//                  Add edge logic_vertex->consumed_var_PREVAR
//                  Add edge logic_vertex->consumed_var_POSTVAR
//                  Add edge logic_vertex->logic_generated_var (same as if comb)

In which case consumed_var_PREVAR will be used? In several cases such as ：
   always @(posedge clk)
       FF = combo_output;
Consumed_var_POSTVAR of combo has edge to the generation logic of combo_output. Did not see any cases comsumed_var_PREVAR has any connection other than the edge to the ALWAYS.

**Comment by wsnyder** [comment]
I'm a bit rusty on this but believe the PREVAR is a weak cutable edge so eventual optimizations may be able to remove some of the __Vdly temporaries.  If you make a bunch of staging flops it should be more obvious what's going on with this.
