### ISSUE TITLE
Question: Does Verilator support assertion delay aperator?

### ISSUE THREAD

**Issue by GennadiyKn** [verilator/verilator#2636]
Hey,
I am relatively new to Verilator. I tried to write an assert like this:
`assert property (@(posedge clk_i) signal_a -> ##2 signal_b ) else begin
 $display("x");
end`
But this leads to a syntax error.
`syntax error, unexpected ##, expecting TYPE-IDENTIFIER`
Does Verilator support the delay operator ## ?

**Comment by wsnyder** [comment]
Not currently, sorry, but you could use $past which works.
Contributions to improve assertions are appreciated.
