### ISSUE TITLE
DDR4 memory model can be used in Verilator

### ISSUE THREAD

**Issue by simdream** [verilator/verilator#2646]
https://www.micron.com/search-results?searchRequest=%7B%22term%22%3A%22DDR4%20Verilog%20model%22%7D

Seems like the memory model that can be freely downloaded are all big-3 simulator encrypted. 

Any DDR4 memory model could be used within Verilator?

**Comment by wsnyder** [comment]
Sorry, looks like no joy finding this, if anyone later sees this and knows, please comment.
