### ISSUE TITLE
Missing flags on g++ compiler on macOS

### ISSUE THREAD

**Issue by aignacio** [verilator/verilator#2692]
Hi, since I updated from 4.040 to Verilator 4.106 I had issues with some flags missing in my compiler (see below), so I disabled -Werror...can you explain what's the  recommended version for g++?

warning: unknown warning option '-Wno-bool-operation'; did you mean '-Wno-bool-conversion'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-tautological-bitwise-compare' [-Wunknown-warning-option]

My current Mac version:
➜ clang++ -v
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by wsnyder** [comment]
Verilator when you run "./configure" detects which flags work including these.  Perhaps you ran configure on a different version/compiler (e.g. gcc) then swapped to clang after Verilation?
