### ISSUE TITLE
CI: adapt matrices to different event sources

### ISSUE THREAD

**Issue by umarcor** [verilator/verilator#2725]
Ref #2687

> https://github.com/verilator/verilator/pull/2687#issuecomment-743193003
> - Most important IMO is fast turn around for submitters. So 20.04 clang+gcc on pull, push, cron nightly on master, manual.
> - Run all OS/distros on cron nightly master, tagged commit, manual
> - Coverage on cron nightly master, tagged commit, manual
> - For crons not triggered manually, keep run only when something changed in the repo since last run OR last run failed. Saves computes and cleaner coverage tracking. e.g github.community/t/trigger-action-on-schedule-only-if-there-are-changes-to-the-branch/17887

**Comment by wsnyder** [comment]
Closing due to age and think most of these CI features are in place, if there's additional improvements please consider a pull request.
