### ISSUE TITLE
Struct in input port

### ISSUE THREAD

**Issue by jcastillo** [verilator/verilator#2744]
Hi,

I am trying to assign values from C++ to a port declared as a packed struct. 

typedef struct packed{
  logic         req_raw;
  logic         req;
.....
} struct_name;

struct_name port_in;

I see that this struct is converted to:
 VL_IN64(struct_name,52,0);

So, all its internal structure is removed.
Is there any way of avoid that?

What I am trying to run this is to create the struct in C++ assign the fields values and then assign the whole struct to the input:

struct struct_in{
   CData/*0:0*/  req;
   CData/*0:0*/  req_raw;
...
};

struct_in st;

st.req = 0;
st.req_raw = 0;

a_uut->struct_name = st;

But it is also failing.

Is there any recommended way to do this?

Regards

**Comment by wsnyder** [comment]
No, sorry, you need to pack the bits yourself.  #860 is a request to build structures to help with this.
