### ISSUE TITLE
`vlcovgen` is not executed with python

### ISSUE THREAD

**Issue by SamuelRiedel** [verilator/verilator#2772]
It seems `src/vlcovgen` has recently been converted from Perl to Python (https://github.com/verilator/verilator/commit/93476a737282f11fea39b6c40ec1b8b2f0628f8b). However, the script is still called with Perl in the build process:
https://github.com/verilator/verilator/blob/05bb24df6c20c76363887094bf68fb6e03c03780/src/Makefile_obj.in#L318

This prevents specifying the Python version in the configure step. Instead, the `vlcovgen` script is called with Perl. It seems to work, but the script's shebang and the system environment will determine the Python version.

``` sh
make[2]: Entering directory `/tools/verilator/src/obj_dbg'
/usr/bin/perl ../vlcovgen --srcdir ..
```

**Comment by wsnyder** [comment]
Thanks for the debug & fix.

**Comment by SamuelRiedel** [comment]
:+1: Thanks for the quick response.
