### ISSUE TITLE
Test make_tracing_c missing output

### ISSUE THREAD

**Issue by RichardEGeorge** [verilator/verilator#2787]
I've downloaded the latest copy of verilator and I'm trying to run the example in examples/make_tracing_c. I have built the verilator code from source on Ubuntu 20.04.1 with the "run in place from VERILATOR_ROOT" scheme. The issue I'm finding is that the example trace file is empty, e.g. the file examples/make_tracing_c/logs/vlt_dump.vcd is zero bytes long. Please could you provide instructions on how to get a working trace file that I can view with GtkWave or similar?

What 'verilator --version' are you using?  Did you try it with the git master version?

Verilator 4.108 2021-01-10 rev v4.108-14-g2075db3d downloaded from git master version

**Comment by wsnyder** [comment]
Thanks for the report, the example had a call to exit() which may bypass flushing the file.  Fixed in git towards next release.
