### ISSUE TITLE
Get latest version @ master as pre-compiled for CI/CD

### ISSUE THREAD

**Issue by aignacio** [verilator/verilator#2790]
Hey @wsnyder,
is there a mirror to get the latest binary of verilator for ubuntu-latest, I need that to run GA (CI/CD) but the recommended/latest version is quite far from the one here in GitHub available.

**Comment by wsnyder** [comment]
I don't know of anything building the Ubuntu packages automatically, if you find one let us know. Alternatively there are docker binaries of all versions, see https://github.com/verilator/verilator/blob/master/ci/docker/run/README.adoc
