### ISSUE TITLE
New small tool to help browsing Verilator reports

### ISSUE THREAD

**Issue by udif** [verilator/verilator#2794]
Here is a small tool I wrote up last night to help me browse a large lint run.
https://github.com/udif/verilator2html

You can use it like this:
``verilator --lint-only ... |& tee log ; verilator2html log out.html``
or
``verilator --lint-only ... |& verilator2html - out.html``

I hope this may be of help for others.

Just to make sure this is clear:
**The core technology behind these tables was not written by me.**

I merely wrote a small script that translates the Verilator output into an HTML table and stuff it into a skeleton HTML file.
My tool resides in its own repo because it requires a 'gh-pages' branch to serve two small JS and CSS files (**again, not written by me**), and this is the only way I can guarantee these files are coming directly from github and not any other 3rd part site. (For more details on why this is neeeded, please see [here](https://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github) ).

**Comment by wsnyder** [comment]
Thanks for the tool and announcement!
