### ISSUE TITLE
Internals: What work does V3Combine need to do to enable this optimization.

### ISSUE THREAD

**Issue by yanx21** [verilator/verilator#2815]
Hi:
    May I ask:
    1. What work does V3Combine need to do to enable this optimization?
    2. What is the behavior result after the optimization complete?
https://github.com/verilator/verilator/blob/4fa41c5dd8524ee31c8f37da6b7ba41e09815d80/src/V3Combine.cpp#L417-L428

**Comment by wsnyder** [comment]
I don't recall what broke with this - you could enable it and find out - but as I recall it was not finding many good candidates to be worth it. #2631 I suspect is currently where the largest gain for investment is.  If you'd like to investigate either would be appreciated.
