### ISSUE TITLE
Windows MSVC++ build issue

### ISSUE THREAD

**Issue by dt-snps** [verilator/verilator#2831]
I'm running into a compatibility issue when trying to compile a Verilated model using MSCV++ (2019) - using version 4.110.  

Build gives me the following error:

C:\cygwin\tools\verilator\4.110\share\verilator\include\verilated_sym_props.h(97): error C2397: conversion from 'VerilatedVarProps::<unnamed-enum-MAGIC>' to 'const vluint32_t' requires a narrowing conversion

Seems that enums in MSVC are 64-bit?  I can fix by explicitly casting to vluint32_t in the class, but it's a hack.

Running verilator with --compiler msvc doesn't help.

Is there some other way I can resolve this without hacking the .h file?

**Comment by wsnyder** [comment]
Try adding a U to the end of the constant on that line, I suspect it really means it's upset about the sign bit.  If this works we'd appreciate a pull request to fix it.

**Comment by wsnyder** [comment]
UL that is, editing comment...

**Comment by dt-snps** [comment]
I tried that, but no joy. 

Is there a reason for using enum instead of just, eg. const vluint32_t MAGIC = 0xddc4f829; ?

**Comment by wsnyder** [comment]
Only legacy that verilator didn't use C++11 originally, please try "constexpr vluint32_t MAGIC = 0xddc4f829UL;"

**Comment by dt-snps** [comment]
"constexpr vluint32_t MAGIC = 0xddc4f829UL;" doesn't work - I think because MAGIC is defined inside the class.

Using "const" instead of "constexpr" will work, or defining it as "constexpr" outside of the class also works.

**Comment by wsnyder** [comment]
Sorry should be "static constexpr vluint32_t MAGIC = 0xddc4f829UL;"  using just const will upset some compilers as needs declaration in .cpp file.

**Comment by dt-snps** [comment]
OK, that worked.  Shall I do a pull request?

**Comment by wsnyder** [comment]
Please, and add you name to docs/CONTRIBUTORS if not present, thanks!

**Comment by wsnyder** [comment]
Thanks for your first pull!
