### ISSUE TITLE
Verilator Multithreaded not Working on Apple Silicon

### ISSUE THREAD

**Issue by BracketMaster** [verilator/verilator#2837]
```bash
In file included from <built-in>:1:
In file included from ./VCounter.h:12:
In file included from <built-in>:1:
In file included from ./VCounter.h:In file included from <built-in>:1:
In file included from In file included from ./VCounter.h:12:
/opt/local/share/verilator/include/verilated_threads.hIn file included from :/opt/local/share/verilator/include/verilated_threads.h:43:
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/cpuid.h:1112::
2In file included from :/opt/local/share/verilator/include/verilated_threads.h :error: this header is for x86 only
4343:
```

Verilator works mostly on new Apple Silicon, but only with `--threads 1``
Unfortunately, [cpuid_count](https://clang.llvm.org/doxygen/cpuid_8h_source.html) for llvm
was never and probably won't be ported to ARM.

Verilator references `cupid_count` to set some multithreaded settings on
Apple platforms as seen [here](https://github.com/verilator/verilator/blob/master/include/verilated_threads.h#L154)

> Would you be willing to try to fix Verilator yourself with assistance?

Sure. This shouldn't be too hard to fix. I'd just need to know what verilator is
looking for from `cpuid_count`

**Comment by BracketMaster** [comment]
I suspect that it uses `cupid_count` for NUMA control?
If so, could probably just remove it entirely for Apple Silicon
and let the OS decide how to pin threads to cores?

**Comment by wsnyder** [comment]
You can temporarily comment that out and the only side effect is the gantt profiling won't work correctly.  I'm sure there's some way to get the information so if you could please figure out the appropriate code & ifdef's and make a pull it would be appreciated.

**Comment by wsnyder** [comment]
Closing due to age - might even be fixed.  If not, we welcome a pull request for this or any portability enhancements.
