### ISSUE TITLE
cmake script reports version with date in verilator_VERSION

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#2881]
Verilator's cmake scripts return verilator_VERSION="4.200 2021-03-12" when most all other packages only return version.

Please consider removing the date in order to make version printout look like in other packages.

Thank you,
Yuri

**Comment by wsnyder** [comment]
Might you be able to submit a pull request to fix this?

**Comment by wsnyder** [comment]
Alternatively perhaps @patstew might be willing to fix this?
