### ISSUE TITLE
Change dump instead of full dump used when changeing fst dump files

### ISSUE THREAD

**Issue by davidmetz** [verilator/verilator#2888]
When splitting fst waveforms into multiple files by closing the old file and opening a new one, change dump is used instead of full dump.
This means that signals that do not change at the beginning of the second waveform start out as invalid and might remain so.
The reason for this is that `m_fullDump` is only set to true in the constructor and not when opening an fst file

**Comment by wsnyder** [comment]
Thanks for fixing this.
