### ISSUE TITLE
V3Premit goes into infinite loop on always read-and-write

### ISSUE THREAD

**Issue by RaynardQiao** [verilator/verilator#2898]
verilator version：master   2021.4.16

error message：
No error information is displayed.   No cpp file is generated.

cmd is:
verilator_bin --sc --top-module twocounter  twocounter.v

Code twocounter.v:

```
typedef struct packed {
    logic [3-1:0]  car_en;
} car_liquid_rpv_s;
typedef struct packed {
    car_liquid_rpv_s   liquid_rpv;
}car_rpv_s;
typedef struct packed {
    logic  car_enable;
    car_rpv_s   car_rpv;
    logic [2-1:0] car_sn;
} car_pv_s;
typedef struct packed{
    car_pv_s   car_pv;
}car_sch_ctxt_s;
module twocounter (car_sch_rsp_pv_ctxt, car_action_pv_ctxt);
    input car_sch_rsp_pv_ctxt;
    output car_action_pv_ctxt;
    car_sch_ctxt_s  car_sch_rsp_pv_ctxt;
    car_sch_ctxt_s  car_action_pv_ctxt;
    always @(*) begin
        car_action_pv_ctxt = car_sch_rsp_pv_ctxt;
        if (car_sch_rsp_pv_ctxt.car_pv.car_enable == 1'b1) begin
            car_action_pv_ctxt.car_pv.car_rpv.liquid_rpv.car_en[ car_action_pv_ctxt.car_pv.car_sn] = 1'b0;    // causing problem
        end
    end
endmodule
```

The statement causing the problem is “car_action_pv_ctxt.car_pv.car_rpv.liquid_rpv.car_en[ **car_action_pv_ctxt**.car_pv.car_sn] = 1'b0;”

If you change the code to “car_action_pv_ctxt.car_pv.car_rpv.liquid_rpv.car_en[ **car_sch_rsp_pv_ctxt**.car_pv.car_sn] = 1'b0;”, the problem is solved. But I think the original code is still a issue.

**Comment by wsnyder** [comment]
Thanks for the good test case - should be fixed in master.
