### ISSUE TITLE
How to read/write internal signals from gate level

### ISSUE THREAD

**Issue by RuochenDai78** [verilator/verilator#2902]
Hello

Here is my question: for example, there is *reg [2:0] a* in the RTL code, and after mapping it into gate-level, three DFFs are used to hold *a[0]*, *a[1]* and *a[2]* and a is declared as *wire* type. Then how can I access *a* in the cpp wrapper?

Thanks

**Comment by wsnyder** [comment]
Please see https://verilator.org/guide/latest/faq.html#how-do-i-access-signals-in-c

Closing as hopefully that answers it, feel free to post a followup question here.
