### ISSUE TITLE
Verilator does not respond 

### ISSUE THREAD

**Issue by Bill94l** [verilator/verilator#2906]
Hello,

launching verilator 4.104 with the following command : work-ver/Variane_testharness hello.elf  in order to simulate the CVA6-RISCV64

gives me the following result which remains unchanged :
```
$ work-ver/Variane_testharness hello.elf 
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 33743
warning: tohost and fromhost symbols not in ELF; can't communicate with target

```
I don't know what I need to do for the simulation to run?!

**Comment by wsnyder** [comment]
These are not Verilator symbols, check with the larger project - Veriane?
