### ISSUE TITLE
incorrect simulation result for cast of ~

### ISSUE THREAD

**Issue by Magpie7** [verilator/verilator#2912]
Hi,

I have seen surprising results from the following.

```
initial begin
   $display("%02b", 2'(~1'b1));
end
```
I would expect `10` verilator produces `00`

I think verilator should warn in this situation as the behaviour could catch people out.

**Comment by wsnyder** [comment]
Rather than warn, Verilator should fix the cast to properly resize the value.

Might you be able to look into a pull request that adds this to the tests, and fixes V3Width (probably AstCast or somewhere around there) to work correctly in this case?

**Comment by wsnyder** [comment]
This gets the correct results on master, so assuming it got fixed somewhere along the line.
