### ISSUE TITLE
%m format implementation

### ISSUE THREAD

**Issue by agrobman** [verilator/verilator#2932]
when I run my code with %m format, verilator adds one more layer of hierarchy to the output vs VCS/XRUN .
Is this intentional?

verilator gives something like TOP.tb vs just tb for 
$display("%m"); in top module tb...

**Comment by wsnyder** [comment]
It adds whatever name you construct the model with.  If you use "" as the name in the constructor you shouldn't see that.

**Comment by agrobman** [comment]
what place do I construct the the model and what way do I set the name?: (main for 4.102 verilator)

 ```
 #include "Vour.h"
  #include "verilated.h"
  int main(int argc, char** argv, char** env) {
      Verilated::commandArgs(argc, argv);
      Vour* top = new Vour;
      while (!Verilated::gotFinish()) { top->eval(); }
      delete top;
      return 0;
  }

```

**Comment by wsnyder** [comment]
`Vour* top = new Vour{""};`

**Comment by agrobman** [comment]
thanks for the tip, 
it did help for this small example with its C++ file, but it does not work for Swerv  test_tb_cpp:

I changed this line:

`  Vtb_top* tb = new Vtb_top{""};`

but %m  still gives me:

`me=TOP.tb_top.tracer`

What could be wrong here?
