### ISSUE TITLE
Split V3Hashed

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#2964]
V3Hashed has 2 functions:
- Compute tree hashes
- Act as a datastructure for detecting tree duplicates via hashing

I understand this now, but acutally caused me a lot of confusion previously. Could we split these 2 into separate things, especially as there is sometime a need for a hash, but not the duplicate detection datastructure (e.g.: #2958)? For discussion, call the hash computing thing a V3Hasher. The caching in user4 can still be preserved, so you could do `V3Hasher::uncachedHash(_)` or `m_hasher.hash(_)`, the later would then actually return a hash value.

The duplicate detecting datastructure can then be passed (and requires) a reference to a V3Hasher at construction.

**Comment by wsnyder** [comment]
Yes, this sounds like a good cleanup, it's just historical that the two were together.
