### ISSUE TITLE
Build verilator

### ISSUE THREAD

**Issue by sreersr** [verilator/verilator#2981]
![Screenshot from 2021-05-25 17-25-13](https://user-images.githubusercontent.com/83933455/119570528-3ead3600-bd7e-11eb-8bf1-1bbde26c6bb4.png)
Hi,
Whenever I build verilator with command make -j, my system is stucked and I have to restart it. I am using Verilator 4.202 2021-04-24 rev v4.202-17-gaac4b709
I have attached the screenshot of error thrown here for your reference. What is the solution for this. Please help me in this regard.

**Comment by wsnyder** [comment]
Your system is likely paging due to too much memory used by the compiler.  Use "make -j 4" where the number is how many CPUs you have, or try a smaller number.  You might need to "make clean" to get rid of partial files.
