### ISSUE TITLE
Verilator version issue

### ISSUE THREAD

**Issue by Talha-Ahmed-1** [verilator/verilator#2987]
`3.904` version is installed in my ubuntu. I update my chisel to 0.5 Snapshot so it needs to upgrade verilator to 4.028. I uprgade the verilator to `4.028` but it again gives `verilator --version = 3.904`
How to properly upgrade the verilator version.

**Comment by wsnyder** [comment]
Installed Verilator the first time (3.904) how?  And installed the new one how?  Are you sure it was the same way?

I presume chisel just calls the verilator in your normal PATH (what "which verilator")shows you).

For example make sure  "which verilator" shows the location you installed into.  Or, install into a new location and update your PATH appropriately.
