### ISSUE TITLE
Access top-level parameter value from Verilated model

### ISSUE THREAD

**Issue by corco** [verilator/verilator#3000]
I would like to access top-level parameter value from C++/SystemC testbench. Basically, if the model is as such:

```sv
module dut #(
  parameter int MY_PARAM = 2
) ();
endmodule : dut
```

I would like to be able to do `Vdut::MY_PARAM` and get 2 or whatever `-gMY_PARAM=x` was used to verilate.

**Comment by wsnyder** [comment]
If you mark it public the value should appear in the header.

      parameter int MY_PARAM /* verilator public_flat_rd */ = 2
