### ISSUE TITLE
Wrong version reported with `--version`?

### ISSUE THREAD

**Issue by kaddkaka** [verilator/verilator#3001]
I just downloaded verilator 4.202, unzipped it and executed `verilator-4.202/bin/verilator --version`, but my output is "Verilator 3.916 2017-11-25 rev verilator_3_914-65-g0478dbd" why could that be?

My old binary was that version but I even renamed it: `/usr/bin/verilator` ->  `/usr/bin/verilator_old`

**Comment by wsnyder** [comment]
You must still have the old version somewhere, see what "which verilator" shows, and/or "printenv" and look for VERILATOR settings.

**Comment by wsnyder** [comment]
Then that file is wrong, maybe you mis-built verilator - start from scratch again?  There's no way verilator itself has a problem related with this, it must be something related to your building or installing.

**Comment by wallento** [comment]
> I just downloaded verilator 4.202

Do you have the link that you downloaded?

**Comment by kaddkaka** [comment]
I did not do any build or install steps, I downloaded from the release page and unzipped this one: https://github.com/verilator/verilator/archive/refs/tags/v4.202.zip

**Comment by wallento** [comment]
That's not a build, but "only" the source code. This is a wrapper around the binary. What is your output for `which verilator_bin`?

**Comment by kaddkaka** [comment]
oh ok, that explains it, then I should build it, thanks.
