### ISSUE TITLE
Add limit to V3Expand to prevent large replication operation runaway

### ISSUE THREAD

**Issue by margej** [verilator/verilator#3005]
Something similar to the following code caused an out-of-memory error when evaluated as part of a larger design. In this example allocation peaked at a little over 12GB on my CentOS7 system:

```
module t #( parameter NV = 2500) (
    input          a,
    input          w1,
    input  [127:0] w2,
    output [ 31:0] o
);

wire [NV-1:0] d = a ? NV'(0) : {NV{w2}};
assign        o = d[31:0];

endmodule
```
Version 4.102 was used with the following command line:
```
verilator --cc t.v
```

The issue was due to a coding error where w1 should have been used instead of w2, and the WIDTH warning emitted makes this clear, but I was wondering if there was an underlying issue under the hood causing the allocation explosion?

**Comment by margej** [comment]
The issue appears to occur in V3Expand

**Comment by wsnyder** [comment]
It's definitely over-aggressive. I'll add a limit to prevent this insanity.
