### ISSUE TITLE
Design not compiling even though only warnings are reported

### ISSUE THREAD

**Issue by udif** [verilator/verilator#3025]
I've been trying to use v4.203 to simulate an entire RTL design (1300+ files).

My simulation script has been basically this:
```
~/bin/verilator --error-limit 10000 --cc -f project_file_list.f | & tee log_cc
```
`project_file_list.f` has been filtered to include only the files needed for the top level RTL and anything below it.
Unfortunately, the compilation ends with:
```
$ grep '^%Error' log_cc
%Error: Exiting due to 4979 warning(s)
```
I have checked `obj_dir/` and it contains files for only some of the modules. Verilator clearly hasn't finished compiling the design.
Analyzing the log file reveals:
```
$ awk '{print $1}' log_cc | sort | uniq | grep ^%
%Error:
%Warning-CASEINCOMPLETE:
%Warning-COMBDLY:
%Warning-IMPLICIT:
%Warning-LATCH:
%Warning-MULTIDRIVEN:
%Warning-REDEFMACRO:
%Warning-UNOPTFLAT:
%Warning-UNSIGNED:
%Warning-WIDTH:
%Warning-WIDTHCONCAT:
```
As it can be seen in the previous `grep`, the `%Error` above is only due to the final error message copied above. There are no additional `%Error` messages in the log, just `%Warning`.

Out of the warnings above, `MULTIDRIVEN` was caused by a 2D array that has separate bits driven by separate processes. `LATCH` is due to a behavioral clock gating cell. The document mentions that clock gating cells may impact performance, but should work. I plan to start optimizing things only after I get this to run.

So my question is:
Why isn't my design compiling? Is any of the warnings above actually a hard error?

**Comment by wsnyder** [comment]
Errors are fatal, hence the final "%Error".  If you don't want that, please use -Wno-fatal
