### ISSUE TITLE
How to speed up Verilator run

### ISSUE THREAD

**Issue by aignacio** [verilator/verilator#3057]
Hi,
I have a design of a MPSoC with has +100 cores, to generate the model it's taking a long time and I was reading about the *Hierarchical Verilation*, how does exactly can I insert /*verilator hier_block*/ in my design to speedup the Verilation process? Is it in the core itself or in the CPU that's part of each tile of the MPSoC?

**Comment by wsnyder** [comment]
I'm not sure what's the difference between the core and CPU, but would suggest, for whatever module there's 100 of, create a .vlt file with e.g.:

```
`verilator_config
hier_block -module "module_name_used_100_times"
```

If this is named hier.vlt, then you'd add hier.vlt to the verilator command line.
