### ISSUE TITLE
FSM conversion schema for arbitrary blocking processes

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#3058]
This is an idea for a schema (algorithm) to convert arbitrary procedural
code written in the body of a SystemVerilog process (as defined in IEEE
1800-2017 Chapter 9), containing blocking constructs into resumable FSMs,
which can then be used to implement arbitrary SystemVerilog processes
without the need for context switching the executing host machine (i.e.: an
implementation in pure C++ without any additional concurrency primitives). I
presume the prototype in #2409 implements an idea very similar to this for
basic delay control, however the following should apply to any process
process. I apologise if a discussion issue already exists around this, but
it might be helpful to keep this separate and self contained.

To set the scene, it is worth summarizing the current behaviour of
Verilator. Currently we can compile SystemVerilog code that does not include
any processes that require blocking the execution of the process. By
blocking I refer to any delay control, event control, or other process
control construct that would require the process state to be saved and then
execution resumed at a later point (possibly still within the same time step,
but at a different invocation, or at a different point in the top level
eval). Such non-blocking processes have the nice property that once we know
at a point in the simulation that the process needs to be started, then we
know it can be evaluated to completion at the same point in the simulation.
Verilator utilizes this property to statically schedule all processes (all
of which are non-blocking), and thanks to the guaranteed completion at the
same simulation point, can do so without any explicit process state
management.

To extend the above to handle blocking processes, we will need a run-time
representation of a process. We need this for at least two reasons:
- We will need to save the state of a process, so we can resume it later
- Some SystemVerilog constructs require us to access the state of a process,
  examples of such include:
  - `join`/`join_any`
  - `wait fork`
  - `disable fork`
  - other forms of `disable`
  - the built-in process class methods as described in IEEE 1800-2017
    Section 9.7
Let us call this run-time process object `VlProcess`. This is basically the
process object as defined in IEEE 1800-2017 9.7.

We can keep implementing non-blocking processes the same way as we do right
now. For blocking processes, we need to star a new process every time the
trigger condition of the enclosing `initial`/`always`/`final` block holds.
We will discuss how we can do this later. For now let's focus on how we can
transform blocking code into resumable non-blocking code.

To transform blocking code into non-blocking resumable FSMs, we will operate
on a SystemVerilog `task` granularity. The SV distinction between a task and
a function is not important for this discussion, and we can treat functions
as if they could block as well. Note we can keep inlining tasks when
possible, but we will conceptually want the task granularity to get a
process going and to handle indirect (virtual) invocations as described
later. This means that the first transformation we do is introducing a task
to hold the body of any `initial`/`always`/`final` blocks and we rewrite
them to be of a canonical form which uses a single task invocation of this
entry point task as the body, e.g.: `always [<sense-list>] entry_task;`

To proceed, first we will tackle task calls.

The obvious thing is that we cannot rely on any stack-allocated variables,
as we do not want to switch machine state to resume the process, so we will
pack all arguments and local variables with automatic storage duration into
a context structure specific to the task, which replaces the stack frame of
the function. We will keep such context structures in a stack _data
structure_ stored in the invoking `VlProcess`.  The task specific context
structures will always hold at least 2 values, a function pointer to the
actual code implementing the task FSM, and the FSM state variable, so all
context structures will derive from the following base type:

```c++
struct VlTaskContext {
  VlTask_t *taskp; // VlTask_t is a function pointer type as shown later
                   // This member pointer is semantically `const`.
  uint32_t state = 0;  // Note: this actually could live elsewhere
};
```

The process object then holds instances of these context objects in a stack
data structure. For simplicity, I will write this stack data structure as a
C++ `std::vector<VlTaskContext*>`, but note that this could indeed be just a
char* array that we in-place append new frames to at the end, but that is an
optimisation that at this point would only distract from the discussion.

```c++
struct VlProcess {
  std::vector<VlTaskContext*> stack;
  ... // Other stuff required to implement SystemVerilog features, e.g.:
      // list of child processes. Not relevant for immediate discussion.
};
```

To be able to pass arguments to indirect (virtual) task invocation, we also
need a common context structure base class that defines the layout of the
arguments, without defining the actual task specific locals, i.e. a context
structure type specific to the signature of the task. The `this` pointer of
member tasks is part of the signature. Note this context structure type is
specific to the declaration of the task, but not to it's definition, so for
some task declaration `a` we have:

```c++
struct  VlTask_a_SignatureContext : public VlTaskContext {
  EnclosingClassType* selfp; // `this` pointer, iff member task.
  CData  arg1; // Input arg 1
  IData *arg2; // Inout arg 2
  // Remaining arguments.
};
```

Finally we of course need the full task context, with all local variables of
automatic storage duration, which is specific to the definition of the task
we want to invoke:

```c++
struct VlTask_a_FullContext : public VlTask_a_SignatureContext {
  // All automatic variables
};
```

We are now ready to invoke a task. To perform an invocation using static
dispatch (i.e.: direct function call), given the current `vlProcess`, we
simply:

```c++
  // Allocate new context for the callee (we can assume this initializes
  // the taskp function pointer and the state variable, and the `this`
  // pointer if the target is a method).
  VlTask_a_SignatureContext *ctxp = new VlTask_a_FullContext(<self-poitnter-iff-member>);
  // Push context to process stack
  vlProcess->stack.push_back(ctxp);
  // Assign arguments
  ctxp->arg1 = ...
  // Call the implementing function, passing the current process, and the
  // context itself. The task function returns a bool indicating blocking
  bool blocked = ctx->taskp(vlProcess, ctx);
```

From the above we see the type of `taskp` in `VlTaskContext` should be
`void (*)(VlProcess*, VlTaskContext*);`

To perform an invocation using dynamic dispatch (indirect task call/virtual
tak call) is almost the same, except that we construct the context object via
a virtual function/function pointer:

```c++
  // Allocate new context via dynamic dispatch (we can assume this initializes
  // the taskp function pointer, the state variable and the `this` poiter)
  VlTask_a_SignatureContext *ctxp = recipient->alloc_VlTask_a_Context();

  // The rest is the same as for a static dispatch call:

  // Push context to process stack
  vlProcess->stack.push_back(ctxp);
  // Assign arguments
  ctxp->arg1 = ...
  // Call the implementing function, passing the current process, and the
  // context itself. The task function returns a bool indicating blocking
  bool blocked = ctx->taskp(vlProcess, ctx);
```

The above task invocations will return true if the task is blocked, and
false if the task is completed (returns). We now need to transform the body
of the task into into a resumable state machine.

A note on procedural blocking constructs: As far as I can see, every
SystemVerilog blocking construct can be re-written (in combination with the
state machine transformation I am about to describe) as a simple `wait`
statement of the form `wait <predicate>;`, which simply blocks the current
process until the predicate becomes true. For this reason, I will only
consider translating such simple `wait` statements (I will present the
translation of other blocking constructs to such `wait` statements later).

We will transform all blocking tasks into C++ functions with the following
signature and basic structure, involving a loop over a case statement that
represents the state system. The key to resumability, is that all blocking
`wait` statements must be the first statement in a state. We convert `wait
<predicate>;` into `if (!predicate) return true`. Example for a task named
`a`:

```c++
// Return indicates blocked (true) or complete (false)
bool a(VlProcess* vlProcess, VlTaskContext* gctxp) {
  // Note the type of gctxp could be `void*`, but it should always be known
  // to be at least the base `VlTaskContext*`.

  // Cast context to specific type
  VlTask_a_FullContext *const __restrict ctxp = static_cast<VlTask_a_FullContext*>(gtxp);

  // Infinite loop
  for (;;) {
    // state dispatch
    switch (ctxp->state) {
      case 0: // Initial state
        if (wait_condition_is_false) return true; // suspend, indicate blocked
        ... // Do stuff
        ctxp->state = 1;
        break; // Can optimize to fall through later, irrelevant to scheme
      case 1: // Other state
        if (other_wait_condition_is_false) return true; // suspend again
        ...
        break;
      case 2: // Yet another state
        ...
        break;
      case 3: // Final state
        return false; // task completed (returned)
      default: abort(); // This is a Verilator bug
    }
  }
}
```

As all suspension is at the beginning of a case branch, the above state
machine can be resumed by simply calling the function again with the same
context, which will re-evaluate the wait condition and proceed accordingly.

From the above, it is fairly obvious how to translate straight line code with
`wait` statements into a state machine:

```systemverilog
task a()
  foo = ~foo;
  wait cond_0;
  bar = ~bar;
  wait cond_1;
  baz = ~baz;
  wait cond_2;
endtask
```

Becomes:
```c++
for (;;) {
  switch (ctxp->state) {
    case 0:
      foo = ~foo;
      ctxp->state = 1;
      break;
    case 1:
      if (!cond_0) return true;
      bar = ~bar;
      ctxp->state = 2;
      break;
    case 2:
      if (!cond_1) return true;
      baz = ~baz;
      ctxp->state = 3;
    case 3:
      if (!cond_2) return true;
      return false;
  }
}
```

The algorithm outline is:
1. Keep assigning non-blocking statements to current state.
2. When encountering a blocking sate, allocate new state.
3. Assign blocking statement to new state, transforming it into
  `if (!cond) return false`
4. Set current state to new state. Goto 1.

Handling branching statements is also relatively easy. For the purposes of
the algorithm, it is useful to think of `begin`/`end` blocks as a 1-way
branch, while an `if` statement is a 2-way branch, and a `case` statement is
an n-way branch. When encountering a branching statement, if none of the
branches can block, then simply assign the whole branching statement to the
current state, otherwise allocate a new "follower state", assign the
branching statement, with each branch trimmed to its non-blocking prefix to
the current state, and recursively convert each remaining blocking suffix as
if it was a standalone list of statements, finishing by going to the
"follower state". This can be implemented with a short recursive algorithm.
Example of the transformation:

```systemverilog
  if (x) begin
    if (y) begin
      foo = ~foo;
    end else begin
      bar = ~bar;
      wait cond_1;
      baz = ~baz;
    end
  end else begin
      quux = 1;
      wait cond_2;
      quux = 2;
      wait cond_3;
      quux = 3;
  end
  wait cond_4;
  done = 1;
```

Which converts to:
```c++
for (;;) {
  switch (ctxp->sate) {
    case 0:
      if (x) {
        if (y) {
          foo = ~foo;
          ctxp->state = 10; // follower state
        } else {
          bar = ~bar;
          ctxp->sate = 1;
        }
      } else {
        quux = 1;
        ctxp->state = 2;
      }
      break;
    cawse 1:
      if (!cond_1) return true; // Might block
      baz = ~baz;
      ctxp->state = 10; // follower state
      break;
    case 2:
      if (!cond_2) return true; // Might block
      quux = 2;
      ctxp->state = 3;
      break;
    case 3:
      if (!cond_3) return true; // Might block
      quux = 3;
      ctxp->state = 10; // follower state
      break;
    case 10:
      if (!cond_4) return true; // Might block
      done = 1;
      return false; // Task complete
  }
}
```

We also need to convert loops, in case we need to block within the loop
body. As any loop can be simply rewritten into a `forever` loop with `break`
and `continue`, I will only consider this. Similarly to the branches, we
need a new state past the end of the loop, which is the target of any
`break` statement, but we also need a state at the loop entry, which is the
target of any `continue` statement (including the implicit `continue` at the
end of the forever loop body):

```systemverilog
  foo = ~foo;
  forever begin
    bar = ~bar;
    wait cond_1;
    if (last) break; else continue;
  end
  baz = ~baz;
```

Converts to:

```c++
for (;;) {
  switch (ctx->state) {
    case 0:
      foo = ~foo;
      ctxp->state = 1; // go to loop entry
      break;
    case 1:
      bar = ~bar;
      ctxp->state = 2;
      break;
    case 2:
      if (!cond_1) return true; // Might block
      if (last) {
        ctxp->state = 3; // State after loop
      } else {
        ctxp->state = 1; // Loop bakc
      }
      break;
    case 3:
      baz = ~bax;
      return false; // Task complete;
  }
}
```

Note the above could be optimized by pushing state 3 into the `true`
branch of the `if (last)` branch, but that is a separate consideration.

The above transformations nest recursively (I know this for a fact as Alogic
basically does the above) and to my knowledge handle all procedural
SystemVerilog code that does not involve a task call. Adding task calls is
easy however. I have already described the invocation schema. There are 2
additional thing to consider one is how to clean up the context on return,
the second is how to handle suspension in the callee. For this, let's look
at how a `VlProcess` is actually created, started, suspended and resumed.

Note: There is a question regarding scheduling of blocking processes (i.e.: at
which point in the eval loop to create and resume them). For simplicity we can
schedule blocking processes based on variable accesses assuming blocking
statements do not block, i.e.: as if the whole block executes when written.
E.g.:
```systemverilog
 always @(posedge clk) begin
    a = ~a;
    forever begin
      wait cond;
      c = c + a;
    end
 end
```
We can schedule that as if it was:
```systemverilog
 always @(posedge clk) begin
    a = ~a;
    forever begin
      cond; // Assume read here
      c = c + a;
    end
 end
```

To implement the always block, we then, at the point where the always block was
scheduled:
```c++
  if (~clk_last & clk /* posedge */) {
    // Need to start new process
    VlProcess *newProcess = new VlProcess;
    // We need to keep a handle to it (note we probably need a shared_ptr or
    // similar as there can be multiple references to the process)
    vlSymsp->processListForThisAlwaysBlock.push_back(newProcess);
    // Arrange for invocation of entry task (this initializes taskp and
    // state)
    VlTaskContext *const ctxp = new VlTask_entry_task_FullContext
    // Note, this task has no arguments as it was constructed by Verilator
    // Push to stack
    newProcess->stack.push_back(ctxp);
    // Do not invoke (as if it started suspended in state 0)
  }
  // Resume all instances of the process created by the above always block,
  // this incldues the one we just created right now (if any).
  for (VlProcess *const vlProcess : vlSymsp->processListForThisAlwaysBlock) {
    for (;;) {
      // Grab top of stack context
      VlTaskContext *const ctxp = vlProcess->stack.back();
      // Resume the process
      const bool blocked = ctxp->taskp(vlProcess, ctxp);
      if (blocked) break; // Process blocked, move on to next process
      // Current task on stack completed, pop it's context
      vlProcess->stack.pop_back();
      // Was this the entry task?
      if (vlProcess->stack.empty()) { // could also do ctxp->taskp == entry task
        // It was the entry task, so the process itself is now completed
        // Free process
        remove vlProcess from vlSymsp->processListForThisAlwaysBlock;
        break; // Process complted, move on to next process
      }
      // Still more tasks suspended on the stack of this process, so keep
      // going, resuming all of those.
    }
  }
```

Sidenote: Scheduling of the blocking processes could be improved, by
scheduling them based on state and relocating them to a different queue in
eval at runtime when they block, but I think with the above worst case we do
have a change detect loop, but otherwise should function.

We can now see what we need to do to call one task from another task's state
system:

```systemverilog
task caller_task();
  foo = 0;
  callee_task(10); // Task call, might block
  foo = 1;
endtask
```

Becomes:
```c++
bool caller_task(VlProcess* vlProcess, VTaskContext* gctxp) {
  VlTask_caller_task_FullContext *const __restrict ctxp = static_cast<VlTask_caller_task_FullContext*>(gtxp);

  for (;;) {
    switch(ctxp->state) {
      case 0:
        foo = 0;

        // Now call callee_task

        // Allocate context/stack frame
        VlTask_callee_task_SignatureContext *const calleCtxp = <new context, static or dynamid dispatch as needed>;
        // Push context to process stack
        vlProcess->stack.push_back(calleeCtxp);
        // Assign arguments
        calleCtxp->arg = 10;

        // We need reference to the calle context, in case it get's
        // suspended and popped by the resumption in the eval loop
        ctxp->caleeCtxp = calleCtxp;

        // Set our next state to past the invocation, so we are resumed in
        // the right place
        ctxp->state = 1

        // Now call the FSM implementing the callee
        const bool blocked = calleCtxp->taskp(vlProcess, calleCtxp);

        if (blocked) {
          // If callee task was blocked, then this task is blocked as well
          return true;
        } else {
          // callee finished immediately. We need top op it's context off,
          // as the process resumption loop will not do it
          vlProcess->stack.pop_back();
        }

        break;
      case 1:
        // This is the state after the return from the callee task. We end
        // up here either immediately if the calle did not block, or via the
        // resumption of the process, in either case the job is the same:

        VlTask_callee_task_SignatureContext *const calleeCtxp = ctxp->calleeCtxp;

        // Note: we can unpick in-out arguments or retufn values form the
        // callee context here if necessary

        // Free callee context (it was already popped)
        delete calleeCtxp;

        // Call done.

        foo = 1;
        return false; // caller_task done;
    }
  }
}
```

I believe with all of the above, we can now start, suspend and resume
processes wiht arbitrary call stacks of both statically and dinamically
invoked blocking tasks, without any machine context switches. There are
opportunities for improvements/optimizations, but the general idea of the
scheme is as presened.

We have a couple things left to consider. First let's look at various
blocking expressions other than `wait`:

```systemverilog
task delayed();
 foo = 2;
 #N;
 foo = 3;
endtask
```

Quite simple conceptually, but we need 2 extra bits: A "next time point this
process should be resumed" variable in the VlProcess, and a global heap
(priority queue) of expected future time values so we don't need to eval on
every time value:

```c++
bool delayed(VlProcess* vlProcess, VlTaskContext* gtxp) {
  VlTask_delayed_FullContext *const __restrict ctxp = static_cast<VlTask_delayed_FullContext*>(gtxp);

  for (;;) {
    switch (ctxp->state) {
      case 0:
        foo = 2;
        // Comptue when to resume
        vlProcess->nextResumptionTime = vlSymsp->currentTime() + N;
        // Add time point to time queue
        vlSymsp->timeQueue.insert(vlProcess->nextResumptionTime);
        // Move to wait state
        state = 1;
        break;
      case 1:
        if (currentTime() < vlProcess->nextResumptionTime) retrurn true; // Blocked
        assert (currentTime() == vlProcess->nextResumptionTime) // Otherwise we missed something
        foo = 3;
        return false; // Complete
        break;
    }
  }
}
```

Event control expressions seem fairly simple, they translate into `wait`
with `$rose`, `$fell`, etc, so I will not go into more detail.

Sequence events (IEEE 1800-2017 9.4.2.4) seem a bit tricky, but they appear
to be a conceptually orthogonal problem (need to detect sequence triggered
condition separately, then wait for that)

The above scheme also supports generic `disable`. Self disabling blocks
simply move to the right state on disable. A simple way of disabling
arbitrary other blocks it is to convert anything that can be a target of a
disable to a `task` (this does required forwarding via inout parameters of
any outer locals), and then pop the contexts of all suspended processes that
might have that process active. They should then resume after the disabled
block as expected. Another way of doing it is to force the suspended FSMs
into the right state simply by setting the state variables to the right
values. Lot of complicated detail here, but conceptually seems doable.

We can also do `fork`. We need to add the new `VlProcess` to a list of
children stored in the current `VlProcess` executing the `fork`, and we also
need to add the new `VlProcess` to some global queue that is re-invoked form
the eval loop for resumption. We can then do `join`/`join_any` simply by
waiting for all/one of the newly created processed to have completed.

We can similarly, do `disable fork` and `wait fork` based on the children
list of the current `VlProcess`.

What's wrong with the above?

**Comment by wsnyder** [comment]
Short answer is I don't think anything's wrong with the above :)

Additional Background
=====================

As you noted there are some other threads describing this, most notibly a similar technique in #2409. Also there's work on making "true" processes using threads in #2446 and #2549, I know there's been a great deal of work on a Antmicro branch which is showing some life.  I suspect even use of real threads will require some good FSM techniques in some cases to get good performance.

First note what #2409 can do now.  Given:

      #(8.0:5:3) clk = 1;
      forever begin
         #5 clk = ~clk;
      end

It will make:

    {
        {
            {
                if ((1U == vlSelf->__vProc1Fsm)) {
                    vlSelf->__vProc1Fsm = 0U;
                    goto __Vlabel2;
                } else if ((2U == vlSelf->__vProc1Fsm)) {
                    vlSelf->__vProc1Fsm = 0U;
                    goto __Vlabel3;
                }
                vlSelf->__vProc1Fsm = 1U;
                Verilated::timedQPush(vlSymsp, VL_TIME_Q() + 5ULL, &(vlSelf->__vProc1Event));
                goto __Vlabel1;
                __Vlabel2: ;
                // From __vProc1Fsm state 1
                vlSelf->t__DOT__clk = 1U;
                while (1U) {
                    vlSelf->__vProc1Fsm = 2U;
                    Verilated::timedQPush(vlSymsp, VL_TIME_Q() + 5ULL, &(vlSelf->__vProc1Event));
                    goto __Vlabel1;
                    __Vlabel3: ;
                    // From __vProc1Fsm state 2
                    vlSelf->t__DOT__clk = (1U & (~ (IData)(vlSelf->t__DOT__clk)));
                }
            }
        }
        __Vlabel1: ;
    }

Note this has the state variables and timing queue as you discuss.  It uses goto's and labels as that's something Verilator can already handle. At present there is no optimization step - obviously that should be done as currently the above is spaghetti code that can have most of the labels and goto's compressed out.

There are also some additional interesting FIXME files and comments if you "git diff master...issue-2409-timing"

As to the described extensions
==============================

As to the idea of using FSMs, I think that's probably the best performing method for small code (e.g. clock generators) if not a lot more. That we might be able to expand across functions/tasks/etc would make this extremely attractive, I don't think that was previously considered a reasonable option but your description makes me hopeful.

Several of the basic techniques exactly align to #2409 and some have been implemented.  What you describe in is of course significant additional implementation work, but I see no reason why that would not work and perform well.  I suspect the compiler won't optimize such functions as well, so we'd only want to do your stack steps when a given function might have a fork/etc underneath as determined by static analysis.

We should also consider the IEEE Stratified event scheduler requirements - this can be done by having multiple timing queues, and is perhaps better explored after the basic techniques ignoring that are completed (and merged?)

I'd strongly encourage looking at #2409 and extending it to explore these techniques.  (And/or get even some small features of #2409 into production, as #2409 is painful to keep merging from master).

**Comment by wsnyder** [comment]
Conversational issue only (and a great one at that), so closing.
