### ISSUE TITLE
Mailing list?

### ISSUE THREAD

**Issue by dosadi** [verilator/verilator#3069]
Hi all,

I have a question about Verilator, but first I want to find out if there exists a Verilator mailing list, or any other discussion forum besides this GiHub Q and A.  I searched but couldn't find mention of one... is it OK to ask questions about general use of Verilator (i.e. not questions regarding the actual development of Verilator itself) here?  If so I'll go ahead and ask....

**Comment by wsnyder** [comment]
There is no discussion email, so just ask questions here please. Ideally a new issue for each separate topic, please.
