### ISSUE TITLE
Context of "Multiple top level modules" warning written to `cout` instead of `cerr` 

### ISSUE THREAD

**Issue by a2800276** [verilator/verilator#3070]
> Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)

Running verilator with multiple top candidates leads to "Multiple top level modules", the warning itself is written to `stderr`, the remaining context (source of the affected module definition) are written to `stdout`. This is very noticeable when redirecting stderr to capture the warnings.

```
stderr: %Warning-MULTITOP: src/B.v:85:8: Multiple top level modules
stderr:                                : ... Suggest see manual; fix the duplicates, or use --top-module to select top.
stdout:                                 : ... Top module 'A'
stdout:    3 | module A (
stdout:      |        ^~~~~~~~~~~~
stdout:                                 : ... Top module 'B'
stdout:   85 | module B (
stdout:      |        ^~~


```

> What 'verilator --version' are you using?  Did you try it with the git master version?

`stable` and current `master`

```
Verilator 4.211 devel rev v4.210-28-g1166728a
```

> Would you be willing to try to fix Verilator yourself with assistance?

I've attached a [diff](https://github.com/verilator/verilator/files/6846325/diff.txt) , I think this is too trivial for a PR: change `cout` to `cerr` 

```
diff --git a/src/V3LinkLevel.cpp b/src/V3LinkLevel.cpp
index 52a0ac05..728073fc 100644
--- a/src/V3LinkLevel.cpp
+++ b/src/V3LinkLevel.cpp
@@ -62,7 +62,7 @@ void V3LinkLevel::modSortByLevel() {
                                           "--top-module to select top."
                                        << V3Error::warnContextNone());
             for (AstNode* alsop : tops) {
-                std::cout << secp->warnMore() << "... Top module " << alsop->prettyNameQ() << endl
+                std::cerr << secp->warnMore() << "... Top module " << alsop->prettyNameQ() << endl
                           << alsop->warnContextSecondary();
             }
         }
```

**Comment by wsnyder** [comment]
A pull request is still good for even small changes as this then runs the tests.  But the patch is appreciated too, so I pushed this, thanks.
