### ISSUE TITLE
Problem linking when using -cc -build

### ISSUE THREAD

**Issue by dosadi** [verilator/verilator#3073]
Hi all,

I am trying to build a source tree which, as part of its build system, builds the example hello_world.v and tries to link it statically into a larger binary.  The build for the hello_world.v seems to finish and produce a .o and .a files, but when it comes time for the static linkage at the very end of the build, I see these:

``
ld -z max-page-size=0x1000 -T/home/jon/controlix/src/nuttx/nuttx/boards/x86_64/intel64/qemu-intel64/scripts/qemu.ld -L"/home/jon/controlix/src/nuttx/nuttx/staging" -L"/home/jon/controlix/src/nuttx/nuttx/arch/x86_64/src/board" -L "/usr/lib/gcc/x86_64-linux-gnu/10/" \
	-o "/home/jon/controlix/src/nuttx/nuttx/nuttx.elf"  \
	--start-group -lgcc -lgcc_eh -lsupc++ --whole-archive --no-relax -lsched -lmisc -lzlib -lcxx -lcontrols -lcontrolix -ldrivers -lboards -lc -lmm -larch -lapps -lnet -lfs -lbinfmt -lboard --end-group
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrols.a(Vhello_world__ALL.o): in function `Vhello_world__Syms::~Vhello_world__Syms()':
Vhello_world__ALL.cpp:(.text+0x4d): undefined reference to `VerilatedModule::~VerilatedModule()'
Vhello_world__ALL.cpp:(.text+0x4d): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedModule::~VerilatedModule()'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrols.a(Vhello_world__ALL.o): in function `Vhello_world__Syms::Vhello_world__Syms(VerilatedContext*, char const*, Vhello_world*)':
Vhello_world__ALL.cpp:(.text+0xc8): undefined reference to `VerilatedSyms::VerilatedSyms(VerilatedContext*)'
Vhello_world__ALL.cpp:(.text+0xc8): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedSyms::VerilatedSyms(VerilatedContext*)'
ld: Vhello_world__ALL.cpp:(.text+0xdb): undefined reference to `VerilatedModule::VerilatedModule(char const*)'
Vhello_world__ALL.cpp:(.text+0xdb): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedModule::VerilatedModule(char const*)'
ld: Vhello_world__ALL.cpp:(.text+0xe9): undefined reference to `VerilatedContext::timeunit(int)'
Vhello_world__ALL.cpp:(.text+0xe9): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedContext::timeunit(int)'
ld: Vhello_world__ALL.cpp:(.text+0xf7): undefined reference to `VerilatedContext::timeprecision(int)'
Vhello_world__ALL.cpp:(.text+0xf7): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedContext::timeprecision(int)'
ld: Vhello_world__ALL.cpp:(.text+0x10e): undefined reference to `VerilatedModule::~VerilatedModule()'
Vhello_world__ALL.cpp:(.text+0x10e): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedModule::~VerilatedModule()'
ld: Vhello_world__ALL.cpp:(.text+0x11b): undefined reference to `VerilatedSyms::~VerilatedSyms()'
Vhello_world__ALL.cpp:(.text+0x11b): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedSyms::~VerilatedSyms()'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrols.a(Vhello_world__ALL.o): in function `Vhello_world___024root::Vhello_world___024root(char const*)':
Vhello_world__ALL.cpp:(.text+0x1b): undefined reference to `VerilatedModule::VerilatedModule(char const*)'
Vhello_world__ALL.cpp:(.text+0x1b): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedModule::VerilatedModule(char const*)'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrols.a(Vhello_world__ALL.o): in function `Vhello_world___024root::~Vhello_world___024root()':
Vhello_world__ALL.cpp:(.text+0x27): undefined reference to `VerilatedModule::~VerilatedModule()'
Vhello_world__ALL.cpp:(.text+0x27): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedModule::~VerilatedModule()'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrols.a(Vhello_world__ALL.o): in function `Vhello_world__Syms::~Vhello_world__Syms()':
Vhello_world__ALL.cpp:(.text+0x56): undefined reference to `VerilatedSyms::~VerilatedSyms()'
Vhello_world__ALL.cpp:(.text+0x56): relocation truncated to fit: R_X86_64_PLT32 against undefined symbol `VerilatedSyms::~VerilatedSyms()'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrols.a(Vhello_world__ALL.o): in function `Vhello_world___024root___initial__TOP__1(Vhello_world___024root*)':
Vhello_world__ALL.cpp:(.text.unlikely+0xb): undefined reference to `VL_WRITEF(char const*, ...)'
Vhello_world__ALL.cpp:(.text.unlikely+0xb): additional relocation overflows omitted from the output
ld: Vhello_world__ALL.cpp:(.text.unlikely+0x24): undefined reference to `VL_FINISH_MT(char const*, int, char const*)'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrolix.a(main.cpp.o): in function `Verilated::lastContextp(VerilatedContext*)':
/home/jon/controlix/src/verilator_runtime/include/verilated.h:689: undefined reference to `Verilated::s_lastContextp'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrolix.a(main.cpp.o): in function `Verilated::lastContextp()':
/home/jon/controlix/src/verilator_runtime/include/verilated.h:693: undefined reference to `Verilated::s_lastContextp'
ld: /home/jon/controlix/src/verilator_runtime/include/verilated.h:694: undefined reference to `Verilated::s_lastContextp'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrolix.a(main.cpp.o): in function `Verilated::threadContextp()':
/home/jon/controlix/src/verilator_runtime/include/verilated.h:707: undefined reference to `Verilated::t_s'
ld: /home/jon/controlix/src/verilator_runtime/include/verilated.h:707: undefined reference to `Verilated::t_s'
ld: /home/jon/controlix/src/verilator_runtime/include/verilated.h:708: undefined reference to `Verilated::t_s'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrolix.a(main.cpp.o): in function `__tcf_0':
/home/jon/controlix/src/verilator_runtime/include/verilated.h:712: undefined reference to `VerilatedContext::~VerilatedContext()'
ld: /home/jon/controlix/src/nuttx/nuttx/staging/libcontrolix.a(main.cpp.o): in function `Verilated::defaultContextp()':
/home/jon/controlix/src/verilator_runtime/include/verilated.h:712: undefined reference to `VerilatedContext::VerilatedContext()'
``

my main.cpp file:

``
#include "Vhello_world.h"
#include "verilated.h"

extern "C" void controlix_main(int argc, char** argv)
{
  vluint64_t main_time = 0;

  Vhello_world* hello_world = new Vhello_world;

  // "Hello, world!" test print loop
  while(!Verilated::gotFinish())
  {
    hello_world->eval();
    main_time++;
  }
``

Any ideas?  I am new to Verilator, so any help is much appreciated.  Is there an external -lverilator or something along that line that I need to link to the final binary?  I am working off a current pull of the git tree.

**Comment by wsnyder** [comment]
Specifically you seem to be missing include/verilated.cpp (.o), but there might be other files required depending on the flags you Verilated with.

In general, you need to link against compiled versions of all of the source files pointed to in the generated .mk file, $(VK_USER_OBJS) $(VK_GLOBAL_OBJS)
