### ISSUE TITLE
Origin of FST reader/writer

### ISSUE THREAD

**Issue by pieter3d** [verilator/verilator#3093]
The source in `fstapi.h` seems to imply it comes from [gtkwave](https://github.com/gtkwave/gtkwave), but I can't find matching source code there. Also, it's listed as MIT licensed, but gtkwave appears fully GPLv2.

**Comment by wsnyder** [comment]
It comes from gtkwave see the verilator_ext_tests for the copy script. https://github.com/verilator/verilator_ext_tests/blob/master/t/t_gtkwave_diff.pl

**Comment by pieter3d** [comment]
How about the license difference?

**Comment by wsnyder** [comment]
That's a question for gtkwave.
