### ISSUE TITLE
Event management

### ISSUE THREAD

**Issue by jalcim** [verilator/verilator#3118]
Hi,

I know that an event manager was in the works for verilator.
I wanted to know where this project was, and if it was possible to contribute to it.
Do you have a link, a field in the documentation, or documents on the subject to be studied ?

Thanks a lot !

**Comment by wsnyder** [comment]
See  #3058, #2409, #2446 and #2549.  We'd certainly welcome help, I suspect #3058 is the best long-term approach performance wise if you'd be able to contribute.
