### ISSUE TITLE
Bashisms in the configure file: ./configure: CFLAGS+= : not found

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#3132]
```configure``` prints this:
```
./configure: CFLAGS+= : not found
./configure: CPPFLAGS+= : not found
./configure: CXXFLAGS+= : not found
./configure: LDFLAGS+= : not found
```

configure is commonly expected to be Bourne shell compatible, but on Linux /bin/sh is a symlink to Bash.

Version: 4.212
OS: FreeBSD 13

**Comment by wsnyder** [comment]
Can you please submit a pull request to change these to something that works with FreeBSD?  Thanks.
