### ISSUE TITLE
Multidriven waiver output causes parse errors

### ISSUE THREAD

**Issue by keithcolbert** [verilator/verilator#3137]
When a multidriven warning is encountered and `--waiver-output` is given, the resulting .vlt file fails to parse on subsequent runs of Verilator. It seems the issue is that Verilator doesn't accept quoted multiline strings, or at least expects them to be expressed differently. I tried a few simple things such as `\` at the end of the lines to no avail. For context, we are trying to switch from global linting switches (`-Wno-MULTIDRIVEN`) to targeted waivers on a large project.

```
$ bin/verilator --version
Verilator 4.213 devel rev v4.212-29-ga7374e84
```

Test is here: https://github.com/keithcolbert/verilator/blob/multidriven_waivers/test_regress/t/t_multidriven_waivers.pl

I would be willing to fix this but it will take me a bit to get acquainted with the code base. It's not urgent as there are many workarounds we can use in the interim.

**Comment by wsnyder** [comment]
Duplicates #3133 2429 - @keithcolbert please see there, will comment there.
