### ISSUE TITLE
`make -j` Command Causes Crash (Unavailable Memory)

### ISSUE THREAD

**Issue by ctopal** [verilator/verilator#3139]
Hi! 

I was following [Git Quick Install](https://verilator.org/guide/latest/install.html) steps and `make -j` actually caused my laptop (Lenovo Thinkpad X1 Carbon Gen 9, 16GB) to sort of crash because of unavailable memory. It was fixed when I switched to `make -j8` but I just wanted to point out the command in the guide might create similar problems for new users in the future. 

Cheers,
Canberk

**Comment by stephenry** [comment]
Limit the number of parallel jobs to something at or below the physical core count. At times, '-j' simply spawns some huge number of parallel jobs, causing either memory exhaustion or a huge number of expensive context switches. Applies generally, not necessary limited to Verilator.

**Comment by wsnyder** [comment]
Thanks for the suggestion, documented using "make -j `nproc`"
