### ISSUE TITLE
How to get the Toggle Coverage and Functional Coverage

### ISSUE THREAD

**Issue by yuqi-ali** [verilator/verilator#3151]
I add -CFLAGS -DCOVERAGE --coverage while compile rtl, and get the coverage.dat after simulation.
After generate html report, there are no toggle coverage and functional coverage ,how to display it

**Comment by wsnyder** [comment]
Sounds like the right process. Is there information in the coverage.dat file?  When you say "no coverage" do you mean no coverage points, or the points are zero?

**Comment by yuqi-ali** [comment]
I can get the line coverage，but no toggle coverage and functional coverage.
after get the .dat file. I use these commands to generate html report
verilator_coverage -write-info coverage.info coverage.dat
genhtml coverage.info --output-directory coverage

**Comment by wsnyder** [comment]
Sorry, but you need to debug it, you need to please give a lot more information to determine what is wrong.

Can you submit a standalone example?  What sort of user coverage statements are there in the code? And are there "toggle" statements in the .dat file?  Does the verilator_coverage text output show the coverage information correctly (ignoring genhtml)?

**Comment by yuqi-ali** [comment]
Do you have some example about this? I use Verilator in SpinalHDL. And SpinalHDL

**Comment by yuqi-ali** [comment]
SpinalHDL can Simulator by using Verilator automatically

**Comment by wsnyder** [comment]
There's an example here: https://github.com/verilator/example-systemverilog

**Comment by yuqi-ali** [comment]
I test this example in Verilator 4.200 ,it seems that the Toggle Coverage and Functional Coverage still not get:
Overall coverage rate:
  lines......: 80.0% (16 of 20 lines)
  functions..: no data found

**Comment by wsnyder** [comment]
The coverage is intentionally not 100% to demonstrate what misses look like.

**Comment by yuqi-ali** [comment]
There are no messages about toggle coverage, is it right?

**Comment by wsnyder** [comment]
The coverage on lines with signal declarations are toggle coverage.

**Comment by wsnyder** [comment]
(I assume you are referring to the example I referenced)

**Comment by wsnyder** [comment]
Closing as think answered, but feel free to follow up.

**Comment by stu-e** [comment]
I have only just started looking into coverage and @yuqi-ali is correct in that 'toggle coverage' is missing. Simulators like Questa will generate reports showing which logic bits have toggled state and which have not changed state. So if you have a vector of 4 bits say and the vector only ever takes on the values of 0 and 1 then bit 0 has toggled but bits 3-1 have not. This shows part of the design has not been exercised.

**Comment by wsnyder** [comment]
Verilator collects toggle coverage, and with its own reports shows it, so I don't believe there is any issue here.  @stu-e if you see issues with verlator-generated toggle reports please open a new issue.

**Comment by wsnyder** [comment]
[Using the most recent version that is]

**Comment by stu-e** [comment]
Forgive me I'm stumped. I see what looks like toggle coverage statistics inside file coverage.dat but beyond that the post processing outlined at https://github.com/verilator/example-systemverilog/blob/master/Makefile#L66 does not produce anything showing toggle coverage. Please what am I missing?

**Comment by wsnyder** [comment]
You can't use the C-tool coverage as it doesn't know what toggle is.  Use Verilator's tools, see the Verilator documentation and Verilator's test_regress/t/t_cover_toggle_points.out

**Comment by Faisalawan11** [comment]
> I can get the line coverage，but no toggle coverage and functional coverage. after get the .dat file. I use these commands to generate html report verilator_coverage -write-info coverage.info coverage.dat genhtml coverage.info --output-directory coverage

Hello yuqi-ali, which command did you use for getting .dat file?

Waiting your response 

Thank you
