### ISSUE TITLE
Simulating a USB Host

### ISSUE THREAD

**Issue by berkguldiker** [verilator/verilator#3156]
Hello,

I am using Verilator to simulate my OpenTitan FPGA. I am working on implementing a USB HID functionality. I can see the transfers in the 'usb.log'. However, I want to confirm if the board can be used as a HID device. Is there a way to simulate a USB host using the verilator or connecting the verilated board to the PC or using Verilator with libusb or a similar software?

Thanks in advance.

**Comment by wsnyder** [comment]
Try asking this on an OpanTitan forum.  Verilator converts the SystemVerilog to C++ code which might be able to communicate through user code to e.g. USB or any other physical interface, but any USB capabilities are unrelated to Verilator.
