### ISSUE TITLE
Don't hide important build error messages

### ISSUE THREAD

**Issue by mcandre** [verilator/verilator#3164]
Fill up your disk so that you only have very little space remaining. Then perform the usual `make` command to attempt to build verilator from source.

The resulting error trace is generic. The user must manually cd into src/obj_dbg, and then run the g++... command. Only then are build errors displayed, about disk space issues. Would be helpful to make sure these messages are not dropped from verilator's make build system.

Example resolutions:

* Print low level build error messages directly to the console.
* Redirect low level build error messages to a consistent log file path, and show this file path to the user in the event of build failure.

What 'verilator --version' are you using?  Did you try it with the git master version?

git master

Would you be willing to try to fix Verilator yourself with assistance?

Not sure where the error obfuscating code rests.

**Comment by wsnyder** [comment]
What make does is outside our control, so I am not sure what precisely you are suggesting verilator do to help this?  Note making a log file will be even more confusing if there is no space to write to the log.
