### ISSUE TITLE
race issue when clock & data are changed from non-blocking assignment

### ISSUE THREAD

**Issue by EDAHUB** [verilator/verilator#3178]
I hit a race issue that a D flip flop which input data & clock are changing in the non-blocking assignment. The result in verilator is that output data changes in the same cycle as input data changes. Expect output data changes in the next cycle.

Create a t_race.pl in the following git branch. Could help check it?
 
https://github.com/shunyaocad/verilator.git , branch: edahub-dev

**Comment by wsnyder** [comment]
This will get fixed by #3278.
