### ISSUE TITLE
Standard class names are treated like keywords

### ISSUE THREAD

**Issue by quark17** [verilator/verilator#3206]
The parse/lex seems to treat some standard class names almost like keywords.  If my source file declares a signal named `process`:
```
module syntax_process (CLK, RST_N);
  input  CLK;
  input  RST_N;

  reg [7:0] process;

  always@(negedge CLK)
  begin
    if (RST_N != 1'b0) begin
      $display("%d", process);
      $finish(32'd0);
    end
  end
endmodule
```
it results in a syntax error:
```
%Error: syntax_process.v:5:13: syntax error, unexpected TYPE-IDENTIFIER
    5 |   reg [7:0] process;
      |             ^~~~~~~
```
I would guess that this is due to code in `V3ParseImp.cpp` (line 522), as the same error happens for signals named `mailbox` and `semaphore`.

The Questa simulator accepts (and simulates) this module.

**Comment by wsnyder** [comment]
mailbox, semaphore and process as you noted are defined in IEEE std::.  It should be possible to override these, but this is a fundamental weakness in the parser related to the same issue discussed in #2485.
