### ISSUE TITLE
$random doesn't update seed

### ISSUE THREAD

**Issue by quark17** [verilator/verilator#3238]
I don't know if `$random` is a priority, since I don't believe it's in SV?  But I noticed that this example ([random_seed.tar.gz](https://github.com/verilator/verilator/files/7690520/random_seed.tar.gz)):
```
for(i=0; i<5; i=i+1) begin
  val = $random(seed);
  $display ("seed=%h, val=%h", seed, val);
end
```
gives the following output for Icarus and QuestaSim:
```
seed=0011ea9e, val=8011ec00
seed=e1e0e687, val=61e0e9c3
seed=3354751c, val=b3547666
seed=d9b0336d, val=59b035b3
seed=7822b74a, val=f822b8f0
```
indicating that the seed is being updated on each call.  For Verilator, the seed is not changed and so `$random` returns the same value on every call:
```
seed=00000011, val=ffffffdc
seed=00000011, val=ffffffdc
seed=00000011, val=ffffffdc
seed=00000011, val=ffffffdc
seed=00000011, val=ffffffdc
```
The IEEE 1364-2005 spec doesn't seem to clarify how the seed is used.  So I'd guess that either of these interpretations is possible?

**Comment by wsnyder** [comment]
See IEEE-2017 20.15.1.   I had thought Verilator followed the rules, but IEEE does say the seed argument must be updated which is what Verilator is missing.

Perhaps you'd be willing to make a pull request?
