### ISSUE TITLE
can't link additional library - how to add additional libs?

### ISSUE THREAD

**Issue by mzau** [verilator/verilator#3239]
I do not know how to link an additional library.

Using systemc with verilator 4.212  on linux ubuntu 18.04.
`export LDFLAGS='-L<additional-library-path> -l<additional-lib>' `
verilator will use that, but the generated g++ link phase
will add the `<additional-lib>` *before* the object modules, like
`-l<additional-lib> mod1.o mod2.o -lsystemc`
which will not satisfy the linker. 
`mod1.o mod2.o -lsystemc -l<additional-lib> `
is working.

I've build verilator from the github master and could be able to patch sources if suggested.

The fix should also cover cmake.

**Comment by wsnyder** [comment]
Pass to Verilator rather than using the environment

     -LDFLAGS "-ladditional_lib"
