### ISSUE TITLE
macOS simulation build errors due to recent type changes

### ISSUE THREAD

**Issue by XarkLabs** [verilator/verilator#3257]
Hello.  Using the verilator "nightly" build package from https://github.com/YosysHQ/oss-cad-suite-build I have noticed a very recent regression in my Verilator simulation project when building under macOS (my project https://github.com/XarkLabs/Xosera/tree/master - "`make vrun`").  It has been building fine for a while, and still builds fine under Linux-x64, so I suspect a recent type change vs macOS or clang (same error below on both M1 or x64 macOS, running x64 verilator executable [but I believe native C++ sim build]).  Perhaps https://github.com/verilator/verilator/issues/3254 or maybe https://github.com/verilator/verilator/issues/3255 ?

Working verilator version:
  `Verilator 4.216 2021-12-05 rev v4.216-7-g8696e38e (mod)`
  (as packaged for macOS in https://github.com/YosysHQ/oss-cad-suite-build/releases/tag/2021-12-20)

Failing verilator version:
  `Verilator 4.216 2021-12-05 rev v4.216-32-gfd45be3d (mod)`
  (as packaged for macOS in https://github.com/YosysHQ/oss-cad-suite-build/releases/tag/2021-12-24)

Example of errors produced on failing version:
```
/Users/XarkLabs/Dev/oss-cad-suite/share/verilator/include/verilated.cpp:280:59: error: format specifies type 'unsigned long' but the argument has type 'vluint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
    VL_PRINTF("-V{t%u,%" VL_PRI64 "u}%s", VL_THREAD_ID(), _vl_dbg_sequence_number(), out.c_str());
                      ~~~~~~~~~~~~~~                      ^~~~~~~~~~~~~~~~~~~~~~~~~
                      %llu
/Users/XarkLabs/Dev/oss-cad-suite/share/verilator/include/verilated.cpp:878:29: error: format specifies type 'long' but the argument has type 'vlsint64_t' (aka 'long long') [-Werror,-Wformat]
                            static_cast<vlsint64_t>(VL_EXTENDS_QQ(lbits, lbits, ld)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/XarkLabs/Dev/oss-cad-suite/share/verilator/include/verilated.cpp:907:95: error: format specifies type 'unsigned long' but the argument has type 'QData' (aka 'unsigned long long') [-Werror,-Wformat]
                            = VL_SNPRINTF(t_tmp, VL_VALUE_STRING_MAX_WIDTH, "%" VL_PRI64 "u", ld);
                                                                             ~~~~~~~~~~~~~~   ^~
                                                                             %llu
/Users/XarkLabs/Dev/oss-cad-suite/share/verilator/include/verilated.cpp:1183:60: error: format specifies type 'long *' but the argument has type 'vlsint64_t *' (aka 'long long *') [-Werror,-Wformat]
                    std::sscanf(t_tmp, "%30" VL_PRI64 "d", &ld);
                                        ~~~~~~~~~~~~~~~~   ^~~
                                        %30lld
```

**Comment by wsnyder** [comment]
Certainly related to #3254 fixes.

I stomped out the VL_PRI64 macro to use the C++11 ones. Please see if the git master builds correctly.
