### ISSUE TITLE
Clock scheduling issue in a clock gating cell

### ISSUE THREAD

**Issue by agrobman** [verilator/verilator#3269]
Hi,

I got clock scheduling issue in one of our designs.

We have the clock gating cell RTL as:

```
module CGC;
  (
   input logic SE, EN, CK,
   output Q
   );
   logic  en_ff /*verilator clock_enable*/; **<<<< had to add this "comment" to make it work**
   logic  enable;
  
   assign      enable = EN | SE;
   always_latch begin
      if(!CK)
        en_ff = enable;
   end

   assign Q = CK & en_ff;
 
endmodule

```
the cell controls clock for D flip-flop registers with enable input.

I've found that such register with the CGC latches wrong value.

if I replace the en_ff latch by falling edge flop - everything simulates fine. 
Not all such flop registers in our design fail, but just some.
I've found workaround with  the /*verilator clock_enable*/ comment, but wondering why the tool propagates/recognizes gated clock correctly from FF as enable and not from the latch (although it recognizes the construct as a latch).

Is there way to improve the clock recognition  algorithm, including latched enables too?

(it is really confusing and time consuming to find such problems in some cases and not in other)

**Comment by wsnyder** [comment]
I and probably nearly everyone using it agree this is something needing improvement, unfortunately like many things it's a large project no one has yet undertaken.

Fortunately it looks like you have a good proper methodology where the clock gater cell is in a common module, so at least the changes can be easily implemented.
