### ISSUE TITLE
Hover object not found

### ISSUE THREAD

**Issue by HuanghualiWood** [verilator/verilator#3282]
When I use vscode , verilator always cannot find `include xxx.v in the same directory.Can give me a friendly tools which enables to recongize all include files

**Comment by wsnyder** [comment]
Verilator by default will find includes in the current directory.  Presumably then, this is a problem in vscode, not verilator.

If you think it is a verilator problem, please provide a verilator linux command line to reproduce the problem (i.e. completely outside VS), and I'll reopen this issue.

**Comment by HuanghualiWood** [comment]
thanks. Later ,I try a new idle
