### ISSUE TITLE
Removing LifePost optimization yields t_if_deep failure

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#3286]
The `VarVertexType::PRE` vertex carries an ordering constraint that is only an optimization, and ignoring it should still yield correct behaviour. Disabling this constraint in V3Order (by removing the edges to/from the `VarVertexType::PRE` vertices) however makes the t_if_deep test fail.

**Comment by wsnyder** [comment]
Just "-Ot" which disables LifePost shows this too, so likely a separate problem. I'll get back to this.

**Comment by wsnyder** [comment]
Nicely done, appreciate your cleaning this up.

**Comment by gezalore** [comment]
Causes issues with #3278 where LifePost is still disabled, so not entirely altruistic, but glad it's one more down.
