### ISSUE TITLE
Missing vector annotation in FST dumping

### ISSUE THREAD

**Issue by jamieiles** [verilator/verilator#3296]
Verilator currently names FST signals by the node name and if the signal is an array, appending the index number in square brackets.  This works fine, but unlike VCD, it means that a signal defined as say:

  logic [31:2] addr;

ends up in the FST as a [29:0] instead and it is not possible to use GTKWave's range fill to pad the LSB's with 0's making it necessary to calculate the byte address.  Ideally we should include the full vector definition at least when the LSB index is non-zero to support this.

**Comment by wsnyder** [comment]
Thanks for making the patches.
