### ISSUE TITLE
unpacked array with packed part >64bits cannot compile

### ISSUE THREAD

**Issue by mytbk** [verilator/verilator#3312]
This looks like the #2774 issue, because it is also related to handling the stringification of packed arrays according to the compiler error message. In the following example, the code generated by the third unpacked array cannot compile.

```
class MyClass;
	bit [63:0] a[2]; // ok
	bit [31:0][1:0] b[2]; // ok
	bit [64:0] c[2]; // error
endclass
```

Verilator version: Verilator 4.219 devel rev v4.216-110-gdecfa6bd

**Comment by wsnyder** [comment]
Should be good with this commit, thanks for making the test case small.
