### ISSUE TITLE
Escape error in Windows path

### ISSUE THREAD

**Issue by jijingg** [verilator/verilator#3318]
`$readmemb( d:\windowspath) ` with windows absolute path will failed!

> Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)

```
%Error: D:/nutstore/Gitlab/proj/macLab/tmp/job_1/C7_WBFFT2048_8L8D.v:17975:15: Unknown escape sequence: \G
17975 |     $readmemb("D:\nutstore\Gitlab\proj\macLab\C7_WBFFT2048_8L8D.v_toplevel_mem.bin",mem);
```
> What 'verilator --version' are you using?  Did you try it with the git master version?

Verilator 4.218 2022-01-17 rev UNKNOWN.REV

> What OS and distribution are you using?

Windows

> May we assist you in trying to fix this in Verilator yourself?

**Comment by wsnyder** [comment]
Backslashesin SystemVerog indicate the next character is a control escape.  So you need to double each backslash to have a correct program.
