### ISSUE TITLE
Support replication of the form: reg [WIDTH -1: 0] count = {WIDTH{1'b0}}

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#3335]
```reg [WIDTH -1: 0] count = {WIDTH{1'b0}}``` currently causes this error:
```
%Error-UNSUPPORTED: xx.v:61:18: Unsupported: Replication to form 'logic$[2:0]' data type
```

verilator-4.218

**Comment by ldoolitt** [comment]
I do this "all the time", and it works when WIDTH is a parameter (or parameter expression).
Can you post a fuller example?

**Comment by yurivict** [comment]
Sorry, this suggestion is based on confusion.
