### ISSUE TITLE
Wish for preprocessor determination of pre- vs. post-v4.210 model interface

### ISSUE THREAD

**Issue by ldoolitt** [verilator/verilator#3343]
I've read the nice section in connecting.rst titled "Model interface changes in version 4.210".
I hit that problem with some legacy code, and was able to easily port it to the post-v4.210 world.  But..

Stale software is real.  Specifically, Debian Bullseye is likely to be out there in widespread use for at least another two years, and it "only" ships v4.038.
How can I write user-level code that works with both APIs?  If there were a preprocessor flag, I'm quite capable
of writing the appropriate `#ifdef`s.  Most notably something like
```
#ifdef POST210
#define INTERNAL(m) (m)->rootp
#else
#define INTERNAL(m) (m)
#endif
```
along with the extra `#include`. [Suggestions for better names are welcome.]

Without something supplied by the Verilator header files, I'm forced to do some crude version detect at the Makefile level (and conditionally add `-DPOST210` there), which is often ugly and/or unreliable.  My Makefiles are already almost unreadable -- I don't want them to end up looking like a configure script.  The `VERILATOR_VERSION` string in verilated_config.h is useless for this purpose.

I looked for such a flag in the existing code base, but came up empty handed.  Did I miss something?

**Comment by wsnyder** [comment]
Good point.  No need to convince me ;), I just hadn't thought of needing the ifdef version until now.

In 4.219 I've introduced VERILATOR_VERSION_INTEGER, so we can use that going forward.  It looks like VL_CELL is the only define changed (deleted) in 4.210, so you can use that.   (To distinguish other versions before 4.219, do a diff and look for any defines that are different between versions.)

```
#if (defined(VERILATOR_VERSION_INTEGER) && VERILATOR_VERSION_INTEGER > 4210000) || !defined(VL_CELL)
# error "4.210 or later"
#else
# error "before 4.210"
#endif
```
