### ISSUE TITLE
Does  verilator support metastability?

### ISSUE THREAD

**Issue by rdkandroid** [verilator/verilator#3355]
Hi, In this code snippet, can verilator simulate signal z at a metastable state? Thank you for your comments.

module glitchEx(
input wire in0, in1, sel,
output wire out
);

wire not_sel;
wire and_out1, and_out2;

assign not_sel = ~sel;
assign and_out1 = not_sel & in0;
assign and_out2 = sel & in1;

// Buggy line of code:
assign out = and_out1 | and_out2; // glitch in signal z

endmodule

**Comment by wsnyder** [comment]
No, Verilator is a two-state simulator, and even a normal simulator won't detect these issues, you need a CDC analysis tool.

Verilator does have a CDC feature that was experimental however it wasn't built to detect this sort of issue.
