### ISSUE TITLE
printing with %d unsigned variables

### ISSUE THREAD

**Issue by agrobman** [verilator/verilator#3361]
I got different number representation in verilator vs xrun.

xrun :

`      2098 :       #6 0 000000008010000c ff828293  x5=0000000080001000 ; addi    x5,x5,18446744073709551608
`
verilator:

`     2098 :       #6 0 000000008010000c ff828293  x5=0000000080001000 ; addi    x5,x5,-8
`

the code:

```
function string dasm32_ai( input[31:0] opcode);
bit[`RV_XLEN-1:0] imm;
string mn;
    imm=0;
    imm[11:0] = opcode[31:20];
    if(opcode[31]) imm[`RV_XLEN-1:12] = '1;
    case(opcode[14:12])
    0: mn = "addi    ";
    2: mn = "slti    ";
    3: mn = "sltiu   ";
    4: mn = "xori    ";
    6: if(opcode[11:7] != 0) mn = "ori     ";
       else return dasm32prefetch(opcode); 
    7: mn = "andi    "; 
    default: return dasm32_si(opcode);
    endcase

    return $sformatf("%s%s,%s,%0d", mn, abi_reg[opcode[11:7]], abi_reg[opcode[19:15]], imm);
endfunction
```

since imm is defined as unsigned  variable, %d format should not print it as negative number ...

I'm using verilator 4.210

**Comment by wsnyder** [comment]
I think this is already fixed in the version in git master, closing assuming so.  Your example didn't work standalone so it's also possible I botched it, if so please attach an example that shows the example standalone and reopen, thanks.
