### ISSUE TITLE
CMake: Linker flags are lost when the verilated project is not the top-level executable

### ISSUE THREAD

**Issue by mastadle** [verilator/verilator#3377]
This issue occurs only when threading is used and you have another level of targets after the target which has the verilator output associated with it.

Example:
```cmake
add_library(veri_lib some_source.cpp)

find_package(verilator HINTS $ENV{VERILATOR_ROOT})
verilate(veri_lib top_hdl.v THREADS 2)

add_executable(self_tests self_test.cpp)
target_link_libraries(self_tests PUBLIC veri_lib)

add_executable(manual_tests manual_test.cpp)
target_link_libraries(manual_tests PUBLIC veri_lib)
```

The generator expression in [verilator-config.cmake.in:337](https://github.com/verilator/verilator/blob/master/verilator-config.cmake.in#L337) won't apply anymore and both executables are missing the thread and atomic library.

I added 2 executables just to illustrate a reasonable application. You save build time this way (files in `veri_lib` are only compiled once) without having to use ccache.

I'll create a pull request which fixes this issue.

**Comment by wsnyder** [comment]
Thanks, can you please make this as a pull request filed here?  Then ask @corco or maybe @patstew to review as they are knowledgeable in that code.
