### ISSUE TITLE
nulll pointer access on debugi larger than 8

### ISSUE THREAD

**Issue by HungMingWu** [verilator/verilator#3380]
> Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)
Run `examples/make_tracing_c`,  enable `--debugi 9`
> The null pointer access happened
> What 'verilator --version' are you using?  Did you try it with the git master version?
Verilator 4.221 devel rev v4.220-21-g5f333be9

**Comment by wsnyder** [comment]
Thanks for the fix.
