### ISSUE TITLE
Version 5 now part of master

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#3383]
I've created the develop-v5 branch.  This will collect changes towards v5.002.

This contains several major features including:
* timed coroutines (#3363)
* improved scheduling ~(#3329)~ (#3384)

Please consider using this branch to perform beta testing.

We are aiming for releasing to master branch in October 2022.

[This comment is periodically edited to summarize current state so you do not need to read later comments.]

**Comment by wsnyder** [comment]
@gezalore has merged the first large improvement which has a compliant scheduler #3329 no more misgenerated clocks!

We'd appreciate beta testers; please try the develop-v5 branch, and if you have issues file github issues as usual.  Thanks.

**Comment by gezalore** [comment]
@dpetrisko might be interested?

**Comment by Alex-Mann** [comment]
Just a note that these lines are essentially the same in `develop-v5` branch:
https://github.com/verilator/verilator/blob/develop-v5/bin/verilator#L344
https://github.com/verilator/verilator/blob/develop-v5/bin/verilator#L347

**Comment by wsnyder** [comment]
@Alex-Mann thanks I fixed the --main.

**Comment by wsnyder** [comment]
@gezalore yesterday merged develop-v5 branch into master!   Feedback is welcome to prepare this to become the next stable release.
