### ISSUE TITLE
Can we add VM_PREFIX as a default define in "verilated.mk" ?

### ISSUE THREAD

**Issue by fredrequin** [verilator/verilator#3402]
Hello,
in order to have a generic main.cpp, it would be nice to add -DVM_PREFIX=$(VM_PREFIX) in the C Preprocessor flags (VK_CPPFLAGS_ALWAYS).
Then, we can have a generic include in the main.cpp :

```
// Macros to build include file name
#define _quoted_string(x) #x
#define _symbols_header(x) _quoted_string(x##__Syms.h)
#define symbols_header(x) _symbols_header(x)
// Top level
#include symbols_header(VM_PREFIX)
```

Top level instantiation code is always the same code:
```
VM_PREFIX *top = new VM_PREFIX ;
```

Opening a VCD trace is becoming:
```
sprintf(fname, _quoted_string(VM_PREFIX) "_%04d.vcd", trc_idx++);
trc->open(fname);
```

What do you think ?

Regards,
Frédéric Requin

**Comment by wsnyder** [comment]
I need to think about this.
* This does match what the tests do
* Verilator supports multiple verilated models in the same main, think this might confuse people and the define would conflict.
* While on one level it makes it more general, it is another abstraction that the user needs to understand to learn what is going on.
* In version 5, it'll be more likely that main is generated for most users automatically, so will be moot.

**Comment by gezalore** [comment]
In either case ideally we will not want extra defines passed to the runtime library (`verilated*.cpp`), for testing speed.

**Comment by wsnyder** [comment]
As above, for now I think we don't want to do this, but thanks for the discussion.
