### ISSUE TITLE
Release plan for 4.221

### ISSUE THREAD

**Issue by mikeurbach** [verilator/verilator#3404]
Hi there, long time listener, first time caller.

Is there a plan to release 4.221? I have been testing the latest master, and there are a couple fixes since the last release that my team is eagerly awaiting:

https://github.com/verilator/verilator/commit/7bfc1a00a723cd91d8d52c146b5e7b45844a2ed6
https://github.com/verilator/verilator/commit/a6d678d41d3fce53ff7b7d8ccd59a86a0c630a00

We can keep using master, but in order to fully incorporate the changes across our organization, we'll really need to install the next release. Is there a timeframe for that? If I can help in any way, I would be happy to.

**Comment by wsnyder** [comment]
Usually there's a release every month or so, and it's been more than a month so this was a good poke!  Released.

**Comment by wsnyder** [comment]
BTW odd versions are development only, so 4.222 is what you want.

**Comment by mikeurbach** [comment]
Awesome, thanks! And makes sense, I'll be using 4.222.
