### ISSUE TITLE
SystemVerilog size (tick) operator with expressions

### ISSUE THREAD

**Issue by Blutyek** [verilator/verilator#3417]
In SystemVerilog the tick operator can be used to change the width of an expression:

&lt;const&gt;<b>'(</b> &lt;expression&gt; <b>)</b>

where &lt;expression&gt; will be extended/cropped to &lt;const&gt; bits width; if it was a signed expression and &lt;const&gt; is larger that its natural width, then signum extension will be performed. Now consider this example:

`module test ( input [5:0] b1, input [5:0] b2, output [9:0] a1, output [9:0] a2 );`
`assign a1 = 10'( b1 );       // Verilator is happy`
`assign a2 = 10'( b2-b1 );  // Verilator spits the dummy`
`endmodule`

In the second assign case Verilator 4.210-19 emits a warning: "Operator SUB expects 10 bits on the LHS but LHS's VARREF b2 generates 6 bits."

I do believe that that is incorrect: the tick operator should be applied on the <i>result</i> of the SUB, which has the same width as its operands. It seems that instead of extending the 6 bits wide SUB result to 10 bits, Verilator expects the SUB to return a 10 bits wide result.

**Comment by wsnyder** [comment]
The cast does affect the operation width.  However it seems more logical that a size cast would force suppression of the WIDTH failure immediately below - the documentation even suggests this already.  So took this bug to instead have that as the request - and this is now fixed.
