### ISSUE TITLE
Q: Strange verilator behaviour when running from a script

### ISSUE THREAD

**Issue by jotego** [verilator/verilator#3443]
I normally run verilator and then execute the output file from a script. Today something really odd happened. When the sim is run within the script it finishes ahead of time, after a number of clock cycles. It looks like the module eval() function is exiting the program with an exit code of 141 (decimal).

But if I call the same executable from the bash shell directly, the simulation completes to the end and the exit code is zero.

I have tried dumping the environment variables and reading and exporting them from the shell before calling the verilator sim. That works ok too: the sim runs all the way to the end.

I do not see what is different for the simulation depending on whether it is called from the script or bash, as I have the same arguments and environment variables. But I get that exit code of 141 consistently.

Could you give me some hints to debug this? I don't know what to check next.

PS: I am running this on MacOS, in case it matters.

**Comment by gezalore** [comment]
I would proceed by running your whole script under a debugger (gdb/lldb), [following forks](https://sourceware.org/gdb/onlinedocs/gdb/Forks.html) to see where the crash/exit happens and track back from there.

**Comment by wsnyder** [comment]
Exit 141 = 128 (core dump) + 13 (sigpipe).  Sig pipe means you did something that no longer needs input e.g.

     verilator ... | head 

so verilator terminates once head has enough lines.  Instead send to temp file and head that.

**Comment by jotego** [comment]
Thanks a lot for the hints! :-D
