### ISSUE TITLE
What can I do if I want to add a dependency static lib into verilator

### ISSUE THREAD

**Issue by specialpointcentral** [verilator/verilator#3447]
Recently, I want to add my static lib into verilator. So I use `<file.a>` to add into verilator args. It works.
But what confused me is verilator self-generate makefile did not give this lib's dependency rules.
So if I modify my lib files and compile them to `file.a`, verilator thinks this lib is ok, and does not recompile the `VTop`.
What can I do to deal this problem.

Thanks.

**Comment by wsnyder** [comment]
You'll need to make your own makefile that has a dependency on the final executable, then includes the generated makefile, e.g.

```
include Vtop.mk
mylibrary.a: {.... whatever rules are needed}
Vtop: mylibrary.a
```

**Comment by specialpointcentral** [comment]
That works, Thank a lot.

> You'll need to make your own makefile that has a dependency on the final executable, then includes the generated makefile, e.g.
> 
> ```
> include Vtop.mk
> mylibrary.a: {.... whatever rules are needed}
> Vtop: mylibrary.a
> ```
