### ISSUE TITLE
V3Lexer_pregen.yy.cpp:8665:18: error: out-of-line definition of 'LexerInput' does not match any declaration in 'V3LexerBase'out-of-line definition of 'LexerInput'

### ISSUE THREAD

**Issue by ymei** [verilator/verilator#3487]
I am trying to compile verilator on macOS 12.4  Dependencies are installed through macports

```
$ /opt/local/bin/flex --version 
flex 2.6.4
$ /opt/local/bin/bison --version 
bison (GNU Bison) 3.8.2
```
The compilation fails with the following message:
```
In file included from ../V3ParseLex.cpp:28:
V3Lexer_pregen.yy.cpp:8665:18: error: out-of-line definition of 'LexerInput' does not match any declaration in 'V3LexerBase'
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
                 ^~~~~~~~~~
V3Lexer_pregen.yy.cpp:8694:19: error: out-of-line definition of 'LexerOutput' does not match any declaration in 'V3LexerBase'
void yyFlexLexer::LexerOutput( const char* buf, int size )
                  ^~~~~~~~~~~
```

I think this is a flex/bison issue but I'm not sure what went wrong.  Please help.

**Comment by wsnyder** [comment]
Yes, this is another MacOS issue with bison/flex, searching on the error shows this discussion:

https://github.com/jonathan-beard/simple_wc_example/issues/7

closing as not a Verilator issue but feel free to follow up to help out anyone else that gets this.

**Comment by ymei** [comment]
I figured it out.  In my particular case (using macports, which installs everything under `/opt/local`, the following command should be used to configure:

`CPPFLAGS="-I/opt/local/include" ./configure`

Then everything compiles.
