### ISSUE TITLE
$display lost if part of always table

### ISSUE THREAD

**Issue by sbmpost** [verilator/verilator#3488]
On OSX 12.3.1 (Monterey), I am using the latest stable verilator 4.224.
I am writing a simple state machine:

    module statemachine(input CLK);

    reg[2:0] state = 3'b0;
    parameter state_1 = 3'b000;
    parameter state_2 = 3'b001;
    parameter state_3 = 3'b010;
    parameter state_4 = 3'b011;
    parameter state_5 = 3'b100;
    parameter state_6 = 3'b101;

    always @(posedge CLK) begin
        $display("I was here");
        case (state)
            state_1: state <= state_2;
            state_2: state <= state_3;
            state_3: state <= state_4;
            state_4: state <= state_5;
            state_5: state <= state_6;
            state_6: state <= state_1;
            default: state <= state_1;
        endcase
    end

    endmodule

Each time CLK goes high, I would expect "I was here" to be printed.
This however is not the case. To see output, I can either comment
out the last 3 states like so:

        // state_4: state <= state_5;
        // state_5: state <= state_6;
        // state_6: state <= state_1;

Or I can introduce the $time variable like so:

    $display("I was here", $time);

**Comment by wsnyder** [comment]
Verilator optimizes some case statements into lookup tables. the standalone display incorrectly got converted, $time correctly disabled this optimization.
