### ISSUE TITLE
Race condition in `VL_ASSIGN_WSB`/`VL_ASSIGN_SBW` methods

### ISSUE THREAD

**Issue by nandor** [verilator/verilator#3494]
Multi-threaded System-C models compiled with verilator 4.224 crash due to a race condition originating from System-C.

The helper methods assigning to `sc_biguint` ports create temporary values on the stack for `VlWide` conversion. The `_butemp`/`sc_unsigned_subref` structures used by System-C to represent bit ranges are allocated on the stack through a `sc_vpool` memory pool which is not thread safe (and generally unsafe as it can only allocate a finite number of ranges before wrapping around).

The assignment methods should perform the operation without such temporaries.

- https://github.com/verilator/verilator/blob/master/include/verilated_funcs.h#L519
- https://github.com/accellera-official/systemc/blob/master/src/sysc/utils/sc_temporary.h

**Comment by wsnyder** [comment]
Wow, that must have been nasty to find, thanks for debugging!

Perhaps you could propose a pull request to fix this and test it?  You should be able to load into a thread local temporary then use an appropriate VL_ASSIGN_SEL to do the insert.
