### ISSUE TITLE
How to restore the thread pool for multi-threaded tracing

### ISSUE THREAD

**Issue by poemonsense** [verilator/verilator#3503]
How may we help - what is your question?

I saw #3449 adding multi-threading support for vcd tracing. However, I cannot figure a way to restore the thread pool for the tracing context after the pool was destroyed.

Previously we are implementing a snapshot mechanism, which restores the snapshotted verilated model after the simulation aborts. We manually create the thread pool for the child process (the snapshot one). However, when we try to update verilator to the most recent version on the master branch, it seems this thread pool does not work. Could you help us figure out what's wrong with the thread pool?

The code is here: https://github.com/OpenXiangShan/difftest/blob/master/src/test/csrc/verilator/emu.cpp#L738-L744

For verilator v4.225, we change it to `dut_ptr->vlSymsp->__Vm_threadPoolp = new VlThreadPool(dut_ptr->contextp(), EMU_THREAD);` (or should it be `EMU_THREAD - 1`?). However, it does not seem to work. After the restored model starts, there's only one thread working and after a second it stops as well. It seems like the tracing threads does not get any working thread.

I guess it is due to the initialization of the traceVcd with the thread pool. However, the vcd class is created after we initialize the thread pool. Could you please give us a hint on how to correctly initialize the thread pool for tracing?

**Comment by poemonsense** [comment]
I noticed the commit you mentioned and had looked at the related files. But I cannot figure out a way to let the tracing threads work after I tried some workaround.

We are using the unstable internal APIs and have experienced the forward compatibility issues (the last time was the v4.210 which moved `__Vm_threadPoolp ` under `vlSymsp`). The generated `const` is removed manually by us (see https://github.com/OpenXiangShan/difftest/blob/master/verilator.mk#L126-L128), so we can do that before the latest version.

We want this because we implement a snapshot mechanism using `fork`, whose works quite like the checkpoints save/restore provided by Verilator. We fork the simulation process periodically and wake up one of the child when the simulation aborts - in this way we are able to re-start the simulation for the last N seconds (given N is the snapshot interval) and dump waveform for this short interval only.

I was just wondering why the Vcd cannot see the ThreadPool we create for the second again when the child wakes up. As in the code, we create the thread pool earlier than creating the VcdC. Shouldn't the created VcdC gets the thread pool from the context? I saw from the source code that VcdC instantiates the buffer with the thread pool when they are created. Or are we using the thread pool incorrectly? In the previous version of Verilator, we just re-create the thread pool and the simulation works well. I don't really know whether it is due to the multi-threaded tracing or the API change of ThreadPool.

**Comment by poemonsense** [comment]
BTW, I think it is a good idea for Verilator to provide this periodical in-memory checkpoint mechanism to the users. It is much helpful for the debugging. Running simulation with waveform is too slow and causes a waster of I/O bandwidth and disk storage. Most debugging cases require only the last N seconds. Probably I think Verilator may provide a stable API to re-construct the simulation when being forked.

**Comment by gezalore** [comment]
> I was just wondering why the Vcd cannot see the ThreadPool we create for the second again when the child wakes up. As in the code, we create the thread pool earlier than creating the VcdC. Shouldn't the created VcdC gets the thread pool from the context?

Which version are we talking about now? on master it should pick it up from the context:
https://github.com/verilator/verilator/blob/af70db88db4773f953e23f4aaab745b25e4ed7f0/include/verilated_trace_imp.h#L495

On the first version of the parallel tracing (which is in 4.224), it used to hold on to the thread pool directly, because the thread pool was not under the context yet:

https://github.com/verilator/verilator/blob/7c79f0d431ab5da8412c8ce6796f0bbb1c7fa2b5/include/verilated_trace.h#L197

**Comment by poemonsense** [comment]
> > I was just wondering why the Vcd cannot see the ThreadPool we create for the second again when the child wakes up. As in the code, we create the thread pool earlier than creating the VcdC. Shouldn't the created VcdC gets the thread pool from the context?
> 
> Which version are we talking about now? on master it should pick it up from the context:

I'm using the master branch. Did not try the first version of paralle tracing.

**Comment by poemonsense** [comment]
Let me have a try with different versions of verilator. Will give more details with examples later. I think probably I'm creating the thread pool incorrectly? Instead of the issues of parallel tracing?

**Comment by gezalore** [comment]
On master, the thread pool is owned by the context, but there are pointers in the generated models (and maybe in other places) that point to it as well to avoid multiple indirection in hot code. You would need to update all of them before this has a chance of working, but there might be other issues as well.

**Comment by wsnyder** [comment]
>BTW, I think it is a good idea for Verilator to provide this periodical in-memory checkpoint mechanism to the users

@poemonsense, it sounds like you are asking for save/restore.  Verilator already supports save/restore.  E.g. save every 10 minutes, and you can restore to any of the save's.  There are some restrictions currently but hopefully it works for your case.

**Comment by poemonsense** [comment]
> >BTW, I think it is a good idea for Verilator to provide this periodical in-memory checkpoint mechanism to the users
> 
> 
> 
> @poemonsense, it sounds like you are asking for save/restore.  Verilator already supports save/restore.  E.g. save every 10 minutes, and you can restore to any of the save's.  There are some restrictions currently but hopefully it works for your case.

Yes. It works the same as the save/restore provided by verilator. We have used this --savable option in our project to do checkpoints. It's quite useful. 

Further, it's better if we can have an in-memory API to save/restore the simulation with in-memory data structures. And based on the in-memory data, we should be able to re-launch the simulation (and probably want an API to re-create the Thread Pool?)

**Comment by poemonsense** [comment]
After carefully looking into the source code, I just find the correct but dirty way of doing this at https://github.com/poemonsense/verilator/commit/15c799add16566d2958cd6aa77e6aab3e730ef9e.

Because of the `unique_ptr`, we have to explicitly release it instead of re-assigning the variable. Otherwise, the destructors would be called by the child process and make the system hang because the child process doesn't have these threads.

Let me explain the use case. On Linux platforms, we have `fork` to duplicate the process with copy-on-write supported by the OS. This is a lightweight approach to snapshot the process, including the verilator simulation binary. Therefore, with fork, we could produce a lot of in-memory simulation snapshots with `fork`. This is a better, much more efficient replacement for the verilator save/restore because it does not need full disk/memory IO for the simulation.

However, the issue with `fork` is multithreading. It's hard to use multithreading with fork because fork does not duplicate the threads. After calling fork, the child process don't have any threads inherited. They need to create their own thread pool for simulation. That's why we have to manually create the thread pool like this:

```
#if defined(VERILATOR_5_000)
  // Verilator 5.0 uses multi-threading even for single-threaded models.
  dut_ptr->vlSymsp->__Vm_threadPoolp = (VlThreadPool *)dut_ptr->contextp()->resetThreadPoolp();
#elif EMU_THREAD > 1
#if defined(VERILATOR_4_210)
  dut_ptr->vlSymsp->__Vm_threadPoolp = new VlThreadPool(dut_ptr->contextp(), EMU_THREAD - 1, 0);
#else
  dut_ptr->__Vm_threadPoolp = new VlThreadPool(dut_ptr->contextp(), EMU_THREAD - 1, 0);
#endif
#endif
```

Actually this semantic is simply `called_at_fork`. However, C++ std::thread does not support this type of callback because it's cross-platform and knows nothing about fork. Also, Linux pthread only supports C function pointers and cannot capture the context `this` via lambda functions.

@wsnyder @gezalore  I'm also wondering whether it is possible for verilator to support officially the fork style snapshots on the Linux platform. It would greatly benefit the community by providing an elegant and highly efficient way of snapshotting the simulation. Debugging really needs this to avoid re-producing the simulation.

**Comment by poemonsense** [comment]
Yes we are able to re-run the snapshots to fast-forward near the end-of-simulation for dumping waveform only for the last seconds. This is mainly for fast simulation as well as debugging.

As far as I know, the forked snapshot cannot be saved to disk. If we want persistent snapshots, we have to let the fork snapshots  use Verilator save/restore for using disk IOs. I believe the verilator save/restore and fork snapshots are complementary to each other. They are their own advantages and use cases.

Thanks for your support on adding the API. I think an API called like `atClone` would be enough for the use to freely use fork in their user code, like `dut_ptr->atClone()`. Verilator would handle the `atClone`, such as resetting the thread pool. In this way, the user does not need to hack the verilator source code (currently we use sed to replace the generated verilated model source code) to access the private members. Also, adding the `atClone` API would not hurt verilator on the Windows/macOS platforms because the API's internal implementation does not rely on fork at all and handles only the model's internal states.

What's your opinion on this? I would like to help but we should probably figure out whether the thread pool is the only thing we need to restore at a (memory-copy, instead of circuit-copy) clone of the verilated model, which I'm not sure. From my experiences, resetting the thread pool is all I need.
