### ISSUE TITLE
What is the purpose of SYSTEMC_64BIT_PATCHES

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#3505]
Googling this defines returns 2 results, both from the Verilator source tree. I can't find any other references anywher, including in my distro SystemC installation. What is the purpose of this? Can it be removed (assume never defined)? 

https://github.com/verilator/verilator/blob/1d400dd98c21e9672fc17b43bdb49ef3b25721ad/include/verilated_fst_sc.h#L98

(there are a total of 4 uses, one in each of `verilated_{fst,vcd}_sc.{h,cpp}`)

**Comment by wsnyder** [comment]
That dates back to a very old SystemC which was 32-bits only.  Please feel free to make a push that removes them.
