### ISSUE TITLE
Verilator 5 – DPI export trigger never triggered in `nba`

### ISSUE THREAD

**Issue by kbieganski** [verilator/verilator#3508]
This concerns the `develop-v5` branch.

The DPI export trigger is used as an external domain for both `act` and `nba` ordering. The sentree used for both is `[true] __VactTriggered.at(<DPI trigger>)`:

https://github.com/verilator/verilator/blob/develop-v5/src/V3Sched.cpp#L1080-L1104

But I think it should be changed to `[true] __VnbaTriggered.at(<DPI trigger>)` for `nba` ordering.

See the `t_order_dpi_export_7.pl` test. We get this code:
```cpp
void Vt_order_dpi_export_7___024root___eval_nba(Vt_order_dpi_export_7___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    Vt_order_dpi_export_7__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vt_order_dpi_export_7___024root___eval_nba\n"); );
    // Body
    if (vlSelf->__VnbaTriggered.at(1U)) {
        Vt_order_dpi_export_7___024root___nba_sequent__TOP__0(vlSelf);
    }
    if (vlSelf->__VactTriggered.at(0U)) {
        Vt_order_dpi_export_7___024root___ico_sequent__TOP__0(vlSelf);
    }
}
```
The condition in the second `if` will never be true, as `__VactTriggered` should be all zeroes in `nba`.

**Comment by gezalore** [comment]
Thanks for catching this, you are of course right. I pushed a test that fails on this, and the fix.
