### ISSUE TITLE
Formatting in docs/guide/files.rst

### ISSUE THREAD

**Issue by dbear496** [verilator/verilator#3514]
In [docs/guide/files.rst](https://github.com/verilator/verilator/blob/e0b61ceabd76d2fd3aae0a1ff1bd522e307de409/docs/guide/files.rst), there seem to be some stray asterisks in the 'Files Read/Written' section, e.g. `{prefix}*___024root*{__n}.cpp` looks like it has some un-rendered markup. I suppose the asterisks could be wildcards, but there is no explanation of what they would mean. Also, `{prefix|_hierMkArgs.f` appears to have a pipe instead of a close brace.

Additionally, in my case I got an output file named `VMyModule___024root__DepSet_h59f7838a__9__Slow.cpp`, and I don't know what the `DepSet_h59f7838a` part means; if someone could explain that, then that would be great.

verilator --version: Verilator 4.220 2022-03-12 rev v4.220-23-ged979c6a (mod)
OS: Ubuntu 22.04

Thanks in advance.

**Comment by gezalore** [comment]
The `*` are wildcards as you suspect (to explain in docs). The DepSet hash depends on which headers the file includes. This is intended to help with incremental re-compilation of the output via ccache but is otherwise unimportant.

**Comment by dbear496** [comment]
Okay, thanks for clarifying the purpose of the DepSet hash and that the asterisks are meant to be there as wildcards. My question is answered, but I will just leave this issue open in case any of the other formatting still needs to be fixed. To clarify, here are the rows that I still think look suspicious:

| file | sus |
| --- | --- |
| *{prefix\|*_hierMkArgs.f | pipe instead of close brace |
| *{prefix}*___024root__Trace{__n}\*.cpp | {__n} is missing italics and asterisk may be extra |
| *{prefix}*___024root__Trace__Slow{__n}\*.cpp | {__n} is missing italics and asterisk may be extra |

If these are actually the way they are supposed to be, then feel free to close the issue.
