### ISSUE TITLE
Is there a way to convert V3Graph back to HDL or C++ code?

### ISSUE THREAD

**Issue by burntfalafel** [verilator/verilator#3526]
Currently the V3Trace block creates V3Graph edges, and optimises the graph. I was wondering is there any to make the graph spit back code? Even the generated C++ model will do.

All I can emit from the V3Graph block is the `*.dot` and `*.tree` files...

Thanks!

**Comment by wsnyder** [comment]
Not sure what you mean by code, what are you trying to do?

**Comment by burntfalafel** [comment]
The aim was to see the code output from the graph optimisation passes done in the V3Trace module. (here:) https://github.com/verilator/verilator/blob/f9f66d787e5b386c89cb9c9714bcf18a55c4090d/src/V3Trace.cpp#L729

**Reason?** Was trying to get the optimised HDL code (or optimised C++ code). 

At the moment I can only dump out the optimised graph in `*.dot` which only allows me to visualise the optmisation difference.

**Comment by burntfalafel** [comment]
Apologies, this question was vague. Got confused by the order of execution of cpp files in the project. Solved by increasing verbosity.
