### ISSUE TITLE
`t_flag_help` doesn't actually test all executables it tries to.

### ISSUE THREAD

**Issue by mglb** [verilator/verilator#3532]
The [`t_flag_help`](https://github.com/verilator/verilator/blob/master/test_regress/t/t_flag_help.pl) doesn't actually test all executables it tries to.
All test cases write to a file with the same name. However, the file contents read by  [`file_grep`](https://github.com/verilator/verilator/blob/master/test_regress/driver.pl#L2424) are [cached](https://github.com/verilator/verilator/blob/master/test_regress/driver.pl#L2463-L2474), so it always greps output of the first executable.
The grep actually fails for output of some tested executables. Due to this, the test fails when run in parallel execution mode (`make test_regress SCENARIOS='--vlt --dist' DRIVER_FLAGS="--j $(nproc) --quiet"` with `Parallel::Forker` installed).

Tested branch: master

The test fix is below. I didn't create PR because the fixed test fails and I'm not sure how you would like to handle it.

```diff
diff --git a/test_regress/t/t_flag_help.pl b/test_regress/t/t_flag_help.pl
index cb38bfb87..e65223006 100755
--- a/test_regress/t/t_flag_help.pl
+++ b/test_regress/t/t_flag_help.pl
@@ -12,18 +12,21 @@ scenarios(dist => 1);

 # See also t_flag_version.pl

+use File::Basename;
+
 sub check {
     my $interpreter = shift;
     my $prog = shift;
+    my $logfile = "$Self->{obj_dir}/t_help." . basename($prog) . ".log";

     run(fails => 0,
         cmd => [$interpreter, $prog, "--help"],
-        logfile => "$Self->{obj_dir}/t_help.log",
+        logfile => $logfile,
         tee => 0,
         verilator_run => 1,
         );

-    file_grep("$Self->{obj_dir}/t_help.log", qr/DISTRIBUTION/i);
+    file_grep($logfile, qr/DISTRIBUTION/i);
 }

 foreach my $prog (
```

**Comment by wsnyder** [comment]
Thanks for the report and fix - I committed along with what was needed to make the test pass.
