### ISSUE TITLE
dpi 64 bits

### ISSUE THREAD

**Issue by quantrpeter** [verilator/verilator#3534]
Hi, DPI seems don't have long (64 bits), how can we represent 64 bits? 

thanks
Peter

**Comment by gezalore** [comment]
It's called `longint`, but this is just basic SystemVerilog syntax. Please refer to the SystemVerilog standard, there are also example in the test suite, for example; 
https://github.com/verilator/verilator/blob/master/test_regress/t/t_dpi_arg_input_type.v

**Comment by quantrpeter** [comment]
thank you my hero
