### ISSUE TITLE
Segfault exporting non-existant package

### ISSUE THREAD

**Issue by 1425** [verilator/verilator#3535]
Running "verilator --cc 1.v" where 1.v contains "export i::n" produces a segfault.

This has been tested with versions:

Verilator 4.038 2020-07-11 rev v4.036-114-g0cd4a57ad
Verilator 4.225 devel rev v4.224-78-g122e89ffd (pulled from git master)

Tested on Ubuntu 22.04.1 LTS.

This issue goes away if the line:

if(!packagep) return;

Is added into the function "exportItem" in V3ParseSym.h.

However, I don't know if this is the preferred way to do this and something else should be done instead to prevent that function being called with a null pointer, and perhaps an assertion added in that function that the pointer is non-null.

**Comment by wsnyder** [comment]
Thanks, I added the "if" up one level higher.
