### ISSUE TITLE
BLKLOOPINIT related question (also discussed in old q/a post 1809)

### ISSUE THREAD

**Issue by plarusa** [verilator/verilator#3557]
BLKLOOPINIT is an error, which suggests the Verilator output is incorrect? Or can I safely disable the error and pay a performance penalty? I am converting a commercial design where Verilator aborts unless this error is disabled. Thanks for helping.

**Comment by wsnyder** [comment]
As described in the docs https://veripool.org/guide/latest/warnings.html#cmdoption-arg-BLKANDNBLK

it is generally safe to disable this.  Theoretically there can be simulation mismatches but that's very rare in normal code when this is used during e.g. reset.
