### ISSUE TITLE
print formatting of hex numbers, width does not match other simulators

### ISSUE THREAD

**Issue by jeras** [verilator/verilator#3565]
While formatting a hex print of a logic vector the width specifier is ignored.
My aim was to produce the same string width regardless of the logic vector width.
For a 32-bit vector the two formattings `%8h` and `%h` produce a string of the same width, 8 characters. 
For a 24-bit vector `%8h` should produce 8 characters and `%h` should produce 6 characters (24-bit/4-bit). 

I created a test on EDA playground to check how other simulators behave.
https://www.edaplayground.com/x/YevD

Verilator seems to ignore the string width specifier and always produces the a sting width aligned with the vector width.

I did check the standard, and I noticed it does not specify clearly what the extended bits should be.
Rivera Pro extends with spaces, while the big 3 extend with zeros regardless of the number sign.

I am using the latest Git main version of Verilator on Linux.

**Comment by wsnyder** [comment]
As you note this behavior is outside the standard. But, if you see some consensus among other tools Verilator certainly should align.

If you could please summarize the other simulator results here, and then provide a test case and fix as part of a pull request it would be appreciated.
