### ISSUE TITLE
rolloverMB() is in bytes not MB

### ISSUE THREAD

**Issue by forensicgarlic** [verilator/verilator#3570]
From reading through github issues these past weeks I became aware of rolloverMB() functionality for VCD traces, and it came up this week as a teammate had an error occur at the end of a long sim creating a giant trace file. However, in initial experiments trying to use rolloverMB(), it didn't actually appear that the size we passed in turned out VCD files sized to that many MB. What are the expected units we should be passing in?

**Comment by wsnyder** [comment]
Looking at the code I believe it is in bytes, not MB as name suggests, please try that.  It should always break files at timestamps, so files might be a bit larger than requested.

Note the first file is the header which must be cat with whatever chunk files are wanted.  (That is, you must keep file _cat0000, could delete 1..999, keep _cat0100. Then cat _cat0000 _cat0100 to get the vcd.
