### ISSUE TITLE
How to switch to clang to compile projects

### ISSUE THREAD

**Issue by MJChku** [verilator/verilator#3575]
After some search, I don't seem to understand how to use clang instead of gcc for compilation. 
For example, with the example project provided ( with `ccache` cleaned as `ccache -c` ):

`verilator --compiler clang  -Wall --cc --exe --build sim_main.cpp our.v` outputs:
`ccache g++  -I.  -MMD -I/usr/local/share/verilator/include -I/usr/local/share/verilator/include/vltstd  etc..  -std=gnu++14 -Os -c -o sim_main.o ../sim_main.cpp`

I also tried to append `CC=clang CXX=clang` before verilator, but doesn't change it to use clang.

**Comment by wsnyder** [comment]
Configure with clang

./configure CXX=clang++ 

Alternatively you can use --compiler but also when run make need CXX=clang++

**Comment by wsnyder** [comment]
Configure with clang

./configure CXX=clang++ 

Alternatively you can use --compiler but also when run make need CXX=clang++
