### ISSUE TITLE
v5-develop: automatic generation main.cc

### ISSUE THREAD

**Issue by mathieu-tp** [verilator/verilator#3577]
With v5-develop version, the C++ main program can be generated using the **--main**  option.

When traces are expected (using $--trace$) if suggest to automatically add the 
`Verilated::traceEverOn(true);
`
call in the generated main C++ file.

**Comment by wsnyder** [comment]
Makes sense. Might you be able to submit a pull request against Master to do this?

**Comment by kbieganski** [comment]
I had the same thought, actually: https://github.com/verilator/verilator/pull/3578
