### ISSUE TITLE
I found the out come of a signal is evaluated wrong in a comb logic. 

### ISSUE THREAD

**Issue by PeichenGuo** [verilator/verilator#3581]
When I am verificating dcache with my c-model, I found something went wrong.

I got a logic here:
```
assign refill_hsk = (wb_ack_i && ~cache_mem_is_write_q && burst_q);
```
And I display it at a posedge of clk:
```
always @(posedge clk) begin
    $display("refill_hsk:%x", refill_hsk);
    $display("wb_ack_i:%x", wb_ack_i);
    $display("cache_mem_is_write_q:%x", cache_mem_is_write_q);
    $display("burst_q:%x", burst_q); 
end
```
I found the output is wrong in the output:

================
refill_hsk:0
s2_valid:0
wb_ack_i:1
cache_mem_is_write_q:0
burst_q:1
data_in:00002b3c
-----------

The comb logic is prettt heavy, is that the problem? 
It works on vcs, but I am trying to use opensource simulator instead of the commercial one.

**Comment by wsnyder** [comment]
Nothing is obviously wrong in what you attached.

Can you please a complete, self-contained minimal runnable example?
