### ISSUE TITLE
Support modules in generate blocks in vpi_iterate

### ISSUE THREAD

**Issue by kaylikayli** [verilator/verilator#3609]
In vpi_iterate, there's no case for vpiInternalScope which I believe is the way we should be accessing scopes within a generate block. Currently, it's possible to get them by name, but within a module I want to be able to get a handle to the namespaces for generate blocks and use that again to get other attributes.

To adapt an example in t_vpi_var.v if we have
```   
module t ...;
   ...
   genvar i;
   generate begin : gen_loop
   for (i=1; i<=6; i=i+1) begin : arr
     arr #(.LENGTH(i)) arr();
   end
   end endgenerate

endmodule : t
```
According to my readings of 37.83 and 37.5 in IEEE1800, I believe it should work like the following in c++:
```
   gen_loop_h = vpi_iterate(vpiInternalScope, module_h);
   gen_loop_gen_arr_h = vpi_iterate(vpiInternalScope, gen_loop_h);
   gen_loop_gen_arr_0_h = vpi_handle_by_index(gen_loop_gen_arr_h, 0);
   gen_loop_gen_arr_0_arra_h = vpi_iterate(vpiInternalScope, gen_loop_gen_arr_0_h);
```

I think the solution here would be to have the generate block identifier be a scope that somehow keeps track of its child scopes, but I'm open to ideas on how to get this working.

**Comment by wsnyder** [comment]
Modules that are inlined create special V3Ast cells that eventually lead to VerilatedVpioScope structures in the runtime include library. Those (and VerilatedVpioModule etc) are then referenced by the VPI code to know what modules and cells etc exist.

The named begin blocks that are part of generates become AstBegin blocks that are flattened out.  We still want those to flatten for performance reasons. So these instead, when using vpi, need to result in handling similar to the Inline'ed modules, that is create Ast structures that get dumped for the runtime.

This will likely need a good deal of plumbming to get working.  The first step is to please get some good self-test test_regress tests that pass on several other simulators, you can make a pull request we can commit those (as failing), then move onto support as described above.

BTW if you can change your VPI code to special case Verilator's handling, while not compatible that is likely the fastest route to getting your model working (versus this support).
