### ISSUE TITLE
--language "VAMS" or 'begin_keywords

### ISSUE THREAD

**Issue by MartinSolk** [verilator/verilator#3648]
Hello,
i have a question to VAMS. I tried to use "--language VAMS" or in my code 'begin_keywords "VAMS" instead. Nothing of it working it gave me this error message.
![image](https://user-images.githubusercontent.com/79546385/193139827-2e251d27-2690-4aa3-9ae2-ade8c9b78493.png)
![image](https://user-images.githubusercontent.com/79546385/193139878-551b4d94-e958-439d-a9b6-4ef356f32249.png)
Do I need it if i want to use wreal or is nothing of VAMS supported anymore?
And my second question is if there is an support for  `wrealZState and  `wrealXState.
Greetings,
Martin

**Comment by wsnyder** [comment]
It's backtick begin_keywords that is

    `begin_keywords

**Comment by MartinSolk** [comment]
Thank you
