### ISSUE TITLE
VlClassRef should not accept assignment with integers

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#3663]
Discovered in #3661 that a variable of type `VlClassRef<T>` can be assigned directly with an integer literal: `VlClassRef<T> foo; foo = 0U;`. This can hide code generation issues so it would be best if this was not possible.

Partial fixes here:
https://github.com/gezalore/verilator/blob/46ed983cf1f29b62095aa95acc8e5dc82bd412e5/src/V3EmitCFunc.cpp#L562-L569
and here:
https://github.com/gezalore/verilator/blob/46ed983cf1f29b62095aa95acc8e5dc82bd412e5/include/verilated_types.h#L1148-L1153

Would @kbieganski be interested in making this proper?

**Comment by kbieganski** [comment]
Yes, I'll fix this.

**Comment by gezalore** [comment]
A more fundamental issue is that AstConst/V3Number does not have a concept that it represents a nullptr (or any hardcoded address) vs a zero (or a true integer).

**Comment by kbieganski** [comment]
What about `V3Number`'s `isNull()`? Not sure how it's used though.

**Comment by gezalore** [comment]
Hmm, missed that, might just be what we are looking for.
