### ISSUE TITLE
Naked begin/end block in module

### ISSUE THREAD

**Issue by mpb27** [verilator/verilator#3695]
Would it be possible to allow a `begin/end` block in a module? This is allowed in Vivado, Riviera Pro, Xcelium, and VCS. While Mentor Questa does not allow it.

```sv
module foo (input logic clk, input logic a, output logic b);

    begin : block_bar
        logic compute_bar;
        // ... do some sequential work here (eg. a must be high for N cycles before asserting bar) ...
        assign b = compute_bar;
    end
    
    // ... more work ...
    // compute_bar and any other block_bar variables are inaccessible here due to scope 😄 

endmodule
```

I'm new to SystemVerilog, so if someone more experienced knows of a construct that can be used to limit scope of varaibles inside a module, a helpful hint would be very much appreciated.

**Comment by wsnyder** [comment]
As far as I could tell this syntax isn't officially part of the IEEE grammar, but I suspect that is their mistake.  Anyhow fixed.
