### ISSUE TITLE
CI: Github actions show a lot of new deprectaion messages

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#3700]
There are several new deprecation notes that need to be addressed/updated in the CI configuration.

**Comment by wsnyder** [comment]
Harder part:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by wsnyder** [comment]
Remaining warnings need to wait for a new actions/download-artifact

**Comment by wsnyder** [comment]
Believe upstream issue fixed.
