### ISSUE TITLE
Coverage in if statement nest in case statement not counted

### ISSUE THREAD

**Issue by vanjoe** [verilator/verilator#3710]
Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)
[test.zip](https://github.com/verilator/verilator/files/9873863/test.zip)

What 'verilator --version' are you using?  Did you try it with the git master version?
Verilator 5.001 devel rev v4.228-118-g2a12b052f. No
What OS and distribution are you using?
Ubuntu 22.04

May we assist you in trying to fix this in Verilator yourself?
Perhaps

I'm noticing that the if statement inside of the case statements are not being counted correctly by coverage. I've attached a simple example that shows this. simply run build.sh and open up the generaged coverage.html/index.html and take a look at the reg.v file. 

test.cpp is the driver file and it basically reads and writes reg0,reg1,reg2,and reg3. I should have 100% coverage.

To run the example you will need verilator (obviously) cmake, and lcov installed.

If you need more information let me know

**Comment by wsnyder** [comment]
lcov doesn't support multiple coverage points on one line.  What you are seeing is that the implied "else" is not covered, which I believe it is correctly not covered.

I would suggest use verilator_coverage --annotate and you can see the additional points.

```
%000002            2'h0: begin
%000002               if (wstb[0]) reg0[7:0] <= din[7:0];
%000000               verilator_coverage: (next point on previous line)

```
