### ISSUE TITLE
Continuous delayed assignment descheduling

### ISSUE THREAD

**Issue by kbieganski** [verilator/verilator#3711]
According to IEEE 1800-2017 10.3.3 (_Continuous assignment delays_):

> In situations where a right-hand operand changes before a previous change has had time to propagate to the
left-hand side, then the following steps are taken:
a) The value of the right-hand expression is evaluated.
b) If this right-hand side value differs from the value currently scheduled to propagate to the left-hand side, then **the currently scheduled propagation event is descheduled**.
...

This does not happen in Verilator – the previously scheduled value is being assigned to the LHS even if one overwrites it.

**Comment by mtdudek** [comment]
I believe that the current behavior of continuous assignments is more suitable for modeling net delays?
