### ISSUE TITLE
Using c++11 in verilator 

### ISSUE THREAD

**Issue by ptyagi35** [verilator/verilator#3722]
I have been trying to use UVM-SystemC Library 1.0-beta4 public release, however it fails to build. I believe the problem can be resolved if we can enforce c++11 throughout the build. the verilator somehow defaults to c++14. How can we specify what c++ version to use for building in verilator?

**Comment by wsnyder** [comment]
C++14 is a superset of C++11, I would be surprised if downgrading would help compile UVM-SC, especially as that code is very new so should have been tested against a standard 6 years old.

Also changing compiler version often messes up libgcc, causing very ugly problems.

I suggest contact the maintainers with the error you are getting, probably they've seen it.

However to answer, you can get what you want by overriding the flags with configure.

./configure CXX="gcc -std=whatever"

The configure script may override your standard, but in theory should only do so if it tests that it has to for the features Verilator needs.
