### ISSUE TITLE
Conversion Error

### ISSUE THREAD

**Issue by MartinSolk** [verilator/verilator#3735]
Hello,
I don't understand, why verilator converts a number 
![image](https://user-images.githubusercontent.com/79546385/200882407-e74f8505-82ff-4b50-b3ea-8c7c37daad66.png)
to
![image](https://user-images.githubusercontent.com/79546385/200882505-00762bec-6274-432e-8b12-37c416c543b4.png)
isn't the right value 0x7e?
Greetings,
Martin

**Comment by wsnyder** [comment]
We will need more detail on what you are doing to get that result.

Also please use text instead of images when you can, thanks.

**Comment by MartinSolk** [comment]
I check it again and I think there isn't any issue. Sorry. But thanks for your quick response.
