### ISSUE TITLE
Need clarifications on --lib-create

### ISSUE THREAD

**Issue by poemonsense** [verilator/verilator#3780]
I'm using verilator to create static and dynamic libraries that can be linked with other files for simulation. However, I'm noticing some behavior changes from v4.218 to v5.002-89-ga83ed6b06.

In v4.218, if I specify user-provided cpp files to verilator and specify `--lib-create SimTop --exe`,  verilator creates the Makefile as follows: `libSimTop.so: $(VK_OBJS) $(VK_GLOBAL_OBJS) SimTop.o $(VM_HIER_LIBS)`.

In v5.002, with the same options, it would create as `libSimTop.so: $(VK_OBJS) $(VK_USER_OBJS) $(VK_GLOBAL_OBJS) SimTop.o $(VM_HIER_LIBS)`. That is, v5.002 links the user-specified cpp files together with verilator-generated cpp files.

If I don't pass the `--exe` option to verilator, both versions create the Makefile without `$(VK_USER_OBJS)`.

So I'm wondering what's the expected correct behavior of the `--lib-create`. Shouldn't it include all the cpp files specified by the user? I prefer that verilator automatically links then together because the user does inform verilator of these extra cpp files. In this way, the user leaves these specified cpp files to verilator without the need to compile them manually.

If so, should verilator links the user objects even without `--exe`? If not, though I think it's better to have this behavior, I assume there should be some regression between v4.218 and v5.002?

**Comment by poemonsense** [comment]
I think the user should not use `--exe` along with `--lib-create` concurrently. I'm just using them together for a workaround to let verilator deal with the cpp files for me.

**Comment by wsnyder** [comment]
For background see #3370 #3382.  I agree using --exe with --lib-create probably doesn't matter, perhaps you'd like to make a pull request to flag that as an error (long with a test)?

**Comment by poemonsense** [comment]
Thanks. I see that the `--lib-create` includes the user objects in #3382. However, in v5.002, when I'm using `--lib-create`, it does not include the user-specified cpp files?

Let me confirm it and check the verilator source files today. I'll try a PR for the arguments.

**Comment by poemonsense** [comment]
I think there're two separated issues.

First, Verilator does not generate the make rules for user-specified cpp files and objects. The error info with master branch of verilator is like the following:
```
make[3]: *** No rule to make target 'cppName.o', needed by 'libName.a'.  Stop.
```

I've opened a PR #3784 to fix that. Please help take a look.

Second, using `--exe` with `--lib-create` is a little bit strange, as there would be `main` function in the source files which would cause errors when linked with other libs. I'll try a PR later for this case.

**Comment by poemonsense** [comment]
I've opened a second PR #3785 to disable using `--exe` together with `--lib-create`.
