### ISSUE TITLE
Spelling fix - patch supplied

### ISSUE THREAD

**Issue by ldoolitt** [verilator/verilator#3797]
See attached patch.
[0001-Spelling-in-C-comments.patch.txt](https://github.com/verilator/verilator/files/10144681/0001-Spelling-in-C-comments.patch.txt)
Pretty obvious spelling fixes in comments of .cpp and .h files in include/ and src/
49 files changed.

**Comment by wsnyder** [comment]
I appreciate the clean ups. Would you mind doing it as a pull request, then I'll merge once it passes.

**Comment by ldoolitt** [comment]
OK, I think my end is done as #3798.   Just waiting for CI.
