### ISSUE TITLE
Memory leak in V3Sched __VactTriggered

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#3834]
@gezalore if you get a chance.

Running with VL_LEAK_CHECKS (comment in line in src/Makefile_obj) the t/t_EXAMPLE.pl test and most others fail with

    - V3Ast.cpp:1123:     Dumping obj_vlt/t_EXAMPLE/Vt_EXAMPLE_058_sched.tree
    %Error: LeakedNode: VARREF 0x555556e0a900 <e3553> {d19ai} @dt=0x555556e1da00@(w1)  __VactTriggered

This varref was created in V3Sched.cpp:1156:

        AstCFunc* const dumpp = actTrig.m_dumpp->cloneTree(false);

Note there are other leaks still present, but this one is hitting most tests.

**Comment by gezalore** [comment]
Also plugged the remaining memory leaks in the front-end, so on t_EXAMPLE the only thing remaining is inside the C/C++ library.
