### ISSUE TITLE
Nonexistent id linked to an existing symbol

### ISSUE THREAD

**Issue by kiryk** [verilator/verilator#3863]
References to nonexistent `foo::pkg::bar` (`foo` is an empty package) Verilate without errors if a package `pkg` with a variable `static int bar` exists.

If `foo::pkg::bar` does exist, it has priority over `pkg::bar`, as expected.

[Here](https://github.com/verilator/verilator/files/10401608/t_pkg_identifier.zip) is an example in `test_regress` format.

Tested with the latest commit (5fce23e90d2a721bb712dc9aacde594558489dda) on Fedora, Linux 6.0.14.

**Comment by wsnyder** [comment]
That's a little surprising, but can see why.  Perhaps you'd be willing to try a fix for this?  Thanks.
