### ISSUE TITLE
Namespaces under `std` are not linked correctly

### ISSUE THREAD

**Issue by kiryk** [verilator/verilator#3864]
When a class inside std is used as a namespace, the following error occurs:
```
%Error: Internal Error: t/t_process_rand.v:18:11: ../V3LinkDot.cpp:2796: Bad package link
-node: CLASSORPACKAGEREF 0xd627d0 <e62> {d18al} @dt=0@  process -> UNLINKED
   18 |       p = process::self();
      |    
```

This is because names in `std` are a special case for the lexer:
https://github.com/verilator/verilator/blob/5fce23e90d2a721bb712dc9aacde594558489dda/src/V3ParseImp.cpp#L527-L534
Their `yylval.scp` is always set to null. For tokens being namespace refs, the value is used as a scope pointer, so refs to namespaces inside `std` are always linked to null, which results in the error.

I think there's no right pointer to assign there instead, because `std` is parsed as the last file.

It probably can be solved by a different mechanic:
1. For every design parse `std` first.
2. For every undefined symbol, check if it exists in `std`.
3. If so, add `import std::*` to the netlist and mark std as used.
4. If `std` is not used, remove it right after the end of parsing.

It'd make Verilator parse `std` even if it's not needed, but `std` is rather small and otherwise the change shouldn't considerably affect the performance, I think it will also scale better.

Running my case requires modifying Verilator, but you can get the same behavior by declaring `static int bar` inside `std::mailbox` and using it in `t_mailbox.v`. [Here](https://github.com/verilator/verilator/files/10402544/t_mailbox_bar.txt) is a diff.

Tested with the latest commit (5fce23e90d2a721bb712dc9aacde594558489dda) on Fedora, Linux 6.0.14.

**Comment by wsnyder** [comment]
By the time LinkDot is called the std:: package has been loaded, so another possible hack is to fixup the links.

I don't really like always reading std as this makes it hard to debug flex/bison, but I can see that's probably better, if you do that please add a hidden --no-std option to avoid the std:: importing to help that debug (and be sure to test it).  Thanks.
