### ISSUE TITLE
Signed/unsigned parameter type improperly passed to module

### ISSUE THREAD

**Issue by jamesshi-hrt** [verilator/verilator#3865]
When instantiating two modules, one of which takes in a signed parameter type and the other taking in an unsigned parameter type, the second instantiated module seems to assume the parameter type is the same as the first instantiated module.

PR for a failing test and fix https://github.com/verilator/verilator/pull/3866

**Comment by wsnyder** [comment]
Thanks for your work on this, and putting up with my uncertainty!
