### ISSUE TITLE
"make test" failure on Debian testing

### ISSUE THREAD

**Issue by ldoolitt** [verilator/verilator#3878]
With verilator git master (commit a1160a85) built from source on Debian (pre-)Bookworm, the usual setup of
`autoconf && ./config && make && make tests`
fails at the `t_a2_first_sc.pl` step.

Symptoms match that reported in issue #3843 by @tijuca, and the fix/workaround I mention there, disabling `CPPFLAGS += $(CFG_CXXFLAGS_STD_NEWEST)` in `include/verilated.mk.in`, also fixes the problem in this context. It would be nice if @wsnyder or @kamilrakoczy could confirm this is the Right Answer.

[Debian testing](https://www.debian.org/releases/bookworm/), which will be called Bookworm when it releases in a few months, currently has the following package versions:
* g++ 12.2.0 (with matching libstdc++ 12.2.0)
* libc 2.36-8
* linux kernel 6.0.12

My tests are run on amd64.

**Comment by kamilrakoczy** [comment]
I think in some cases we still need to set proper std flag in verilated makefile (when compiler without std flag doesn't support c++11).

Instead I've created PR that resets this variable when it is not required while building verilator to make sure std flags are the same between building verilator and when building verilated design.
