### ISSUE TITLE
Warning for condition expression width

### ISSUE THREAD

**Issue by Zvord** [verilator/verilator#3884]
Verilator has a warning for conditions whose expressions have width more than 1. It seems to be an expected behaviour: there's a check in `t_lint_width_bad_out`
```
%Warning-WIDTH: t/t_lint_width_bad.v:40:12: Logical operator IF expects 1 bit on the If, but If's VARREF 'THREE' generates 41 bits.
                                          : ... In instance t
   40 |    initial if (THREE) $stop;
      |            ^~
```

But why? The language reference, chapter 12.4 says two things on this matter:
> If the cond_predicate expression **evaluates to true (that is, has a nonzero known value)**, the first statement shall be executed. ..

> Because the numeric value of the if expression is tested for being zero, certain shortcuts are possible. For example, the following two statements express the same logic:
```
if (expression)
if (expression != 0)
```

Unless I'm missing something, the specification implies that the expression width can be more than 1.

**Comment by wsnyder** [comment]
Warnings are about constructs that are language legal, but might represent a coding error.

An if statement from a synthesis statement is testing a boolean, something that is zero or one.  If something is multibit, that is a "2", the language says it is true but perhaps the author didn't think of how to handle that case.  Or, maybe the signal started a single-bit then later changed to a multibit field, and the compare is now incorrect as that was not considered.  Adding the != 0 makes the intent clear.
