### ISSUE TITLE
Support vpiDefName module names

### ISSUE THREAD

**Issue by AndrewNolte** [verilator/verilator#3906]
Currently I don't think there's any way to get the module name from the verilated cpp. You can get the instance name, and the path, but the actual module name is baked into the cpp class, and is not in the scope data.

I think we could put the module name in with ScopeData for vpi modules, and hence also put that in VerilatedScope. generate scopes would be blank, and top scopes would have a repeat of the name.

**Comment by wsnyder** [comment]
I presume you are referring to vpiDefName.  Your analysis and suggested implementation seem correct.  Do you think you can provide a pull request to add this (I'm assuming you want this feature)?

**Comment by AndrewNolte** [comment]
Yes, is vpiDefName not implemented currently? I wasn't planning on adding that to the vpi, mainly just as a member to VerilatedScope. But if it's not too much extra I could maybe do that as well. Would that just be overriding defName for VerilatedVpioModule?

**Comment by wsnyder** [comment]
That sounds right, and update the t_vpi_module test to check it please.

**Comment by AndrewNolte** [comment]
This is sort of touching the same code as https://github.com/verilator/verilator/pull/3840, could we please get that merged?

**Comment by wsnyder** [comment]
Thanks for fixing this.

**Comment by wsnyder** [comment]
For some reason all the regression tests didn't run against the pull, when it hit master there are many test failures (https://github.com/verilator/verilator/actions/runs/4088934517).  I've reverted.  I can't reopen a pull, so please make a new pull, thanks & sorry.

**Comment by forensicgarlic** [comment]
I'm a little confused on the status of this issue, based on being mentioned in the 5.008 release, but getting re-openned on Feb 3. Is this incorporated in 5.008, but work still remains?

**Comment by wsnyder** [comment]
It is not in.  I created Changes from the git log, where it was, but I forgot it had been backed out, I will remove from Change history.

**Comment by ksstrike** [comment]
Bringing the issue back on the table with #5572 as it's quite a useful functionality to have.
Aiming primarily for cocotb integration, so the assumption is we're running Verilator with `--public-flat-rw`.
I am aware of prior work having been done in #3931 / #3938, but I'm not exactly sure what the roadblock was.
@AndrewNolte seeing as you're still active in the project, could you chime in and elaborate?
