### ISSUE TITLE
Packed structure show as a wire in VCD, instead of a hierarchy

### ISSUE THREAD

**Issue by rapiz1** [verilator/verilator#3911]
When using a packed struct, the dumped VCD prints the struct as a wire instead of a hierarchy with members.

This is particularly disturbing when working with buses. I use packed struct for AXI bus and it results in a ~200 bits wire signal in VCD, which is barely readable.

**Comment by wsnyder** [comment]
Use --trace-structs https://veripool.org/guide/latest/exe_verilator.html#cmdoption-trace-structs

**Comment by rapiz1** [comment]
Thank you for the lightning answer!

**Comment by rapiz1** [comment]
For FST there's https://github.com/verilator/verilator/issues/1537 but I think that has already been resolved, as tested with `--trace-struct`, an FST dump showed the signal well.
