### ISSUE TITLE
Documentation is missing "Limitations" section

### ISSUE THREAD

**Issue by xobs** [verilator/verilator#3932]
The documentation mentions that users should refer to the "Limitations" section when a feature is "Unsupported": https://verilator.org/guide/latest/warnings.html#cmdoption-arg-Unsupported

However, this section does not appear to exist.

Either this section should be added, or this text should be updated.

**Comment by wsnyder** [comment]
See "Language Limitations", I fixed to cross reference, thanks for the report.
