### ISSUE TITLE
Commercial cooperation

### ISSUE THREAD

**Issue by KingkingLiu** [verilator/verilator#3934]
Design engineers at our company encountered some pain points when using spyglass lint, such as the long time it takes to check a large design, the slow time to fix bugs, and the limited number of licenses. While I would like to understand verilator and then do some Lint-related development on my own to help the front end team, it's too difficult for me and would take too long time. So I wonder if there is any possibility of cooperation between us. The way this works is that we come up with some specific lint requirements and you help us develop them. My superiors have also expressed a willingness to cooperate. Of coursr, we will pay you for your effort. We may discuss the cost and other specific cooperation details next if you agree to my proposal. Looking forward to your reply : ).

**Comment by wsnyder** [comment]
There are companies that can assist, there is a list here https://veripool.org/verilator_commercial_support/ in addition some other individuals may be available. Please email me at wsnyder@wsnyder.org for additional information.
