### ISSUE TITLE
How is verilator `make` [install] sourcing PYTHON3?

### ISSUE THREAD

**Issue by slagernate** [verilator/verilator#3936]
I have multiple python install locations. I tried an array of things, notably `export PYTHON3=/usr/bin/python3` (my ideal python path), but `sudo make install` kept using python located at `opt/pym32/bin`. I also set PYTHON3 in the `Makefile`, i.e. `PYTHON3 = /usr/bin/python3`. 

Ended up doing a search and replace `/$(PYTHON3)//usr/bin/python/g` on the entire verilator directory to get past this:

`find . -name '*' -type f -exec sed -i -e 's/$(PYTHON3)/\/usr\/bin\/python3/g' -- {} +`

Is there a more ideal way to handle this, without resorting to a virtual environment?

**Comment by wsnyder** [comment]
Verilator uses configure, which finds the paths of executables then builds them in.

Try "./configure PYTHON3=/path....." then rebuild.
