### ISSUE TITLE
Virus detection false positive?

### ISSUE THREAD

**Issue by stu-e** [verilator/verilator#3944]
/verilator/test_regress/t/t_unicode.pl is being flagged as a virus by NANO-Antivirus
If you drop a copy of this file into virustotal.com it will perform a virus scan using various virus scanners. Only NANO-Antivirus flags it as suspicious.
Are you aware of this?

**Comment by wsnyder** [comment]
Thanks for the report.  It looks like anything with "chr" sets that off which is of course stupid, all the more so as there's no way Perl looks like Visual Basic. Anyhow I'm sure it's pointless to argue this with the vendor. I committed a hack around this.
