### ISSUE TITLE
Instance level public declaration in configuration files

### ISSUE THREAD

**Issue by AndrewNolte** [verilator/verilator#3950]
The idea is to use the full path in config files to publicize objects at the instance level. Ex:

```
public_flat  -path top_tb.gen_arr[0].signal
```

Would this be possible? And would this provide much of a build/runtime performance benefit? In my experience making fewer things public speeds things up, so that's the motivation for this.

**Comment by wsnyder** [comment]
The public indication is currently on a given signal ignoring its scope, and the final data structures in the generated C are likewise without scope (in attempt to reuse the code between different scopes).  So at present I think this is hard, and not much to be gained.  Good question though.
