### ISSUE TITLE
-U linker flag on MacOs: PR #3823 fix should be added to cmake files as well

### ISSUE THREAD

**Issue by peter-d** [verilator/verilator#3978]
Seen this in v5.006 and master. PR #3823 fixes the weak symbols issue in a Makefile flow, but the same fix should be added to the cmake file, by adding the right linker flags when we detect AppleClang:
```cmake
add_link_options(-Wl,-U,__Z15vl_time_stamp64v,-U,__Z13sc_time_stampv)
```

**Comment by wsnyder** [comment]
Thanks for debugging and making a good pull request.
