### ISSUE TITLE
Incorrect results for reverse for loop

### ISSUE THREAD

**Issue by zcharlesz** [verilator/verilator#4000]
The logic after transforming with verilator is not the same as original RTL code;

Example:
example is edited based on verilator/examples/make_tracing_sc/top.v; just replace top.v with the code below and then input command "make" (add verilator_flags  --Wno-fatal).

=============================================================
// top.v
module top
  (
   // Declare some signals so we can see how I/O works
   input              clk,
   input              fastclk,
   input              reset_l,

   output wire [1:0]  out_small,
   output wire [39:0] out_quad,
   output wire [69:0] out_wide,
   input [1:0]        in_small,
   input [39:0]       in_quad,
   input [69:0]       in_wide
   );

   // Connect up the outputs, using some trivial logic
   assign out_small = ~reset_l ? '0 : (in_small + 2'b1);
   assign out_quad  = ~reset_l ? '0 : (in_quad + 40'b1);
   assign out_wide  = ~reset_l ? '0 : (in_wide + 70'b1);

   // And an example sub module. The submodule will print stuff.
   sub sub (/*AUTOINST*/
            // Inputs
            .clk                        (clk),
            .fastclk                    (fastclk),
            .reset_l                    (reset_l));

   // Print some stuff as an example
   initial begin
      $display("[%0t] Model running...\n", $time);
   end

// ============add code start=====================
parameter row=15;
parameter col=9;

reg [row:0][col:0]  seg_chunk_num_pre;
reg [row:0][col:0]  seg_chunk_num;
reg [row:0][col:0]  seg_chunk_num_flip;

integer k;
always @(posedge fastclk) begin
    if (reset_l)
		for (k=0; k<row+1; k=k+1) begin
			seg_chunk_num_pre[k] <= 10'b0;
		end
	else
		for (k=0; k<row+1; k=k+1) begin
			seg_chunk_num_pre[k] <= 10'b1 + k;
		end
end	

integer i;
always @(*) begin
	for (i=0; i<row+1; i=i+1) begin
		seg_chunk_num[i] = seg_chunk_num_pre[i];
		seg_chunk_num_flip[i] = seg_chunk_num[row-1-i];
	end
end	
// ============add code end=====================

endmodule

=============================================================

Waveform:
Ideally seg_chunk_num_flip should be changed simultaneouslly after seg_chunk_num being changed;
but the waveform shows that parts of bits of seg_chunk_num_flip is changed at next clk posedge, which is not the original logic of RTL code!
![image](https://user-images.githubusercontent.com/120101215/222698467-263759f5-a621-416d-adc9-a7624ead9282.png)

Besides, if the order of code is reversed. such as code below: The waveform will be fine. 
		//seg_chunk_num[i] = seg_chunk_num_pre[i];
		seg_chunk_num_flip[i] = seg_chunk_num[row-1-i];
                seg_chunk_num[i] = seg_chunk_num_pre[i];

verilator version:  verilator-master;  downloaded 2023/03/03
OS: CentOS 6.10

**Comment by wsnyder** [comment]
```
always @(*) begin
  for (i=0; i<row+1; i=i+1) begin
    seg_chunk_num[i] = seg_chunk_num_pre[i];
    seg_chunk_num_flip[i] = seg_chunk_num[row-1-i];
  end
end
```

This is saying "when seq_chunk_num_pre or seq_chunk_num is seen to change, run this loop".  IEEE allows the simulator to decide when that is. The problem is the loop is setup so that that the second part looks at bits the first hasn't written yet.  So running this once won't get the results you expect.

Your code should be like this:  (Or use a generate loop outside the always).

```
always @(*) begin
  for (i=0; i<row+1; i=i+1) begin
    seg_chunk_num[i] = seg_chunk_num_pre[i];
  end
  for (i=0; i<row+1; i=i+1) begin
    seg_chunk_num_flip[i] = seg_chunk_num[row-1-i];
  end
end

```
