### ISSUE TITLE
Signal names with --report-unoptflat

### ISSUE THREAD

**Issue by T-Platz** [verilator/verilator#4029]
I'm currently debugging a circular combinational loop reported by Verilator as a `%Warning-UNOPTFLAT` with the `--report-unoptflat` flag. This generates a .dot file which I visualized using the `dot` command. However, this graph only contains a loop of eight nodes n0, ..., n7, all labeled with c1. Sadly, this doesn't really help, as I still don't know where exactly the loop is. Is there a way to include signal names and/or line numbers in the .dot file?

**Comment by wsnyder** [comment]
When it built the subgraph it was missing cloning some information. Please try the new trunk.

**Comment by wsnyder** [comment]
commit b2ced6ff1 - mentioned wrong bug number in message
