### ISSUE TITLE
Help debugging an UNOPTFLAT

### ISSUE THREAD

**Issue by shareefj** [verilator/verilator#4051]
Hi there,

this is my first time really looking in detail at a complex UNOPTFLAT issue and I'm a bit stuck with how to debug this further.  The signal that is causing the issue is a top level input from a tri-state pad model.  The signal, `gpio_pad_in[11:0]` feeds multiple blocks within the design and running Verilator with the `--report-unoptflat` flag seems to suggest multiple signals within various levels of hierarchy as good candidates to split.  The dot graph seems to be too big to open in any PDF reader I've tried so far which in itself might indicate an error.

Two of the signals in question here are a clock and bi-directional data pin which feed sequential elements in one of the hierarchies.  I'm confused why the tool is complaining about these as most of the examples I've seen for UNOPTFLAT issues are combinational assignments that have to be evaluated multiple times.

Perhaps a first step would be try to break out all my GPIO into individual nets rather than buses?  I wonder if Verilator gets confused as these are really all independent signals?

**Comment by wsnyder** [comment]
Sorry, missed replying to this.  Yes, verilator treats all signals in a bus as the "same" signal. In some cases using split_vars (see manual) may help fix these sort of issues.  But, in many cases you can simply ignore these warnings.

Closing as answered but feel free to follow up.
