### ISSUE TITLE
How to generate verilator executable file  with debugging symbol?

### ISSUE THREAD

**Issue by wangjialei1998** [verilator/verilator#4095]
I use the following command to generate the executable file :
$(VERILATOR) --cc -CFLAGS --debug --build -exe top.v sim_main.cpp
But when executed in gdb like this: 
gdb Vtop
It comes out that: "No debugging symbols found in ./Vtop"
I am new to verilator. 
Could any one telll me how to debug the simulating file in gdb ?

**Comment by wsnyder** [comment]
--debug enables Verilator debug, not compiler debug.

In gcc you use "-ggdb" typically to enable debug symbols and need to pass to linker also.

So use e.g. 

     $(VERILATOR) --cc --build --exe -CFLAGS -ggdb -LDFLAGS -ggdb top.v sim_main.cpp

**Comment by wangjialei1998** [comment]
thank you !!!!It works!
