### ISSUE TITLE
VldelayScheduler undefined nextTimeSlot()

### ISSUE THREAD

**Issue by genfrontier** [verilator/verilator#4104]
Hey guys,

So i was able to build on master our model, however after the verilate and compile, the linker complains with tons of these : 

/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: ../../../../src/t/versim-core/verilated-hw/out/c_verilated_hw__ALL.a(c_verilated_hw.o): in function `c_verilated_hw::nextTimeSlot()':                                                                                                                                   
  
c_verilated_hw.cpp:(.text+0xb78): undefined reference to `VlDelayScheduler::nextTimeSlot() const'

i have checked -fcoroutines in CXX flags and --timing on verilator opts, i wonder why this function is not seen,

I see in the verilator code at verilator/include/verilated_timing.h the function is there, why is not being picked up?

Thanks

**Comment by wsnyder** [comment]
Are you sure you are linking against all the .cpp files that verilator has listed in the makefile it generates?  I'm pretty sure you aren't getting verilated_timing.cpp.

Closing assuming that's it, but feel free to follow up.
