### ISSUE TITLE
Build issues on CentOS - recent

### ISSUE THREAD

**Issue by svenka3** [verilator/verilator#4105]
On a CentOS laptop, up until last week i built Verilator from source (autoconf/configure/make). I used gcc 13.0.1 (unchanged). With recent pull from master, I get errors around: std::__final etc. So I added std=c++14 as below:

```sh
sudo make -j 5 CXX=/home/srini/tools/GCC/exe_gcc_10/bin/g++ CXXFLAGS="-std=c++14" CC=/home/srini/tools/GCC/exe_gcc_10/bin/g++ LD=/home/srini/tools/GCC/exe_gcc_10/bin/g++
```
Now I get errors from linker as below:

```log
V3Tristate.cpp:(.text+0x846): undefined reference to `std::__throw_bad_array_new_length()'
```
Any clues please?

Thanks

**Comment by wsnyder** [comment]
Closing assuming you figure it out, please consider posting here with more info in case others come across it.

**Comment by svenka3** [comment]
Thanks for the clue and sorry for the noise. Below is the fix - use CC=<path_to_latest_gcc> to use it as linker. 

It now works fine. 

```sh
sudo make -j 5 CXX=/home/srini/tools/GCC/exe_gcc_10/bin/g++ CXXFLAGS="-std=c++14" CC=/home/srini/tools/GCC/exe_gcc_10/bin/gcc LD=/home/srini/tools/GCC/exe_gcc_10/bin/g++
```
Thanks

**Comment by svenka3** [comment]
BTW, I faced the same issue on WSL (Windows 10) as well. There my g++ was 10.3.0, all I needed to do was to add CXXFLAGS="-std=c++14" to configure and make.
