### ISSUE TITLE
GLS compile takes much longer even on small design

### ISSUE THREAD

**Issue by svenka3** [verilator/verilator#4107]
How may we help - what is your question?

> I am trying to run a small APB slave model post-synthesis GLS (pre-layout, no timing). RTL gets done in a giffy. GLS compile takes significantly long time (in g++ each..cpp files).

Estimated gate count:
```log
   Number of cells:              37296
```
I can provide test RTL and netlist if this is of some interest to dig deeper - or is this sort of known, hence of no interest here?

Kindly advice.
Thanks

**Comment by wsnyder** [comment]
How long does the longest single file take to compile?  How many files are compiled?
