### ISSUE TITLE
Simulation coredumps after first call to eval()

### ISSUE THREAD

**Issue by genfrontier** [verilator/verilator#4118]
Hey guys, me again, good news!, i was able to verilate and compile our model using v 5.009.

i too added a --main to get some example on how to make the simulation loop as i am using --timing now and our env previously was on v 4.040.

However as soon as the first call to eval happen i get a coredump. I used gdb to get the back trace and looks like this: 

#0  0x0000000002091920 in c_verilated_hw_tt_srcb_reg_bank_x2__pi75___stl_sequent__TOP__tt_t_with_l1__t__fpu__srcb_in_fpu__DOT__srcb_regs__u_srcb_reg_bank_x2__BRA__1__KET____0(c_verilated_hw_tt_srcb_reg_bank_x2__pi75*) ()
#1  0x0000000001a6f538 in c_verilated_hw___024root___eval_stl__0(c_verilated_hw___024root*) ()
#2  0x0000000001a85493 in c_verilated_hw___024root___eval_stl(c_verilated_hw___024root*) ()
#3  0x0000000001a85512 in c_verilated_hw___024root___eval_settle(c_verilated_hw___024root*) ()
#4  0x00000000008c2314 in c_verilated_hw::eval_step() ()
#5  0x000000000053a5e0 in c_verilated_hw::eval (this=0x11c622c0) at /verilated-hw/out/c_verilated_hw.h:191
#6  0x0000000000549676 in api::core::assert_reset (core=0x11c62da0) at /tests/versim-api.h:171

I wonder if there is any pointers on what could be happening, i am using the new 'contexp' and topp style now, and call the 

contextp->time(topp->nextTimeSlot());

whenever i need time to pass.

I tried a few things, like using the default context instead and use the context pointer from the verilated hardware instead to no avail.

Any help is greatly appreciated.

Thanks.

**Comment by wsnyder** [comment]
Verilate (or compile with similar)

  -CFLAGS -DVL_DEBUG=1    -CFLAGS -D_GLIBCXX_DEBUG    -CFLAGS -ggdb    -LDFLAGS -ggdb

and then see if you get more info, and please attach the source files around the line the backtrace indicates.  Likely that will be enough to also help you debug what is happening there.
