### ISSUE TITLE
Unrecognized command line option -fcoroutines

### ISSUE THREAD

**Issue by gabizon103** [verilator/verilator#4119]
Running verilator, I get a g++ error stating: `unrecognized command line option ‘-fcoroutines’`

I am using verilator 5.009 on Ubuntu 20.04 with g++ 9.4.0. What is the correct version of g++ to be using?

**Comment by kbieganski** [comment]
Try [GCC 10 or newer](https://veripool.org/guide/latest/exe_verilator.html#cmdoption-timing).

Or `--no-timing` if not using timing features.
