### ISSUE TITLE
Using systemc.h causes namespace issues in larger projects

### ISSUE THREAD

**Issue by eyck** [verilator/verilator#4126]
When using verilator with SystemC in larger projects the use of systemc.h causes issues as it imports by default the namespaces sc_core and sc_dt.
In larger projects e.g. using SystemC-UVM this can lead to ambiguous symbol resolution.

**Comment by PkmX** [comment]
Doesn't verilator still emit `#include "systemc.h"` in the generated model's header?

**Comment by wsnyder** [comment]
@PkmX yes there is still a `#include "systemc.h"` emitted. I'm not sure how that relates to this issue; if you are having problems please open a new issue as we think this one is resolved, thanks.
