### ISSUE TITLE
How can I build Verilator without optimizations?

### ISSUE THREAD

**Issue by tudortimi** [verilator/verilator#4176]
I'm doing some edit/re-compile work on Verilator and this is pretty slow due to the fact that it has to optimize as well (i.e. to build in `obj_opt`). It compiles with `-O3`. Is there a way to reduce the optimization level to hopefully make it faster? I'm only really interested in the "debug" version. Can I skip building the optimized version altogether?

**Comment by wsnyder** [comment]
export VERILATOR_NO_OPT_BUILD=1 

Then build.  Don't forget to remove it before final testing.

**Comment by tudortimi** [comment]
I also found a `VL_NOOPT` variable in one of the Makefiles which allowed me to pass `-O0` to the `obj_opt` build.
