### ISSUE TITLE
Question about verilator_coverage: what is the max coverage?

### ISSUE THREAD

**Issue by flaviens** [verilator/verilator#4191]
Hi!

I'm new with coverage measurements. I followed the docs and would like to trace line and toggle coverage.
I use `verilator_coverage` and get a concise report, using `--rank` such as:

```
Tests:
  Covered,     Rank,  RankPts,  Filename
    44087,        1,    44087,  "coverage.dat"
```

The question is: I'd like to know if I'm covering 10% or 99% of the coverage points. **How to know how many cover points are there in total**?

Thank you very much!
Flavien

**Comment by wsnyder** [comment]
Ranking is for test grading, you have only one test so that isn't likely useful.
The normal "--annotate" report will tell you the coverage.

>Total coverage (2/28) 7.00%

2 buckets of 28.

Closing as answered but feel free to follow up.
