### ISSUE TITLE
share/verilator/include/verilated.mk contains non-existent AR=/usr/local/bin/ar on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#4213]
On FreeBSD it installs the file ```share/verilator/include/verilated.mk``` with this line:
>  AR = /usr/local/bin/ar

The build should find the ar executable and use it, for example:
```
$ which ar
/usr/bin/ar
```

Version: 5.010
FreeBSD 13.2 STABLE

**Comment by christopher-bowman** [comment]
yes making the change in share/verilator/include/verilated.mk seems to work for me (I just didn't know where to look, thank you)

**Comment by igalic** [comment]
it might be good to change this to

```majefike
AR ?= /usr/bin/ar
```

i reckon many package build systems might set that variable

**Comment by yurivict** [comment]
I think that this line should be just:
> AR = ar

to allow the PATH variable to determine the path.

**Comment by wsnyder** [comment]
Note it comes from whatever ./configure determines.  You can override it with "./configure AR=AR".

**Comment by yurivict** [comment]
> Note it comes from whatever ./configure determines. You can override it with "./configure AR=ar".

Then this is a bug in configure because ```/usr/local/bin/ar``` doesn't exist on this platform.

**Comment by wsnyder** [comment]
What does ./configure print?

     checking for ar... ar

You can add echos or whatever to debug the shell code in "configure" that computes this.  Most likely you do have a $AR variable, or ar is in your $PATH. This code shouldn't be able to pull "/usr/local/bin" from nowhere.

**Comment by yurivict** [comment]
I found what the problem was.

For whatever reason verilator's port build requires ar from binutils. But binutils wasn't present at the runtime, so /usr/local/bin/ar provided by binutils isn't present.

Some time back binutils was added as dependency to solve some problem, I don't remember what problem that was.

I will correct the port.

Thank you for your help!
