### ISSUE TITLE
undefined reference to `VlThreadPool::VlThreadPool error when compiling

### ISSUE THREAD

**Issue by fortyone041** [verilator/verilator#4218]
OS: Pop!_OS 22.04 LTS
Pyenv: 3.11.1
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Kernel: 6.2.6

I'm getting this error when compiling :

`g++ -I /home/fortyone/Documents/verilator/include -I /home/fortyone/Documents/verilator/include/vltstd main.o Vtoplevel___024root__DepSet_h887c3000__0.o Vtoplevel___024root__DepSet_h887c3000__0__Slow.o Vtoplevel___024root__DepSet_h9890b585__0.o Vtoplevel___024root__DepSet_h9890b585__0__Slow.o Vtoplevel___024root__Slow.o Vtoplevel___024unit__DepSet_h1dabdd97__0__Slow.o Vtoplevel___024unit__Slow.o Vtoplevel__ConstPool_0.o Vtoplevel.o Vtoplevel__Syms.o /home/fortyone/Documents/verilator/include/verilated.cpp -o testbench`

The error I get:

```
/usr/bin/ld: /tmp/ccRF5bL0.o: in function `VerilatedContext::threadPoolp()':
verilated.cpp:(.text+0xdc28): undefined reference to `VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)'
```

verilator --version 

```
$ verilator --version
Verilator 5.010 2023-04-30 rev v5.010-33-gc37ec1975
```

I'm still learning to use Verilator. Help is appreciated. Thanks !

**Comment by wsnyder** [comment]
You need to link against more than just verilated.cpp.  The "verilated.mk" file that is generated has the list of .cpp files necessary.

If you can, it's much easier to just use "verilated --binary" and it will do the work for you.
