### ISSUE TITLE
Error while running verilator with --timing option

### ISSUE THREAD

**Issue by navaneethM1** [verilator/verilator#4243]
Hi,
I am facing this error:
g++: error: unrecognized command line option ‘-fcoroutines’; did you mean ‘-fc-prototypes’?
Could you please let me know how to resolve this?

**Comment by Risto97** [comment]
You are using an old gcc version, I think you need gcc greater than 10

**Comment by wsnyder** [comment]
Correct, C++20 is needed to use --timing, also note older compilers work with --no-timing.
