### ISSUE TITLE
Including help2man dependency in installation guide

### ISSUE THREAD

**Issue by andkostov** [verilator/verilator#4260]
How may we help - what is your question?

Dependency on `help2man` isn't listed in the installation guide, resulting in the following "error":
[https://pastebin.com/8iEQxVbr](https://pastebin.com/8iEQxVbr)

Proposed fix aims to improve clarity by including `help2man` in the list of dependencies prescribed in the Installation guide.

**Comment by wsnyder** [comment]
Thanks for the pull to fix this.

**Comment by JL102** [comment]
@wsnyder FYI help2man is now listed twice on that line.
