### ISSUE TITLE
Verilator build compiler vs runtime compiler

### ISSUE THREAD

**Issue by udif** [verilator/verilator#4269]
>Thanks for taking the time to report this.

>What would you like added/supported?

When Verilator is build using GCC it creates a specific `include/verilated.mk` file. When it is built using clang, it creates a different file.

If verilator is built using GCC but later clang is installed, and you try to compile your design with `make CXX=clang++-12 CC=clang-12` or similar values, the design will not compile. Every file compiled produces the (probably harmless) warning:
> warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]  

And later, `ld` fails with many messages similar to : 
`relocation R_X86_64_32 against 'XXXXX' can not be used when making a PIE object; recompile with -fPIE`  
or
`relocation R_X86_64_32S against 'XXXXX' can not be used when making a PIE object; recompile with -fPIE`  

There should be a simpler way to have both files, e.g. `include/verilated_gcc.mk` , `include/verilated_clang.mk` , and add a compiler selection flag for the Verilator runtime. A typical use scenario is when a user tries to decide which compiler gives better performance or compiles his design faster.

**Comment by wsnyder** [comment]
I appreciate this would be useful. Currently Verilator needs to run configure checks to compute compiler option flags.  Doing so for a "theoretical" other compiler it does not know about (e.g. clang if using gcc) might be possible but is error prone, and still would not work if the compiler is later changed.

The other alternative is to at Verilation or verilated compile time run these experiments, which would be slow.

Also both options would be complicated for a relatively rare use case.

Therefore unfortunately this won't be fixed.
