### ISSUE TITLE
Ongoing Verilator parallelization

### ISSUE THREAD

**Issue by mglb** [verilator/verilator#4291]
I and @kamilrakoczy at Antmicro experiment with parallelization of V3Expand and V3Gate stages.

When picking a stage for parallelization we've first limited our options to longest running stages, then picked stages that look like they should profit from parallelization.

The table below shows execution time of longest running stages during Verilation of a larger design (note that const_cpp runs twice):

|    time [s] | stage                        |
|------------:|:-----------------------------|
|  26.683474  |  058_reorder                 |
|  23.547353  |  088_expand                  |
|  18.088358  |  090_subst                   |
|  17.510266  |  055_gate                    |
|  16.529585  |  072_sched-create-nba        |
|  12.475455  |  089_const_cpp               |
|  12.427678  |  036_scope                   |
|  12.038215  |  080_trace                   |
|   8.947663  |  101_emit (already parallel) |
|   7.790785  |  066_sched-settle            |
|   6.777922  |  030_linkdot                 |
|   6.504149  |  091_const_cpp               |

(measured using Verilator 5.011 built with tcmalloc on Linux @ i7-12700)

As for V3Expand, it takes at input an AST consisting mainly of a long list of AstCFunc nodes. Conveniently, all work done by V3Expand happens inside those nodes, and operations in each node are generally independent from operations in other nodes.
The idea is to process each AstCFunc as a separate parallelizable job. Since each AstCFunc is worked on independently the AST doesn't require synchronization between threads.

The one thing ignored above is type table access, which is used quite often and almost everywhere, including node constructors and quite a lot of property getters, making it rather a separate issue. The type table is a part of the root node, which also needs synchronization for occasionally run functions like tree dumping.
My plan is to synchronize type table and the root node access using two separate read-write mutexes. Type table reading and AST modification (assuming that threads work on independent AST branches) would require obtaining a shared locks. Type table modification and exclusive AST access (where it is guaranteed that the whole AST stays in a stable valid state) should happen after obtaining exclusive locks.
There's also the global const pool, another part of the root node, which seems to need locking in a way similar to the type table locking.

**Comment by wsnyder** [comment]
Did you run with --threads?  I would have expected the partitioner to dominate.

Be careful of separate locks for the type table, constants, and root node, depending how they are used you might get a dining philosophers problem.  Make sure each can make progress separately.

**Comment by wsnyder** [comment]
I agree V3Expand seems a good first candidate.

**Comment by mglb** [comment]
The initial table has been generated with `--no-threads`.

I did measurements with different `--threads` values (same design, but different machine).
Looks like V3Partition doesn't register itself in the stats. It is included in duration of the next stage, variableorder, which is the longest one according to stats.

<details><summary>Stage durations with `threads` set to 16, 2, 1 @ i7-7820X (8 cores * 2 threads)</summary><p>

|                               |  threads=16 |   threads=2 |   threads=1 |
|:------------------------------|------------:|------------:|------------:|
| TOTAL                         | 1534.890703 | 1012.622322 |  856.052641 |
| 099_variableorder             |  534.595350 |   97.547458 |    0.136157 |
| 072_sched-create-nba          |  143.307542 |  133.836034 |   40.503610 |
| 058_reorder                   |   73.845363 |   64.476187 |   63.970654 |
| 089_const_cpp                 |   73.580961 |   64.705498 |  109.608784 |
| 088_expand                    |   66.190740 |   57.334982 |   56.053782 |
| 090_subst                     |   52.314976 |   48.351193 |   45.656121 |
| 055_gate                      |   48.733394 |   44.856901 |   44.938559 |
| 091_const_cpp                 |   38.113465 |   34.092016 |   56.305170 |
| 080_trace                     |   31.377650 |   29.982856 |   26.761971 |
| 036_scope                     |   29.681696 |   26.902816 |   26.649957 |
| 101_emit                      |   23.002624 |   21.623267 |   20.549624 |
| 066_sched-settle              |   19.898508 |   18.568825 |   18.543321 |
| 081_localize                  |   16.926329 |   15.834090 |   14.793389 |
| 003_linkdot                   |   13.850996 |   12.126144 |   12.317940 |
| 077_life_post                 |   13.808189 |   13.216151 |   12.387590 |
| 023_linkdot                   |   13.674228 |   12.182146 |   12.223423 |
| 082_descope                   |   13.601065 |   12.478555 |    9.910335 |
| 054_tracedecl                 |   12.561418 |   11.224592 |   11.206176 |
| 083_combine                   |   12.381788 |   11.670006 |   12.632445 |
| 098_common                    |   12.181231 |   11.130591 |    0.001251 |
| 076_life                      |   12.139072 |   11.661992 |   10.883525 |
| 093_merge_cond                |   11.939597 |   11.062705 |    9.687779 |
| 037_linkdot                   |   11.869763 |   10.638445 |   10.668137 |
| 096_cast                      |   11.424857 |   10.635482 |    9.557259 |
| 030_linkdot                   |   10.907424 |    9.721880 |    9.696318 |
| 087_premit                    |   10.466088 |    9.427539 |    7.894335 |
| 009_linkdotparam              |    9.060786 |    8.117723 |    8.175924 |
| 029_inline                    |    7.988585 |    7.504337 |    7.517697 |
| 012_width                     |    7.813950 |    6.893695 |    6.887582 |
| 031_dfg-optimize              |    7.623935 |    7.190438 |    7.168840 |
| 086_clean                     |    7.038103 |    6.375905 |    5.712684 |
| 028_dfg-optimize              |    6.953875 |    6.488591 |    6.551614 |
| 052_split                     |    6.851431 |    6.321017 |    6.290132 |
| 002_linkparse                 |    6.838857 |    6.506310 |    6.524608 |
| 078_const                     |    6.767622 |    6.259942 |    6.098041 |
| 079_deadAllScoped             |    6.697042 |    6.379649 |    5.937425 |
| 075_const                     |    6.685371 |    6.192655 |    6.077513 |
| 084_const                     |    6.264676 |    5.736300 |    4.861109 |
| 092_deadAll                   |    5.942447 |    5.613383 |    5.045757 |
| 060_activetop                 |    5.673252 |    5.232033 |    5.252032 |
| 061_sched-gather              |    5.539555 |    5.130394 |    5.127770 |
| 067_sched-partition           |    5.538687 |    5.309221 |    5.308659 |
| 100_cuse                      |    5.399258 |    5.110557 |    4.646055 |
| 097_cctors                    |    5.327805 |    5.063613 |    4.657117 |
| 068_sched-replicate           |    4.880341 |    4.701433 |    4.673698 |
| 057_deadAllScoped             |    4.618235 |    4.377518 |    4.375944 |
| 056_const                     |    4.572540 |    4.241036 |    4.222871 |
| 095_depth                     |    4.503180 |    4.290250 |    3.912659 |
| 085_deadAll                   |    4.277472 |    4.047594 |    3.476155 |
| 025_tristate                  |    4.141337 |    3.909936 |    3.921393 |
| 059_delayed                   |    4.006899 |    3.793864 |    3.796491 |
| 074_clock                     |    3.918617 |    3.741554 |    3.573331 |
| 042_task                      |    3.791353 |    3.583379 |    3.616648 |
| 071_sched-create-act          |    3.743300 |    3.595847 |    3.577905 |
| 043_name                      |    3.586975 |    3.334243 |    3.336315 |
| 050_deadDtypesScoped          |    3.258136 |    3.027000 |    3.013310 |
| 040_deadDtypesScoped          |    3.104842 |    2.881730 |    2.880765 |
| 065_sched-break-cycles        |    3.072733 |    2.944390 |    2.957953 |
| 019_const                     |    3.014113 |    2.609924 |    2.696843 |
| 046_const                     |    2.794185 |    2.544599 |    2.542195 |
| 049_const                     |    2.629525 |    2.395328 |    2.405651 |
| 039_const                     |    2.555536 |    2.320740 |    2.320962 |
| 020_split_var                 |    2.541849 |    2.261887 |    2.264139 |
| 044_unroll                    |    2.175308 |    2.014504 |    2.017915 |
| 032_const                     |    1.973192 |    1.828968 |    1.786901 |
| 035_const                     |    1.838984 |    1.669868 |    1.704762 |
| 013_widthcommit               |    1.808606 |    1.610256 |    1.614078 |
| 008_param                     |    1.751000 |    1.624061 |    1.621970 |
| 024_begin                     |    1.711149 |    1.622328 |    1.620863 |
| 026_unknown                   |    1.586184 |    1.401708 |    1.401891 |
| 094_reloop                    |    1.579635 |    1.475485 |    1.298654 |
| 045_slice                     |    1.577053 |    1.499716 |    1.497617 |
| 047_life                      |    1.508615 |    1.422183 |    1.422040 |
| 041_case                      |    1.446990 |    1.378887 |    1.368588 |
| 015_undriven                  |    1.371346 |    1.262345 |    1.246815 |
| 004_linkresolve               |    1.215433 |    1.127170 |    1.130584 |
| 051_active                    |    1.171718 |    1.121532 |    1.122621 |
| 053_splitas                   |    1.162868 |    1.110103 |    1.103453 |
| 016_assertpre                 |    1.058823 |    1.011467 |    1.015427 |
| 033_deadDtypes                |    0.974957 |    0.926048 |    0.929216 |
| 048_table                     |    0.870605 |    0.827481 |    0.834335 |
| 014_const                     |    0.772629 |    0.723047 |    0.721957 |
| 017_assert                    |    0.757047 |    0.717007 |    0.725330 |
| 011_deadModules               |    0.725084 |    0.680580 |    0.680381 |
| 010_linklvalue                |    0.608725 |    0.578277 |    0.571108 |
| 005_linklvalue                |    0.601600 |    0.564592 |    0.563794 |
| 007_linkinc                   |    0.600653 |    0.569670 |    0.570668 |
| 027_dfg-extract               |    0.572948 |    0.544765 |    0.544636 |
| 006_linkjump                  |    0.557698 |    0.531590 |    0.531132 |
| 022_dearray                   |    0.475345 |    0.453633 |    0.453589 |
| 038_class                     |    0.436822 |    0.427014 |    0.427197 |
| 021_split_var                 |    0.225881 |    0.214809 |    0.215222 |
| 034_inst                      |    0.220883 |    0.212085 |    0.213329 |
| 062_sched-static              |    0.087543 |    0.084612 |    0.084580 |
| 070_sched-create-triggers     |    0.040115 |    0.037258 |    0.036168 |
| 063_sched-initial             |    0.016825 |    0.016146 |    0.015946 |
| 069_sched-create-ico          |    0.014716 |    0.013845 |    0.013651 |
| 064_sched-final               |    0.001379 |    0.001273 |    0.001241 |
| 073_sched                     |    0.001052 |    0.001071 |    0.001020 |
| 018_wraptop                   |    0.000573 |    0.000572 |    0.000563 |
| 001_cells                     |    0.000000 |    0.000000 |    0.000000 |
</p></details>
