### ISSUE TITLE
Branch Coverage in Verilator

### ISSUE THREAD

**Issue by RadicalRoman** [verilator/verilator#4305]
Does anybody know how to get branch coverage from Verilator? I have a lot of "assign x = a ? b : c;" statements and would like only 50% branch coverage if b but not c is hit.

**Comment by wsnyder** [comment]
Conditional operators are considered expression coverage, not branch coverage, and expression coverage isn't currently supported.  We'd of course welcome improvements to add that, but it's not simple.

**Comment by RadicalRoman** [comment]
Is toggle or assertion coverage supported?

**Comment by wsnyder** [comment]
Yes, both, please see the documentation for details.
