### ISSUE TITLE
Bit-Level Toggle Coverage

### ISSUE THREAD

**Issue by RadicalRoman** [verilator/verilator#4312]
The "--coverage-toggle" flag enables toggle coverage collection in Verilator. When I open the dumped *.dat file, I see one column of signal names (often individual bits within a wider bus) and one column with integers, the number of times that bit has toggled.

When using verilator_coverage/genhtml to view coverage results, this bit-level toggle information disappears. For instance, given a 32-bit port, the number of times that port's value has changed will be reported. The number of times an individual bit within that port has toggled is not reported.

Is there any way to view coverage and include bit-level toggle information?

**Comment by wsnyder** [comment]
You need to use verilator_coverage with --annotare. The genhtml format does not have a way to express the detailed information.
