### ISSUE TITLE
undefined reference to `VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)'

### ISSUE THREAD

**Issue by fabiodl** [verilator/verilator#4331]
I already checked #4218 but I am linking agains the .a created by the .mk file.

I still get 
undefined reference to `VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)'

what am I doing wrong?

**Comment by wsnyder** [comment]
Perhaps your "include" directory is from a different Verilator version then the verilator executable?

Debug it by making sure you see verilated_threads.cpp being compiled, then verilated_threads.o getting linked into your program, and that the verilated_threads.cpp that was used in this has that (later undefined) reference defined in it.

Closing for now as seems something build related at your end, though please feel free to follow up here, and/or reopen if you do think it's a verilator bug.
