### ISSUE TITLE
wrong config header in configure.ac

### ISSUE THREAD

**Issue by amiloradovsky** [verilator/verilator#4380]
When running `autoreconf`, `src/config_build.h.in` gets overwritten by `autoheader` with an unrelated config header, because `src/config_build.h` is in `AC_CONFIG_HEADERS`.
Found while updating Nixpkgs (NixOS) package for v5.012.

https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.71/html_node/Configuration-Headers.html

**Comment by wsnyder** [comment]
Thanks for fixing this.
