### ISSUE TITLE
Is verilator capable of accessing memory content using VPI interface? 

### ISSUE THREAD

**Issue by yulong-lan** [verilator/verilator#4383]
I am trying to access the memory at any location I want, meaning I want to provide the address, and have the memory value at that address returned.

In brief, the hierarchy of the design is as shown in this VPI handle declaration: 
```
`vpiHandle vh1 = vpi_handle_by_name("TOP.ariane_testharness.i_sram.i_tc_sram_wrapper.i_tc_sram.sram", NULL); 
if (!vh1) vl_fatal(FILE, LINE, "ariane_testharness", "No handle found");`
```

And the memory model "sram" is only a one-dimentioanl array: 
```
parameter type         data_t    = logic [DataWidth-1:0],
data_t sram [NumWords-1:0]/*verilator public_flat_rd*/;
```
But I only gets this error and warning message: "No handle found", which indicates that the handle is simply not created.

Does verilator support this VPI feature, or am I using it wrong?

**Comment by wsnyder** [comment]
Verilator supports this.  Probably the item isn't at the hierarchical name you think it is.  Call Verilated::scopesDump() in your C++ code to see what the hierarchy is.
