### ISSUE TITLE
CMake verilate() function in different directory than target requires CMP0079

### ISSUE THREAD

**Issue by nickelpro** [verilator/verilator#4389]
[CMP0079](https://cmake.org/cmake/help/latest/policy/CMP0079.html) allows linking libraries from directories other than the one where the given target was created and was introduced in CMake 3.13.

The current verilator-config.cmake sets the version to CMake 3.12, so this policy is set to `OLD` and calling `verilate(FST_TRACE)` from a subdirectory results in:

```
CMake Error at /usr/share/verilator/verilator-config.cmake:338 (target_link_libraries):
  Attempt to add link library "-lz" to target "tests" which is not built in
  this directory.

  This is allowed only when policy CMP0079 is set to NEW.
```

CMake 3.13 is five years old, and building verilator at all requires CMake 3.15, so bumping up a single minor version in the config script should be safe.

**Comment by wsnyder** [comment]
Thanks for the pull. I have a bit of concern about older distros, but those using cmake tend to be relatively up-to-date, so we'll hope this works out ok.
