### ISSUE TITLE
Error while running verilator with --timing option

### ISSUE THREAD

**Issue by needhnlxf** [verilator/verilator#4392]
Hi,
I am facing an error when I use --timing:
g++: error: unrecognized command-line option ‘-mno-cet’; did you mean ‘-mno-aes’?
Could you please let me know how to resolve this?
(verilator version: Verilator 5.013 devel rev v5.012-58-g5a694cc)
(gcc version: gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11))

**Comment by wsnyder** [comment]
Compiler flags are all tested when you ./configure the Verilator package, so that this is broken means a different compiler was used for configure and when you got the error.  Please get the git tree, do that, rebuild verilator, and you should be good.
