### ISSUE TITLE
verilator_coverage does not sum line hit count over coverage reports

### ISSUE THREAD

**Issue by astoeckel-abr** [verilator/verilator#4439]
First of all, thank you for your work on Verilator!

Starting with commit https://github.com/verilator/verilator/commit/b778784333ba0dda0f13141c5b68db9a11e98509 (related to #3876), `VlcSourceCount::incCount` no longer increments the line hit count, but computes the minimum over all hit counts instead:
```
m_count = std::min(m_count, count);
if (!ok) m_ok = false;
```
(See https://github.com/verilator/verilator/commit/b778784333ba0dda0f13141c5b68db9a11e98509#diff-fd6a0121ce287e5d29c7c66320119c31074285af2b21861f18f185274a291661R56-R64)

I'm sure there was a good reason why this was changed, but in my usage scenario where I'd like to compute the summed coverage over multiple tests, I'm now getting incorrect results. Specifically, in my use-case individual tests test different parts of the design, so the minimum hit count for many lines ends up incorrectly being set to zero.

I'm using the following patch to fix this behaviour in our internal Verilator build:
```diff
diff --git a/src/VlcSource.h b/src/VlcSource.h
index 788945787..6b87dd811 100644
--- a/src/VlcSource.h
+++ b/src/VlcSource.h
@@ -58,7 +58,7 @@ public:
             m_count = count;
             m_ok = ok;
         } else {
-            m_count = std::min(m_count, count);
+            m_count += count;
             if (!ok) m_ok = false;
         }
     }
-- 
```

If this is intended behavior, then feel free to ignore this issue; though, in that case the naming of the `incCount` function may be a little misleading.

**Comment by wsnyder** [comment]
The intent of the change was that multiple *different* coverage points on the same line should reflect the coverage that is the minimum across different points.  It is wrong to consider different points as additive.

For your use case you should be merging coverage, like is done in the t_vlcov_merge.pl test.  That test seems to correctly check that we add up the coverage between different files.

Or, perhaps I'm misunderstanding your use case and there is still something wrong?

**Comment by wsnyder** [comment]
If you'd like to submit a pull request to add a new verilator_coverage option to add rather than min, that would be fine. Please remember to add a test - you can see what to add by temporarily making the new option the default and seeing what tests fail.

Closing as we'll either get a pull request or not ;)
