### ISSUE TITLE
Enumerated type variable .name() method causes lifetime unknown Internal Error

### ISSUE THREAD

**Issue by jwoutersymatra** [verilator/verilator#4448]
In the example below, an "Interval Error V3Fork.cpp:194: Variable's lifetime is unknown" is triggered when using the .name() method of an enum to render it as a string. Printing the enum as an integer is OK (see commented line in example).

I tried a bunch of things as mentioned in the manual like making a local copy, but it seems that the call to .name() is the issue.

Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)

```
module enum_lifetime_bug;

typedef enum {PWR_DC, PWR_SQUARE_WAVE} e_pwr_profile;

e_pwr_profile     pwr_profile = PWR_DC;
real cap_voltage = 0.0;
real pwr_dut     = 0.0;

initial begin: POWER_PROFILE

  while(1) begin
    pwr_dut = 0.0;
    wait(cap_voltage >= 3.3);
    fork
      begin
        wait(cap_voltage <= 2.0);
        $display("Warning undervoltage (%0t)", $time);
      end
      begin
        case (pwr_profile)
          PWR_DC: begin
            forever begin
              pwr_dut = 0.1;
              #1ms;
            end
          end

          PWR_SQUARE_WAVE: begin
            forever begin
              #5ms;
              pwr_dut  = 0.01;
              #5ms;
              pwr_dut  = 0.05;
            end
          end

          default: begin
            //$error("pwr_profile %0d not supported", pwr_profile);
            $error("pwr_profile %s not supported", pwr_profile.name()); // <-- .name() causes lifetime error
          end
        endcase
      end
    join_any
    pwr_dut    = 0.0;
  end
end


initial begin
  repeat(100) begin
    #1us;
    cap_voltage += 0.1;
  end
  $finish;
end

endmodule

```
What 'verilator --version' are you using?  Did you try it with the git master version?

Verilator 5.014 2023-08-06

What OS and distribution are you using?

Ubuntu under windows WSL2

May we assist you in trying to fix this in Verilator yourself?

**Comment by wsnyder** [comment]
Fixed, thanks for the straightforward test case.
