### ISSUE TITLE
Support UVM delayed assignment inside public function/task

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#4496]
UVM has this:

```
task uvm_wait_for_nba_region;
  int nba;
  int next_nba;
  next_nba++;
  //vvvv -- %Error-UNSUPPORTED: t/t_uvm_pkg_todo.vh:875:7: Unsupported: Delayed assignment inside public function/task
  nba <= next_nba;
  @(nba);
endtask
```

This blocks UVM post-elaboration.  Despite the message the function isn't public, it's because it (probably correctly) couldn't inline.

**Comment by kbieganski** [comment]
Is there a reason we don't allow NBAs in non-inlined functions? Or is it okay to just limit the check to actual public functions?

**Comment by wsnyder** [comment]
>Is there a reason we don't allow NBAs in non-inlined functions? Or is it okay to just limit the check to actual public functions?

Before --timing it would not be able to properly schedule the old/new version of the variable.

I think that's still true, but feel free to write a test to check it works correctly with --timing.
