### ISSUE TITLE
Multi-core support in Verilator

### ISSUE THREAD

**Issue by jordankrim** [verilator/verilator#4525]
I'm using Verilator to run a test and it fails but passes with an EDA simulator. The reason for the failure is not certain, as it can possibly be the generated Verilator test harness or my design multi-core harness.

The only reference to multi-core I found in the Verilator documentation is in the section on Hierarchical Verilation which seems to only address the length of time required to Verilate a design.   

If there is multi-core support in Verilator and I am not using it correctly, I would really like to know how does one invoke/use it?

**Comment by wsnyder** [comment]
See the documentation, e.g. here https://veripool.org/guide/latest/verilating.html#multithreading
