### ISSUE TITLE
Extent to which UVM is supported

### ISSUE THREAD

**Issue by arshadrohan5** [verilator/verilator#4534]
Is support for UVM enabled currently? I faced a PKGNODECL error while Verilating a simple UVM testbench. Screenshots are attached.
![image](https://github.com/verilator/verilator/assets/84508750/6f8a30e1-1395-4570-aa4c-3c0de98b04d8)

**Comment by wsnyder** [comment]
Not yet, see #1538

**Comment by arshadrohan5** [comment]
How can I get started on adding support for UVM? What are the technical prerequisites that I should be aware of to initiate my contributions to Verilator effectively?

**Comment by wsnyder** [comment]
We'd love help!  If you look through the sub issues described in #1538, and see which you'd like to contribute to, then post in that sub issue your intent, then we'll give some pointers.   (Many also have good starting points, just need more work to complete.)
