### ISSUE TITLE
Fix regression in class object destruction

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#4540]
@RRozak #4533 a3c154dcd3fb0ec4768eaa3be2c3dd7b648376b3 has caused a regression in several ivtests (run under sv-test framework)

https://github.com/steveicarus/ivtest/blob/master/ivltests/sv_class13.v
https://github.com/steveicarus/ivtest/blob/master/ivltests/sv_class14.v
https://github.com/steveicarus/ivtest/blob/master/ivltests/sv_class17.v
https://github.com/steveicarus/ivtest/blob/master/ivltests/sv_class18.v

These now core dump on destruction.  Could you take a look please?   Also please convert at least one of the tests above into a test_regress form to catch these in the future.  Thanks!

**Comment by RRozak** [comment]
The problem occurs when an object created by a copy constructor is used at least two times. In #4533 I didn't add a ref counter incrementation to the copy constructor. After the first object reference, the counter is set back to 0 and the object is deleted. The 2nd use gives seg fault.
I created PR with a fix.
