### ISSUE TITLE
Making .vcd files easier to read in gtkwave w.r.t. modifying signals on falling edge

### ISSUE THREAD

**Issue by oharboe** [verilator/verilator#4550]
Is there a way to tell Verilator to output .vcd files that don't show signals changing on the falling edge?

Use-case: although the Chisel test framework modifies the top level inputs of the device under test on the falling edge for technical reasons, I would prefer to have the .vcd file with signals only changing on the rising edge. Signals only changing on the rising edge of the clock is what I would see in the depths of the design where signals only change as the result of a flip-flop changing. Signals changing at the falling edge at the top level is an artifact of using a simulator.

If I understand correctly, Chisel *could* call eval() three times: to create rising edge, modify inputs for DUT, falling edge. However, this increases simulation times by 50% (assuning all eval() invocations take the same amount of time).

Chisel does invoke eval(), near as I can tell, every time one of the DUT top level inputs are changed, however this happens on the falling edge. This is done so that combinational logic can be tested without stepping the clock. I am unsure if Chisel *could* call eval() multiple times(every time the input changes) while the clock is high, but I assume that this was considered, but not done for some reason I don't understand...

Example: The upper trace is harder to read than the lower trace...

![image](https://github.com/verilator/verilator/assets/2798822/36866724-e29c-48d3-8391-ec1f05e89767)

From a discussion on the topic: https://groups.google.com/g/chisel-users/c/fDgMbbkGC0c/m/aEAlXUr2AwAJ

Also see this github issue: https://github.com/ucb-bar/chiseltest/issues/646

Here is a script that does the post-processing so that signals only change on the rising edge of the clock:

```python
#!/usr/bin/python3

import os
import sys

default_output_suffix = "-fixed"

def usage():
    print(f'USAGE: {os.path.basename(__file__)} <input.vcd> [output.vcd]')
    print(f'  output file arg is optional; if omitted, output will be written to <input{default_output_suffix}.vcd>.')
    print()

def main():
    if len(sys.argv) != 2 and len(sys.argv) != 3:
        usage()
        raise Exception('Invalid arguments')
    
    input_file_name = sys.argv[1]
    output_file_name = sys.argv[2] if len(sys.argv) == 3 else os.path.splitext(input_file_name)[0] + default_output_suffix + os.path.splitext(input_file_name)[1]

    with open(input_file_name) as input:
        with open(output_file_name, 'w') as output:
            # Find top-level clock var identifier in hierarchy defs
            #  Note: We assume that the first clock definition is the top-level one
            clock_name = 'clock'
            clock_id = ''
            while line := input.readline():
                output.write(line)
                line = line.strip()
                if line.startswith('$var'):
                    var_parts = line.split()
                    assert(len(var_parts) == 6)
                    var_name = var_parts[4]
                    if var_name == clock_name:
                        assert(var_parts[1] == 'wire')
                        assert(var_parts[2] == '1')
                        assert(var_parts[5] == '$end')
                        clock_id = var_parts[3]
                        break
                if line.startswith('$enddefinitions'):
                    raise Exception('Could find clock var')
            enddefinitions_found = False
            while line := input.readline():
                output.write(line)
                if line.startswith('$enddefinitions'):
                    enddefinitions_found = True
                    break
            if not enddefinitions_found:
                raise Exception('Could not find $enddefinitions')
            #print(f'clock id: {clock_id}')

            def is_binary_change(change):
                return change.startswith('0') or change.startswith('1')

            def is_clock_change(change):
                nonlocal clock_id
                return is_binary_change(change) and change[1:].strip() == clock_id

            # Process changes by timestamp
            class Changes():
                def __init__(self, timestamp):
                    self.timestamp = timestamp
                    self.changes = []

                def output(self):
                    if any(is_clock_change(change) and change.startswith('0') for change in self.changes):
                        # If this set of changes has a falling clock edge, output all
                        #  non-clock changes before the timestamp so that they will
                        #  correspond to the most recent rising clock edge instead.
                        for change in self.changes:
                            if is_clock_change(change):
                                continue
                            output.write(change)
                        output.write(f'#{self.timestamp}\n')
                        for change in self.changes:
                            if not is_clock_change(change):
                                continue
                            output.write(change)
                    else:
                        # Otherwise, output changes as they appeared in the input.
                        output.write(f'#{self.timestamp}\n')
                        for change in self.changes:
                            output.write(change)

            current_changes = None

            while line := input.readline():
                if line.isspace():
                    continue

                # Skip $dumpvars, if any
                if line.startswith('$dumpvars'):
                    output.write(line)
                    end_found = False
                    while line := input.readline():
                        output.write(line)
                        if line.startswith('$end'):
                            end_found = True
                            break
                    if not end_found:
                        raise Exception('Could not find $end for $dumpvars')
                    continue

                if line.startswith('#'):
                    if current_changes:
                        current_changes.output()
                    timestamp = int(line.replace('#', ''))
                    current_changes = Changes(timestamp)
                    continue

                current_changes.changes.append(line)

            if current_changes:
                current_changes.output()

if __name__ == '__main__':
    main()
```

**Comment by wsnyder** [comment]
>Is there a way to tell Verilator to output .vcd files that don't show signals changing on the falling edge?

No, and I'd prefer not to have waves represent other than reality (as Verilator sees it anyways).

But as described in the chisel threads they could apply inputs one delta cycle after the clock posedge, that is call Verilator as:

     clk = 1
     eval()  // posedge
     apply_inputs
     eval()  // see inputs
     advance_time();
     clk = 0
     eval()  // negedge
     advance_time();
     
This will be slightly slower but not much, and will also work if you are modeling e.g. DDR or something with logic at both posedge and negedges.

Thanks for the cleanup script.

Closing as answered. Feel free to followup or reopen if there's something specifically doable by Verilator to help this.

**Comment by oharboe** [comment]
@wsnyder Makes sense. Thanks for the prompt reply and clarification! Clarifying this is half the solution. I will try to work with the Chisel test maintainers to see if there is a reason why this solution can't be applied.
