### ISSUE TITLE
Fix variable resolution in some packages broken in 5126689

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#4605]
https://github.com/verilator/verilator/commit/51266898ec495196eb8187314bd3d96fdfc62dd8 introduces a failure on an old version of OpenTitan I'm using.

Unfortunately I don't have time to make a smaller case, so I tarred up my sources. To reproduce, run `verilator -f options.f` in the archive directory
[titan.tar.gz](https://github.com/verilator/verilator/files/13061894/titan.tar.gz)

Reverting the change to `AstNode::sameTreeIter` here is a fix:

https://github.com/verilator/verilator/commit/51266898ec495196eb8187314bd3d96fdfc62dd8#diff-e906e55f643fad56cc33abbacd2ffe7aa795a2fce460389336d160a1d7a4c5eaL1085

@RRozak would you mind attempting a more proper fix?

**Comment by gezalore** [comment]
Note: GDB suggested an AstNodeVarRef to a variable inside a package does not have `classOrPackagep` set, but I don't see how that is related to the patch that introduced this...

**Comment by RRozak** [comment]
I will look into it, but unfortunately not in the next few days.

**Comment by gezalore** [comment]
Appreciate it regardless

**Comment by RRozak** [comment]
I fixed it: https://github.com/verilator/verilator/pull/4723.
As you said, the problem was with `classOrPackagep` field.
The revert helped, because due to it, an additional variable was added, which was passed to a port instead of the original value defined in a package.

**Comment by gezalore** [comment]
Thanks again for tracking this down
