### ISSUE TITLE
Include <systemc> instead of <systemc.h> in model's header file

### ISSUE THREAD

**Issue by PkmX** [verilator/verilator#4622]
#4127 previously fixed the use of `systemc.h` in Verilator's common headers, but the generated model header file still includes `systemc.h` which pollutes the global namespace. It should instead use `#include <systemc>` and generate fully qualified names for SystemC's data types.

To reproduce, simply modify `examples/make_hello_sc/sc_main.cpp` to use `cout` unqualified.

**Comment by wsnyder** [comment]
Could you submit a pull request to fix this?

**Comment by wsnyder** [comment]
Thanks for contributing this.
