### ISSUE TITLE
Uninitialized used variables in V3Fork

### ISSUE THREAD

**Issue by gezalore** [verilator/verilator#4636]
I think this is another one for you @kboronski-ant please. These variables are uninitialized but used:
https://github.com/verilator/verilator/blob/a5951babfc2687b42c495406a8d2afe31eb84661/src/V3Fork.cpp#L273-L274

Output is still not deterministic because of these I think (see #4635 if it helps)

**Comment by wsnyder** [comment]
I think in nearly all cases AstNodeModule will reset the variable, but I added an init.
