### ISSUE TITLE
VL_SHIFTL_III not supported

### ISSUE THREAD

**Issue by mbalboni07** [verilator/verilator#4647]
v5.016
Code generated is creating code that is failing compiling due to this error:

`error: use of undeclared identifier 'VL_SHIFTL_III'`

VL_SHIFTL_III is not present indeed in the possible choices

**Comment by wsnyder** [comment]
It's defined in verilated_funcs.h, you are perhaps using a newer Verilator with an older set of includes?

**Comment by mbalboni07** [comment]
Thanks for the quick answer. I will check it tomorrow morning and report back here

**Comment by wsnyder** [comment]
Didn't hear back, but pretty sure will work, feel free to comment here otherwise.
