### ISSUE TITLE
Issue with some SystemC datatypes

### ISSUE THREAD

**Issue by mbalboni07** [verilator/verilator#4648]
v5.016

Generated code is failing at compilation time due to this error

`error: cannot pass object of non-trivial type 'sc_core::sc_out<sc_dt::sc_uint<64>>' through variadic function; call will abort at runtime [-Wnon-pod-varargs]`

**Comment by wsnyder** [comment]
Did this used to work for you?  I suspect not and you're trying to hook a sc_uint<64> to a verilated port - verilator uses uint64_t.

**Comment by mbalboni07** [comment]
Super thanks again for the quick answer. I was verilating same code with v4.226 and it was working. Do you know if something could have changed about support of systemc in the newest releases?
Big thanks in advance

**Comment by wsnyder** [comment]
That was over a year ago, a lot has changed.

**Comment by wsnyder** [comment]
Closing presuming you figured this out, feel free to follow up here if otherwise.
