### ISSUE TITLE
Invalid Option: --binary

### ISSUE THREAD

**Issue by justincdas** [verilator/verilator#4653]
I am getting the following issue, How can I resolve it?

/india/tools/verilator/verilator-5.016/bin/verilator --binary --top-module testrunner -f .svunit.f 
%Error: Invalid Option: --binary
%Error: Command Failed ulimit -s unlimited 2>/dev/null; exec /india/tools/verilator/verilator-5.016/bin/verilator_bin --binary --top-module testrunner -f .svunit.f

**Comment by wsnyder** [comment]
If you run "verilator --version" you'll see you are running an old version of the binary that the wrapper you call is running. Your VERILATOR_ROOT or VERILATOR_BIN or otherwise is pointing to the wrong place.

**Comment by wsnyder** [comment]
P.S. See those with "printenv | grep VERILATOR"

**Comment by justincdas** [comment]
Thanks for the reply, 
justinc@osvnc001 /~ % which verilator
/india/tools/verilator/verilator-5.014/bin/verilator
justinc@osvnc001 /~ % verilator --version
Verilator 4.014 2019-05-08 rev UNKNOWN_REV

Somehow on version query, it is showing old version. And the env vars VERILATOR_ROOT and VERILATOR_BIN are not defined.
I will check what went wrong in the installation.
