### ISSUE TITLE
configure finds SystemC, but then the build doesn't link with libsystemc.so

### ISSUE THREAD

**Issue by yurivict** [verilator/verilator#4656]
configure prints:
```
checking whether SystemC is found (in system path)... yes
```

Then the string 'systemc' never appears in any compile or link command lines.

Then the FreeBSD port's framework prints this warning:
> Warning: you might not need LIB_DEPENDS on libsystemc.so

which is correct because binaries aren't linked with libsystemc.so

(Previously there was an unrelated configure's failure to find SystemC.)

**Comment by wsnyder** [comment]
Verilator on discovering -lsystemc in configure will add it to SC_LIBS in include/verialted.mk. Verilator only uses SC_LIBS when you verilate with --sc (VM_SC=1).  So if you are getting it you are likely adding it somewhere in your environment or makefile, please check.  Alternatively, I would suggest turning off linker warnings.

Closing as think that should answer it, but feel free to follow up here.
