### ISSUE TITLE
Incorrect simulation of flip-flop after latch

### ISSUE THREAD

**Issue by atorregrosa-smd** [verilator/verilator#4666]
There seem to be some issues when simulating a latch that feeds a flop that samples the signal on the same edge the latch becomes transparent. The flip-flop seems to be sampling the signal on the same edge it starts to be generated, and I would expect it to sample the previous value. The issue seems to be present in both verilator `5.016` and `5.018`.

Waves example: flop_ff follows flop_n. I would expect it to show the value on the next cycle.
![waves](https://github.com/verilator/verilator/assets/78434679/3c2ae7ab-69af-4c73-a252-7bd3343e1aae)

I have attached a [small testcase](https://github.com/verilator/verilator/files/13251859/test.txt) that reproduces the issue. It simulates as expected on VCS & Questa.

I'm not entirely sure what is the correct behavior for this. If the line with the `always_comb` is replaced by an assignment with no addition logic, the test fails on all simulators.

**Comment by wsnyder** [comment]
A simulator is allowed to choose arbitrary arrangement of processes. That always_comb and assign give different results suggest you're in trouble territory, though I'm not sure if this is strictly legal or not.  Anyhow for performance reasons we're very unlikely to change the behavior of Verilator to make this ordering of processes race-free.
