### ISSUE TITLE
UNOPTFLAT errors (after warnings)

### ISSUE THREAD

**Issue by jordankrim** [verilator/verilator#4702]
I am getting errors:

...
%Warning-UNOPTFLAT: rtl/divfunc.v:43:23: Signal unoptimizable: Feedback to clock or circular logic: 'modexp.core_inst.divfunc_inst.ready'
   43 |     reg               ready    [(XLEN+1)-1:0];
      |                       ^~~~~
                    rtl/divfunc.v:43:23:      Example path: modexp.core_inst.divfunc_inst.ready
                    rtl/divfunc.v:85:17:      Example path: ALWAYS
                    rtl/divfunc.v:43:23:      Example path: modexp.core_inst.divfunc_inst.ready
%Error: Exiting due to 5 warning(s)

First, why does it exit after these 5 type of warnings (not errors)?  Second, I tried using both the /* verilator_split_var */ and a config file with it, but it didn't seem to work.  I am wondering if it's because I am using version 4.226.  If it is, and I want to update to 5.010 (or the latest), what version of distro should I download and install for Red Hat Enterprise Linux version 8.8?

Thanks,
Jordan Krim

**Comment by wsnyder** [comment]
Verilator always exits after warnings unless you give -Wno-fatal. As described in the documentation, it is usually fine to suppress this warning.

Upgrading they might not go awa,y but you certainly should be using a much newer version. You might as well use the last release (built from sources).
