### ISSUE TITLE
Help needed with failing "make test"

### ISSUE THREAD

**Issue by jordankrim** [verilator/verilator#4711]
I compiled Verilator on RHE 8.8 but when I run "make test", it fails with this:

...
test_regress/t/t_a1_first_cc.pl
======================================================================
dist/t_a1_first_cc: ==================================================
dist/t_a1_first_cc: -Skip: Skip: scenario 'dist' not enabled for test
======================================================================
vlt/t_a1_first_cc: ==================================================
	perl ../bin/verilator --debug --debugi 0 --gdbbt --no-dump-tree -V
warning: File "/home/jkrim/verilator/test_regress/.gdbinit" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
No stack.
**BFD: /home/jkrim/verilator/bin/verilator_bin_dbg: unable to initialize decompress status for section .debug_aranges
BFD: /home/jkrim/verilator/bin/verilator_bin_dbg: unable to initialize decompress status for section .debug_aranges
"/home/jkrim/verilator/test_regress/../bin/verilator_bin_dbg": not in executable format: file format not recognized**

It runs fine on an Oracle VM Box under Windows 10, so I am not sure what is wrong on RHE.

**Comment by gezalore** [comment]
Looks like some issue with compressed debug info, please remove the "-gz" compiler flag from configure.ac then rebuild and retest.

**Comment by jordankrim** [comment]
Thank you.  That appeared to work.  Is there any problem with eliminating the -gz with regards to Verilator working correctly?

**Comment by gezalore** [comment]
It's just the format of the debug info for Verilator itswlf, which your toolchain seems to be having an issue with. It makes no difference to usage.
