### ISSUE TITLE
How to increase DETECTARRAY_MAX_INDEXES ?

### ISSUE THREAD

**Issue by jordankrim** [verilator/verilator#4752]
I am seeing this:

%Error-DETECTARRAY: rtl/divfunc.v:48:27: Unsupported: Can't detect more than 256 array indexes (probably with UNOPTFLAT warning suppressed): modexp.core_inst.divfunc_inst.quotient
                                       : ... Could recompile with DETECTARRAY_MAX_INDEXES increased
48 |     reg [(XLEN)-1:0]      quotient [(XLEN+1)-1:0]; 

I can't seem to find in the documentation how to compile with this increase.

**Comment by wsnyder** [comment]
There hasn't been a DETECTARRAY for 8 years, please use a newer version.

**Comment by jordankrim** [comment]
I moved to:
Verilator 5.019 devel rev v5.018-44-gb8417abee
The sim is very slow to start as I am creating 2 very large "memories" (?), but eventually even though looking at the waves the simulation *seems* to be progressing, it terminates with this:

%Error: rtl/modexp.v:60: Active region did not converge.
Aborting...
make: *** [Makefile:66: vcd] Aborted (core dumped)

**Comment by wsnyder** [comment]
Is there some strange # delay or activation or something on your memory array?  See if you can rewrite it as normal behavioral code.

**Comment by jordankrim** [comment]
There is no # delay on the memory array and as far as I can tell, it is normal behavior code albeit it has a (huge) genvar with some macros defining the reset behavior.

**Comment by gezalore** [comment]
If you think this should terminate please increase the --converge-limit option, if that helps also consider the split_var attribute.
