### ISSUE TITLE
Tracing ports/signals from a Verilated code and from a pure SystemC block

### ISSUE THREAD

**Issue by mbalboni07** [verilator/verilator#4758]
Hello,
this is mostly a question. If I have a SystemC project that is instantiating in the sc_main the systemc wrapper for verilated code and another pure SystemC block, is there a way to add traces from both?
I am using VerilatedVcdSc* trace_file and collecting there the traces from the verilated part (perfectly working).
But how can I add the traces from SystemC block to the same file?
Is there an example somewhere?

Thanks in advance.

**Comment by wsnyder** [comment]
You need to create a separate SystemC-only trace file, then in your waveform viewer open both separate files.
