### ISSUE TITLE
does verilator handle generate optionality correctly?

### ISSUE THREAD

**Issue by solomatnikov** [verilator/verilator#4766]
It looks like the result differs if `generate` is omitted:

https://github.com/openhwgroup/cvw/issues/520#issuecomment-1857211880

https://github.com/openhwgroup/cvw/issues/520#issuecomment-1857221195

From https://github.com/openhwgroup/cvw/issues/520#issuecomment-1857812142

> The generate keyword is supposed to be optional. According to IEEE_Std1800-2017 at page 786:
> 
> > The keywords generate and endgenerate may be used in a module to define a generate region. A generate region is a textual span in the module description where generate constructs may appear. Use of generate regions is optional. There is no semantic difference in the module when a generate region is used. A parser may choose to recognize the generate region to produce different error messages for misused generate construct keywords. Generate regions do not nest, and they may only occur directly within a module. If the generate keyword is used, it shall be matched by an endgenerate keyword.
> 
> Nevertheless, there could be a bug in Verilator such that it wants the generate keyword.

**Comment by wsnyder** [comment]
From those other bugs I don't see how the conclusion about generate/endgenerate was reached; what was added were "generate if" statements - the important part being the "if" not the "generate".  Verilator should be fully IEEE compatible as to generates.  If you can create a standalone example where there is a difference between using generate or standalone if, etc, please attach here and reopen.
