### ISSUE TITLE
Support SystemC 3.0.0 draft

### ISSUE THREAD

**Issue by maveric2** [verilator/verilator#4805]
verilated_vcd_sc.h:46:35: fatal error: no member named 'add_trace_file' in 'sc_core::sc_simcontext'
        sc_get_curr_simcontext()->add_trace_file(this);

**Comment by wsnyder** [comment]
[System 3.0.0](https://github.com/accellera-official/systemc/releases/tag/3.0.0_pub_rev_20231129) is only in draft review, as you probably know.  Could you please consider making a pull request to Verilator (and/or SystemC itself as now is the time) to support it?

**Comment by donlon** [comment]
It seems that SystemC 3.0.0 remove phase callback and trace file related APIs, which Verilator's tracing function depends on currently. Instead the new version uses the new stage callback API to provide callbacks. I can fix it later quickly.
