### ISSUE TITLE
Parallel verilation in hierarchical mode 

### ISSUE THREAD

**Issue by futurehome** [verilator/verilator#4813]
What would you like added/supported?

The design is large, so I use hierarchical mode for verilation, because there are a lot of sub-modules, how to run the sub-modules in different sessions(Not just threads)? Looks like it will execute all the V*_hierMkArgs.f one by one.

**Comment by futurehome** [comment]
For 1, I think it's because the V*_hierMkArgs.f are always update when re-running  verilator.

**Comment by wsnyder** [comment]
Can you explain more about what you mean by executing in different sessions?

**Comment by futurehome** [comment]
I mean all the V*_hierMkargs.f can be executed in parallel.

**Comment by futurehome** [comment]
BTW, because my design is extremely large, it takes several hours to verilate the whole design. But in hierarchical mode, there are several limitations, like no trace support, etc. Do you have plan to support trace for hierarchical mode?

**Comment by wsnyder** [comment]
There are several open issues on hierarchical.  AFAIK there's no one actively fixing these so they are likely to be open for a long time.  We'd welcome your or others' work on them; feel free to post to the issues that you'd like to work on.
