### ISSUE TITLE
Access and set struct port value of top design

### ISSUE THREAD

**Issue by ckf104** [verilator/verilator#4816]
Hi ! I have a design like
```systemverilog
  typedef struct packed {
    logic[2:0]           a;
    logic[2:0]           b;
    logic[2:0]           c;
  } struct_t;

module Top(
  input  struct_t        context_i
);
 //
endmodule
```

I expect that I can access signal in C++ like
```c++
VTop->context_i.a = xxx;
```
But it seems that verilator don't reserve such struct info in verilated c++ model.
Is any option can help or verilator don't support this?

**Comment by wsnyder** [comment]
C++ doesn't have a way to do this cleanly, especially without also breaking accessing the packed struct as a whole.
However, Verilator could create a structure that you can cast to inorder to do the decoding/encoding. This is already covered by #860; if you would like to contribute that improvement please comment there.
