### ISSUE TITLE
Unrecognized argument error while building Verilator from git 

### ISSUE THREAD

**Issue by Shreesh-Kulkarni** [verilator/verilator#4823]
![image](https://github.com/verilator/verilator/assets/78203773/26e7e42e-025a-4533-838b-ae76e3d53e2e)

I came across this error while building verilator from git master. I followed the documentation for installation steps.
I could have used the package manager version, but for my specific project, the version from the package manager install isn't supported. Hence, the git master version is suitable.

I am running the build on WSL2 with Ubuntu 20.04 LTS.

I would appreciate any suggestions to fix this error myself, so that I can contribute for the same.

**Comment by wsnyder** [comment]
Either upgrade "bear" to >= version 3.0, or unistall bear, or use

`make BEAR=`

Closing as this should solve it but feel free to followup here.

P.S. in future please avoid screenshots and post text, or convert screenshot to text with OCR. Thanks.

**Comment by Shreesh-Kulkarni** [comment]
Thanks! I'll keep it in mind to use text instead next time.
