### ISSUE TITLE
Help with secret decoder ring for sanitize

### ISSUE THREAD

**Issue by jordankrim** [verilator/verilator#4843]
I am attempting to debug a problem with my simulation that just exits before completion -- no error,  seg fault and looking at the waves it appears to be running fine.  I have looked for a timeout in my code but can't seem to find it.    I decided to try the Verilator sanitize option, but I don't know the secret decoder ring to find where in my source code the problem is.  Here is the last print before the sim quits:

=================================================================
==1563769==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 65536 byte(s) in 1 object(s) allocated from:
    #0 0x7fb543e2a216 in operator new[](unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:98
    #1 0x562d12c50a71 in context_t::init(void (*)(void*), void*) ../fesvr/context.cc:53

Direct leak of 264 byte(s) in 1 object(s) allocated from:
    #0 0x7fb543e2a11b in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x562d1062dca3 in memory_init (/mnt/data/projects/project/jkrim/CEP-Setup/cep_v4_4_test_verilator/CEP/sims/verilator/simulator-chipyard-CEPVerilatorRocketConfig+0xe7eaca3)
    #2 0x7fffb65e7a7f  ([stack]+0x1ea7f)

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0x7fb543e2a11b in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x562d10630db0 in std::_Deque_base<unsigned long, std::allocator<unsigned long> >::_M_initialize_map(unsigned long) (/mnt/data/projects/project/jkrim/CEP-Setup/cep_v4_4_test_verilator/CEP/sims/verilator/simulator-chipyard-CEPVerilatorRocketConfig+0xe7eddb0)

Indirect leak of 480 byte(s) in 1 object(s) allocated from:
    #0 0x7fb543e2a11b in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x562d10645cc2 in void std::deque<mm_rresp_t, std::allocator<mm_rresp_t> >::_M_push_back_aux<mm_rresp_t>(mm_rresp_t&&) (/mnt/data/projects/project/jkrim/CEP-Setup/cep_v4_4_test_verilator/CEP/sims/verilator/simulator-chipyard-CEPVerilatorRocketConfig+0xe802cc2)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fb543e2a11b in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x562d10631bfc in std::_Deque_base<mm_rresp_t, std::allocator<mm_rresp_t> >::_M_initialize_map(unsigned long) (/mnt/data/projects/project/jkrim/CEP-Setup/cep_v4_4_test_verilator/CEP/sims/verilator/simulator-chipyard-CEPVerilatorRocketConfig+0xe7eebfc)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7fb543e2a11b in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x562d10630be6 in std::_Deque_base<unsigned long, std::allocator<unsigned long> >::_M_initialize_map(unsigned long) (/mnt/data/projects/project/jkrim/CEP-Setup/cep_v4_4_test_verilator/CEP/sims/verilator/simulator-chipyard-CEPVerilatorRocketConfig+0xe7edbe6)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7fb543e2a11b in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x562d106412a1 in std::vector<char, std::allocator<char> >::_M_default_append(unsigned long) (/mnt/data/projects/project/jkrim/CEP-Setup/cep_v4_4_test_verilator/CEP/sims/verilator/simulator-chipyard-CEPVerilatorRocketConfig+0xe7fe2a1)

SUMMARY: AddressSanitizer: 66928 byte(s) leaked in 7 allocation(s).

**Comment by wsnyder** [comment]
Those are just memory leaks.  While not ideal from a memory management standpoint they can be ignored as are harmless.  If your code died (later though not seen in what you attached) it would be for different reasons than these leaks.

As to finding code that corresponds to these, this is pointing inside VerilatorRocketConfig (etc) which is not part of Verilator or something Verilator makes.

Closing as answered but feel free to follow up here.
