### ISSUE TITLE
cannot open source file "verilated.h"

### ISSUE THREAD

**Issue by sanxzhar** [verilator/verilator#4845]
Ubuntu 22.04 installed on M2 macOS via UTM.

I have installed verilator via the `sudo apt install verilator` command. Everything went smoothly without any errors.

However when I tried to import header files such as verilated.h, I am receiving an error in my VS Code:
`cannot open the source file "verilated.h"`

My `c_cpp_properties.json` file:
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-arm64"
        }
    ],
    "version": 4
}
```

How I am importing headers: 
```
#include <verilated.h>
#include <verilated_vcd_c.h>
#include "Valu.h"
#include "Valu___024unit.h"
```

I believe someone has already encountered the same problem and could help me.

UPD: I was able to solve this issue by changing importPath in VScode. If you are meeting the same issue, I am here to help you.

**Comment by Tr4cck** [comment]
hey bro I think i meet the same problem, can you share your importPath?
