### ISSUE TITLE
Runtime value issue under some specific conditions

### ISSUE THREAD

**Issue by flaviens** [verilator/verilator#4864]
Hi there!

Thank you as always for your contributions and for taking the time for reading this issue!
[In this repository, I reduced for you a design in which I had runtime value issues](https://github.com/flaviens/verilator-b15). It is not in test_regress format (I'm not very familiar with it) but it seems to be easily transferable for someone knowledgeable.

The interesting thing is that the bug is extremely unstable: most minor alterations, even outside of the path from inputs to outputs, will clear the bug.

I tested it with `Verilator 5.021 devel rev v5.020-69-ge4a0e5aad`.

A timeline of what happens:
1. The little `always_ff` puts `'0` into `sig_b`.
2. The  input changes (which should not influence the output, but ignoring this step will clear the bug).
3. The bigger `always_ff` transmits the zero-value from `sig_b` through `sig_c` into `sig_e`.
So eventually, the output value should be `0`.
However, with some optimizations enabled (in some non-reduced case, I think it was the opposite), such as `-fno-subst -fno-subst-const`, the output value is `1`.

Please let me know if you have any question or require further info!

Kind regards,
Flavien

**Comment by wsnyder** [comment]
@yTakatsukasa this also goes away with only -fno-const-bit-op-tree

**Comment by flaviens** [comment]
Crazy, thank you for the fix! :heart:
