### ISSUE TITLE
Can I run verilator simulation with dynamically linked files?

### ISSUE THREAD

**Issue by NazerkeT** [verilator/verilator#4903]
Hi there, 

In my use case I wanted to test complex riscv cpp application that dynamically links multiple large header files in order to execute the main app. Earlier it was not possible with Spike simulator, so I was wondering whether it is possible with Verilator. 

Thanks,
Best wishes

**Comment by wsnyder** [comment]
I presume you mean use shared objects (your "header files" confuses me).  Verilator makes a C++ program, so you can make your own link command etc to load shared objects.
