### ISSUE TITLE
(BASIC) Anatomy of the verilator makefile...

### ISSUE THREAD

**Issue by space-devon** [verilator/verilator#4907]
Very basic question, but I am new to makefiles. I am using the helloworld makefile example to learn what needs to be used in order to generate the Verilator outputs. I am wondering if I have 4 levels in a hierarchy (top which calls mod1 which calls mod2 which calls mod3), do I need to (1) create the .cpp/__ALL.a files for each of those sublevels individually and then call them all together in the top level creation? Or do I (2) create them all individually, then on the top level call, just reference the top level .v file and it will know which submodules to call? Or (3), do I only need to create a .cpp/_ALL.a file for the top level, and then in the files to use for compilation include all the submodule .v files?

Option 1:
![image](https://github.com/verilator/verilator/assets/160534325/7b81526c-8595-42f3-a774-b1ec05e21a25)

Option 2:
![image](https://github.com/verilator/verilator/assets/160534325/7de992d7-427d-4d8e-b1fa-b2670f99a928)

Option 3:
![image](https://github.com/verilator/verilator/assets/160534325/349703df-92d9-4b53-bbec-52c0b3ef14f5)

**Comment by wsnyder** [comment]
Option 3. See e.g. examples/make_tracing_c/Makefile

Note that example uses -MMD in Makefile_obj, which will build only if source files change, which is useful.

Closing as answered but feel free to follow up here. Welcome.
