### ISSUE TITLE
Cygwin Win11 gives segmentation fault when running "make test"

### ISSUE THREAD

**Issue by Xocket** [verilator/verilator#4908]
Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)
Attached error.
[debug.txt](https://github.com/verilator/verilator/files/14338057/debug.txt)

What 'verilator' command line do we use to run your example?
"make test"

What 'verilator --version' are you using?  Did you try it with the git master version?
Stable version. I did try the master version too.

What OS and distribution are you using?
cygwin64 under Windows 11

I feel like I've tried everything and nothing works so far. I've used both the stable and latest version.

I'm a beginner so sorry if there's something obvious I'm missing. I don't know if it's a root problem, a configuration problem, something going wrong when executing make or what.

I feel like I should just give up and install it under WSL.

**Comment by wsnyder** [comment]
```
#0  ___chkstk_ms () at /usr/src/debug/gcc-11.4.0-1/libgcc/config/i386/cygwin.S:126
#1  0x00000000002af7a8 in ?? ()
#2  0x0000000a00015980 in ?? ()
#3  0x0000000100563070 in V3Stats::statsStageAll (nodep=0x7ffe036e8, stage=..., fastOnly=fastOnly@entry=false) at ../V3Stats.cpp:168
```

Seems like something went bad in the stack.  Unless you can debug further I'll need to install cygwin and debug, this may take a while.  Can you use WSL instead of Cygwin?

**Comment by Xocket** [comment]
> ```
> #0  ___chkstk_ms () at /usr/src/debug/gcc-11.4.0-1/libgcc/config/i386/cygwin.S:126
> #1  0x00000000002af7a8 in ?? ()
> #2  0x0000000a00015980 in ?? ()
> #3  0x0000000100563070 in V3Stats::statsStageAll (nodep=0x7ffe036e8, stage=..., fastOnly=fastOnly@entry=false) at ../V3Stats.cpp:168
> ```
> 
> Seems like something went bad in the stack. Unless you can debug further I'll need to install cygwin and debug, this may take a while. Can you use WSL instead of Cygwin?

Works with WSL. Works also under Cygwin with 5.016, it's 5.18/stable/master that have problems.

**Comment by wsnyder** [comment]
Ok, I'm unlikely to be able to debug this as don't have a Windows 11 system, if you can that would be great.

**Comment by wsnyder** [comment]
Closing as unlikely to get a fix without a pull request, as none of the maintainers AFAIK have Windows 11 + Cygwin.
