### ISSUE TITLE
Encountering errors related to UVM `type_id`

### ISSUE THREAD

**Issue by harshk-99** [verilator/verilator#4928]
<img width="970" alt="Error png" src="https://github.com/verilator/verilator/assets/75646768/9b7eb6f3-afbb-49e8-90e9-76bcaa59e2f3">

 I am trying to compile a UVM based testbench and getting this error. Is this because of UVM library or due to Verilator incompatibilty?
 
 I am aware that Verilator still does not completely support UVM, but since `type_id::create` is not working, I am wondering what is causing this issue.
 
 P.S. I am using Verilator v5.020 and UVM library from ChipsAlliance.

**Comment by wsnyder** [comment]
That UVM library should be the correct one.  We're not ready to support users using UVM, but you're welcome to debug and feed back any fixes/suggestions you find. If you do debug, I'd note that the test_regress/t/t_uvm_todo.t test in the Verialtor kit does pass and has similar constructs - the sources it uses came from that uvm-verilator library..
