### ISSUE TITLE
When I am using PIO in vscode to generate traces, the report shows success, but the vcd wave file is not generated in the folde

### ISSUE THREAD

**Issue by deleteeeee** [verilator/verilator#4929]
Installed verialtor on a windos system using Cygwin. gcc-core 11.4 ,verilator v4.228
When I am using PIO in vscode to generate traces, the report shows success, but the vcd wave file is not generated in the folder
![image](https://github.com/verilator/verilator/assets/145892840/41a4346f-a6a3-49a3-bdd3-2605a862e153)

There are only the following files in the .pio folder
![image](https://github.com/verilator/verilator/assets/145892840/e7d29a52-a951-42aa-bccd-2bca299ed356)

**Comment by wsnyder** [comment]
I don't know what PIO is, perhaps whoever makes that framework can help.  If you isolate this to something that only uses Verilator and can post a complete example doing that we'll try to help out.

Note also Cygwin tends to be pretty unstable. If there's any way you can use WSL instead it's much more robust.

**Comment by deleteeeee** [comment]
@wsnyder Thanks for the answer. pio refers to the plugin in vscode, platform IO.  Everything looks normal, except that the .vcd file cannot be generated

**Comment by wsnyder** [comment]
As above, If you isolate this to something that only uses Verilator and can post a complete example doing that we'll try to help out.

Closing until then.
