### ISSUE TITLE
Compiler is selected at configuration time

### ISSUE THREAD

**Issue by ekliptik** [verilator/verilator#4936]
https://github.com/verilator/verilator/blob/9dcb7ea6a962cdbc9c72a94d421da8169636ec08/include/verilated.mk.in#L13

What is the motivation for this? This is in conflict with the presence of the `--compiler` flag, which is set at verilation time.

**Comment by wsnyder** [comment]
--compiler affects only workarounds in emitted code.  I updated docs to emphasize this does not affect compiler flags (as those need to be determined experimentally) in configure.
