### ISSUE TITLE
Verilator 5.023 associates wrong option with bash command in warning message

### ISSUE THREAD

**Issue by europe2024** [verilator/verilator#4956]
The version of Verilator is Verilator 5.023 devel rev v5.020-154-g32f288084.

The OS is a variant of Debian (version 12).

The Verilated model produced the following message.

     %Warning: System has stack size 8192 kb which may be too small; suggest 'ulimit -c 234607' or larger

"ulimit -c" should be changed to "ulimit -s".

**Comment by wsnyder** [comment]
Thanks, fixed.
