### ISSUE TITLE
Does the verilator support the conversion of 3D arrays (4D arrays counting the bit width)?

### ISSUE THREAD

**Issue by YOKO-XIA** [verilator/verilator#4969]
Hello, does the verilator support the conversion of 3D arrays (4D arrays counting the bit width)?
During the verification, the function of the converted C++ code is inconsistent with that of the original RTL code.

```
reg  [1:0][7:0][7:0][15:0] buffer0;
reg  [7:0][15:0][15:0] buffer1;
reg  x;

always a* begin
    for (int i=0;i<8;i++) begin
        for (int j=0;j<16;j++) begin
            if (j<8 ) begin
                buffer1[i][j] = buffer0[x][i][j];
            end else begin
                buffer1[i][j] = buffer0[~x][i][j-8];
            end
        end
    end
end
```

Is the above writing supported?
I would be very grateful if you could answer me.

**Comment by wsnyder** [comment]
This should work, can you please post an example that is self-contained, self-checking, and passes on another simulator?

**Comment by YOKO-XIA** [comment]
Thank you very much. 
We found that the tool can support 3D arrays, but it cannot support assignment with 3D arrays (3D arrays on the right of "="). 
We replace the 3D array on the right of "=" with the equivalent expression of the 2D array, and the result is correct.
