### ISSUE TITLE
Compilation throws warnings on GCC14

### ISSUE THREAD

**Issue by np22-jpg** [verilator/verilator#4974]
The latest git commit (c92ced4ac79a84f1ed8ad9f1050571f6ee0e387b) fails when compiled on GCC 14. This is because of a [recent breaking change in the C++ standard](https://timsong-cpp.github.io/cppwp/n4861/diff.cpp17.class#2). Specifically, [this line](https://github.com/verilator/verilator/blob/master/src/V3OptionParser.cpp#L108) gets substituted to `ActionCbVal<int>(CbType cb)`, which throws a warning (that converts to an error with `--enable-ccwarn`) on GCC14. This blocks building on Fedora 40 and Rawhide.

(Mildly messed up) Error snippet:
```
./V3OptionParser.cpp:108:28: error: template-id not allowed for constructor in C++20 [-Werror=template-id-cdtor]
  108 |         explicit className(CbType cb) \
      |                            ^~~~~~
../V3OptionParser.cpp:118:1: note: in expansion of macro â€˜V3OPTION_PARSER_DEF_ACT_CB_CLASSâ€™
  118 | V3OPTION_PARSER_DEF_ACT_CB_CLASS(ActionCbVal<int>, void(int), m_cb(std::atoi(argp)), en::VALUE);
```

**Comment by wsnyder** [comment]
Thanks for the pull.
