### ISSUE TITLE
add reflection adjacent capability to model output

### ISSUE THREAD

**Issue by ct-clmsn** [verilator/verilator#5002]
In order to provide integration with simulation platforms, provide a generic mechanism to get access to I/O port data.

**Comment by ct-clmsn** [comment]
proposed solution submitted in PR #5003

**Comment by wsnyder** [comment]
I don't understand - why is this needed versus using the VPI?

**Comment by ct-clmsn** [comment]
I have a use case where code generated by Verilator is used in a simulator with a plugin system. The verilator code is baked into a plugin. The plugin interface needs to access the verilator generated code's I/O member variables in an opaque manner. Read/write access to verilator's I/O ports is important and this feature allows that access along with providing additional type information that the plugin wrapper needs to make runtime decisions.

**Comment by wsnyder** [comment]
And how is what you describe not provided by the VPI?

**Comment by wsnyder** [comment]
It's a different mechanism that adds significant maintenance costs which I'm reluctant to add as most users won't need this.  Can you overload more onto the vpi - perhaps something that uses the VPI discovery but has a verilator-specific function to return the raw Verilator data pointer? Then the cost to support is much more acceptable.

**Comment by wsnyder** [comment]
Seems discussion ran its course - no change for now.
