### ISSUE TITLE
`$sscanf` doesn't compile when the argument has to be masked

### ISSUE THREAD

**Issue by kiryk** [verilator/verilator#5035]
While working on #4999, I noticed arguments to `$sscanf` and `$fscanf` can get masked, which disallows passing reference to their Verilated equivalents. This, in turn, fails to compile.

I prepared a small example: [t_sscanf_clean.zip](https://github.com/verilator/verilator/files/14853554/t_sscanf_clean.zip).

I'm using the [current master](https://github.com/verilator/verilator/commit/8a4ceb571713e3420846c0de6956ad0b62ff77e1) on Fedora with Linux 6.6.9

**Comment by wsnyder** [comment]
See  #3224, a pull to fix this would be appreciated, please comment there.
