### ISSUE TITLE
Include a CITATION.ttf

### ISSUE THREAD

**Issue by coastalwhite** [verilator/verilator#5057]
It would be really nice to have a simple way to cite this work being done for academics. GitHub has accepted the [Citation File Format](https://citation-file-format.github.io/) for repositories. I would truly appreciate it if this repository could add such a file.

**Comment by wsnyder** [comment]
Can you create a pull with the file or attach here?  Put in "fixme" if some things are unknown to you. It's OK if tests fail on the pull as I'll fill in the fixme.
