### ISSUE TITLE
MacOS x86 compilation failure

### ISSUE THREAD

**Issue by neeldugar** [verilator/verilator#5086]
Effectively there are a couple of lines of non-portable code for MacOS x86, see [here](https://github.com/verilator/verilator/blame/0da7ecf753a69aa35f991f0873d764b6ebae6a14/include/verilatedos_c.h#L54) and [here](https://github.com/verilator/verilator/blame/0da7ecf753a69aa35f991f0873d764b6ebae6a14/include/verilatedos_c.h#L69) which is preventing the conda-forge/verilator-feedstock automatic distribution, seems to have been introduced in #5018  for v5.024. Strangely enough seems like MacOS arm builds are not impacted by this.

**Comment by wsnyder** [comment]
Can you please submit a pull request to fix this with appropriate ifdefs?

**Comment by neeldugar** [comment]
Sure, will look at it a little later.

**Comment by wsnyder** [comment]
@neeldugar did you find a work around for this - can you submit a patch?

**Comment by wsnyder** [comment]
Ok, given that and lack of a patch I'm closing this out, if a Mac x86 user wants to submit a pull later, great.
