### ISSUE TITLE
Incorrect result involving concat, ternary expression, and indexing with underflow

### ISSUE THREAD

**Issue by VarunKoyyalagunta** [verilator/verilator#5095]
I created a failing test here
https://github.com/verilator/verilator/compare/master...VarunKoyyalagunta:verilator:bug/concat_index_ternary_subtract_underflow

It failed on `v5.024` and master (841dd13681d80b8769d4430b3d64ba5a6421ac98)

This is where the bad computation happens. Note `cnt[2:0]` is greater than `3'd2`.

```
out <= {in[31], q[cond ? 3'd2 - cnt[2:0] : 3'd0]};
```
Small tweaks such as removing the concat, or separating out the `3'd2 - cnt[2:0]` into a temp variable and using that causes the test to pass.

> May we assist you in trying to fix this in Verilator yourself?

Sure

**Comment by wsnyder** [comment]
Thanks for the good test case. 

Fixed.  The use of a packed array internally needs a multiply to choose the right slice, and that upset calculating the index's expression width and so the index result.
