### ISSUE TITLE
Installation on Apple Silicon Mac Fails

### ISSUE THREAD

**Issue by expsg-Zubin** [verilator/verilator#5117]
Hi, I am trying to install Verilator on an apple silicon Mac, I clone the GitHub onto my Mac and then attempt to use the autoconf tool to set the configurations up for installation. The issue is that I always seem to get the error.

"configure: error: the g++ -std=gnu++11 compiler appears to not support C++11."

**Comment by wsnyder** [comment]
I was hoping an apple user would comment... but as not... are you sure you have the latest OS and compiler installed?  The message suggests not.

**Comment by wsnyder** [comment]
Think this was recently fixed, please try git master and open a new issue if fails.
