### ISSUE TITLE
lvalue error encountered when trying to build with verilator

### ISSUE THREAD

**Issue by space-devon** [verilator/verilator#5119]
Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)
![image](https://github.com/verilator/verilator/assets/160534325/27d1af50-dc42-44f6-bff7-c269bc8d8fc3)

What 'verilator' command line do we use to run your example?
We have a makefile, but the issue doesn't seem to be with our example. There are a lot of subfiles involved, so it's hard to replicate externally.

What 'verilator --version' are you using?  Did you try it with the git master version?
This is on version 5.0.1.0. This is the version we need for compatibility with Renode, so we cannot use the master version.

What OS and distribution are you using?
Linux

May we assist you in trying to fix this in Verilator yourself?
Yes

**Comment by wsnyder** [comment]
Closing, if provide test case please reopen.
