### ISSUE TITLE
UVM Getting Started

### ISSUE THREAD

**Issue by philipaxer** [verilator/verilator#5155]
Hi All,

I want to start with verilator's UVM  support. I am unclear what the latest and greatest matching UVM/verilator sources are. There are too many branches and repos. There is the chipalliance UVM repository which has a gazillion branches and there is the verilator UVM repo. I am not actively looking at the development flow, i.e. which repo is leading and which is following. This makes it very hard to track where to clone from.
There are also some presentations form Antmicro which point to VeeR-EL2. This checks out specific commits form some "cherry picked" repos, however that is not what i am looking for. I assume that the development progressed since this presentation.

Given that there seems to be decent support by now, it would be really helpful if there was an official "UVM Getting Started" which helps  to set up the right environment.

cheers
Philip

**Comment by ramazankaan95** [comment]
I am also looking forward for this!

**Comment by wsnyder** [comment]
I appreciate this would be useful.  As summarized in #1538 UVM is still not supported yet, so there will not yet be any official write up on how to run UVM.  Antmicro is free to describe how to use their branches if they want to, but that is outside of this official tree.   As always we'd welcome help on taking Antmicro or other branches or implementing features in the main branch towards official UVM support.

**Comment by obliguedon** [comment]
look at this project : [GettingVerilatorStartedWithUVM](https://github.com/MikeCovrado/GettingVerilatorStartedWithUVM)

especialy the [`run_verilator.sh`](https://github.com/MikeCovrado/GettingVerilatorStartedWithUVM/blob/b79355d7a21d17e1a00ffda4a765bd31c476efdb/scripts/run_verilator.sh)

**Comment by serge0699** [comment]
@philipaxer, you can also check [verilator-verification-features-tests](https://github.com/antmicro/verilator-verification-features-tests) with this [post](https://antmicro.com/blog/2024/09/open-source-uvm-verification-axi-in-verilator/).
