### ISSUE TITLE
Does Verilator have a conditional trigger feature similar to ESSENT?

### ISSUE THREAD

**Issue by listenchin** [verilator/verilator#5157]
I am a senior student currently working on my graduation project from China, which involves implementing a conditional trigger mechanism in Verilator. I have completed a rough implementation based on version 5.019 (with an algorithm similar to ESSENT). However, when testing with a self-implemented MIPS CPU, there was no significant performance improvement. After reading the generated C++ model, I found that most of the logic is recognized as sequential logic and resides in the NBA (non-blocking assignment) region. This results in my internally implemented triggers for checking whether regions are active using sentree mostly being clock signals (clk). Do you have any suggestions for improvement? Thank you very much and sorry for my poor English.

**Comment by wsnyder** [comment]
Glad to have you working on this!

Verilator tries hard to avoid any combo logic, as you noticed.

If you take the design you mention, and perhaps a few other medium/large designs and run it through essent, and also through Verilator, how does the performance compare?  

I suspect most of the potential gain would be to compute what clock trees can be entirely turned off to avoid computing sequential blocks.

I'd suggest taking a Verilated design, and manually editing the C++ in a way that you think could be optimized, then measuring the performance, that will tell you if the optimization when automated might help.

Link to ESSENT https://github.com/ucsc-vama/essent

**Comment by wsnyder** [comment]
Closing - others feel free to comment even if closed.
