### ISSUE TITLE
Fix DPI import of null C-string

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#5179]
From #5177 (unrelated to that bug's real problem):

```
import "DPI-C" function string getenvval(input string env_name);
string       RISCV_DIR = getenvval("RISCV");

const char *getenvval(const char *pszName) {
    return ((const char *) getenv(pszName));
}
```

When RISCV is not defined this returns null. @davidharrishmc you should ask to get the C code fixed - have it return e.g. "" or give an error or whatever.

But, to defend against crashes Verilator should treat nulls as "" when dpi-importing a null string.

**Comment by davidharrishmc** [comment]
Thank you.  I've made that change to sim/verilator/wrapper.c.  The if block is the new part.

Our new code appears to work normally and also prevent the crash when RISCV is undefined.

```
#include <stdlib.h>

#include "Vtestbench__Dpi.h"

const char *getenvval(const char *pszName) {
    const char *pszValue = getenv(pszName);
    if (pszValue == NULL) {
        return "";
    }
    return ((const char *) getenv(pszName));
}
```
