### ISSUE TITLE
Change to read config files first

### ISSUE THREAD

**Issue by kaddkaka** [verilator/verilator#5185]
When waiving lint errors with `-lines` option, the config file has to go before the source code file on the command line.

This behavior was very confusing to me and a colleague today.

When putting the file in the wrong order, the outcome is that the waiver is ignored and the warning is still counted and reported. This happens without any error or warning from the tool.

Suggestion:
- warn if a waiver doesn't have any effect
- warn if a line waiver is applied after the file has already been scanned
- force the config file to be first in the command (?)

Doing any of these would make verilator lint an easier tool to use. But doing any kind of work to simplify this is equally welcomed. :)

**Comment by wsnyder** [comment]
> force the config file to be first in the command (?)

Hmm.  Presently .vlt files are handled same as .v files.  This in theory allows the controls to be intermixed with the .v file, though I suspect no one is doing that. I guess I'm open to a pull to do this.

>warn if a line waiver is applied after the file has already been scanned

Doable, but above seems better.

>warn if a waiver doesn't have any effect

There was some discussion in #3138 and we decided not to do that (though the issue kind of drifted).
