### ISSUE TITLE
verilator.mk missing in cmake installation

### ISSUE THREAD

**Issue by philipaxer** [verilator/verilator#5187]
When you compile and install verilator with cmake, it will not correctly install verilator.mk. Also the configuration from verilator.mk.in to verilator.mk is broken.
This means that from a verilator that was installed via cmake, you cannot run the examples which are Makefile-based.

regards
Philip

**Comment by wsnyder** [comment]
cmake build/install is not officially supported outside Windows. But anyhow worth fixing, could you submit a pull to fix this?

**Comment by wsnyder** [comment]
Appreciate the fix.
