### ISSUE TITLE
clang>12 coroutine test fail while ./configure

### ISSUE THREAD

**Issue by jcteng** [verilator/verilator#5201]
![image](https://github.com/verilator/verilator/assets/14208527/80b6d933-4681-4fd7-a2c0-b3b8c3fe491d)

**Comment by wsnyder** [comment]
What OS?  If Mac see #5190.

**Comment by wsnyder** [comment]
If not mac please convert the screen shot to text, thanks.

**Comment by jcteng** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

`./configure CC=clang-17 CXX=clang++-17
configuring for Verilator 5.027 devel
checking whether to perform partial static linking of Verilator binary... yes
checking whether to use tcmalloc... check
checking whether to build for coverage collection... no
checking whether to use hardcoded paths... yes
checking whether to show and stop on compilation warnings... no
checking whether to run long tests... no
checking for z3... yes
checking for cvc5... no
checking for cvc4... no
checking for SMT solver... z3 --in
checking for gcc... clang-17
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether clang-17 accepts -g... yes
checking for clang-17 option to enable C11 features... none needed
checking whether the compiler supports GNU C++... yes
checking whether clang++-17 accepts -g... yes
checking for clang++-17 option to enable C++11 features... none needed
checking for a BSD-compatible install... /usr/bin/install -c
compiler is clang++-17 --version = Ubuntu clang version 17.0.6 (++20231209124227+6009708b4367-1~exp1~20231209124336.77)
checking that C++ compiler can compile simple program... yes
checking for ar... ar
checking for perl... /usr/bin/perl
checking for python3... /usr/bin/python3
checking for flex... /usr/bin/flex
/usr/bin/flex --version = flex 2.6.4
checking for bison... /usr/bin/bison
/usr/bin/bison --version = bison (GNU Bison) 3.8.2
checking for ccache... ccache
objcache is ccache --version = ccache version 4.5.1
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for size_t... yes
checking for size_t... (cached) yes
checking for inline... inline
checking whether clang++-17 accepts -pg... yes
checking whether clang++-17 accepts -std=gnu++17... yes
checking whether clang++-17 accepts -Wextra... yes
checking whether clang++-17 accepts -Wfloat-conversion... yes
checking whether clang++-17 accepts -Wlogical-op... no
checking whether clang++-17 accepts -Wthread-safety... yes
checking whether clang++-17 accepts -fcoroutines-ts... no
checking whether clang++-17 accepts -fcoroutines... no
checking whether clang++-17 accepts -fcoroutines-ts -Wno-deprecated-experimental-coroutine... no
checking whether coroutines are supported by clang++-17... no
checking whether clang++-17 accepts -Qunused-arguments... yes
checking whether clang++-17 accepts -faligned-new... yes
checking whether clang++-17 accepts -Wno-unused-parameter... yes
checking whether clang++-17 accepts -Wno-shadow... yes
checking whether clang++-17 accepts -Wno-char-subscripts... yes
checking whether clang++-17 accepts -Wno-null-conversion... yes
checking whether clang++-17 accepts -Wno-parentheses-equality... yes
checking whether clang++-17 accepts -Wno-unused... yes
checking whether clang++-17 accepts -Og... yes
checking whether clang++-17 accepts -ggdb... yes
checking whether clang++-17 accepts -gz... yes
checking whether clang++-17 linker accepts -gz... yes
checking whether clang++-17 accepts -faligned-new... yes
checking whether clang++-17 accepts -fbracket-depth=4096... yes
checking whether clang++-17 accepts -fcf-protection=none... yes
checking whether clang++-17 accepts -mno-cet... no
checking whether clang++-17 accepts -Qunused-arguments... yes
checking whether clang++-17 accepts -Wno-bool-operation... yes
checking whether clang++-17 accepts -Wno-c++11-narrowing... yes
checking whether clang++-17 accepts -Wno-constant-logical-operand... yes
checking whether clang++-17 accepts -Wno-non-pod-varargs... yes
checking whether clang++-17 accepts -Wno-parentheses-equality... yes
checking whether clang++-17 accepts -Wno-shadow... yes
checking whether clang++-17 accepts -Wno-sign-compare... yes
checking whether clang++-17 accepts -Wno-tautological-bitwise-compare... yes
checking whether clang++-17 accepts -Wno-tautological-compare... yes
checking whether clang++-17 accepts -Wno-uninitialized... yes
checking whether clang++-17 accepts -Wno-unused-but-set-parameter... yes
checking whether clang++-17 accepts -Wno-unused-but-set-variable... yes
checking whether clang++-17 accepts -Wno-unused-parameter... yes
checking whether clang++-17 accepts -Wno-unused-variable... yes
checking whether clang++-17 linker accepts -mt... no
checking whether clang++-17 linker accepts -pthread... yes
checking whether clang++-17 linker accepts -lpthread... yes
checking whether clang++-17 linker accepts -latomic... yes
checking whether clang++-17 linker accepts -fuse-ld=mold... yes
checking whether clang++-17 linker accepts -fuse-ld=mold... yes
checking whether clang++-17 linker accepts -static-libgcc... yes
checking whether clang++-17 linker accepts -static-libstdc++... yes
checking whether clang++-17 linker accepts -Xlinker -gc-sections... yes
checking whether clang++-17 linker accepts -lpthread... yes
checking whether clang++-17 linker accepts -latomic... yes
checking whether clang++-17 linker accepts -lbcrypt... no
checking whether clang++-17 linker accepts -lpsapi... no
checking whether clang++-17 linker accepts -l:libtcmalloc_minimal.a... yes
checking whether clang++-17 accepts -fno-builtin-malloc... yes
checking whether clang++-17 accepts -fno-builtin-calloc... yes
checking whether clang++-17 accepts -fno-builtin-realloc... yes
checking whether clang++-17 accepts -fno-builtin-free... yes
checking whether clang++-17 supports C++14... yes
checking for clang++-17 precompile header include option... -include-pch
checking for struct stat.st_mtim.tv_nsec... yes
checking whether SystemC is found (in system path)... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/Makefile_obj
config.status: creating include/verilated.mk
config.status: creating include/verilated_config.h
config.status: creating verilator.pc
config.status: creating verilator-config.cmake
config.status: creating verilator-config-version.cmake
config.status: creating src/config_package.h

Now type 'make' (or sometimes 'gmake') to build Verilator.
`

**Comment by wsnyder** [comment]
I checked and this works on the git master, I think due to #5200 being fixed.

**Comment by jcteng** [comment]
thanks
