### ISSUE TITLE
Cannot use inout wire as input and output

### ISSUE THREAD

**Issue by Gerharddc** [verilator/verilator#5207]
I am having an issue with Verilator where it is not possible to use an inout wire as input and output simultaneously as in the example at https://www.intel.com/content/www/us/en/support/programmable/support-resources/design-examples/horizontal/ver-bidirec.html.

When running the following test:

```
TEST_SUITE("Bidirectional Module")
{
    static auto dut = make_unique<Vbidir>();

    TEST_CASE("Can Write")
    {
        // Set bidir as ouput
        dut->oe = 1;
        dut->inp = 123;
        dut->clk = 0;
        dut->eval();
        
        // Clock to latch
        dut->clk = 1;
        dut->eval();
        dut->clk = 0;
        dut->eval();

        CHECK(dut->bidir == 123);
    }

    TEST_CASE("Can Read")
    {
        // Set bidir as input
        dut->oe = 0;
        dut->bidir = 101;
        dut->clk = 0;
        dut->eval();
        
        // Clock to latch
        dut->clk = 1;
        dut->eval();
        dut->clk = 0;
        dut->eval();

        CHECK(dut->outp == 101);
    }
}
```

It fails because it seems that in the "Can Read" test, the "outp" signal does not get updated an is stuck at 0.

**Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)**

I have uploaded an example with tests to https://github.com/Gerharddc/verilator-inout-issue/tree/main and attached the source as [verilator-inout-issue-main.zip](https://github.com/user-attachments/files/16025821/verilator-inout-issue-main.zip)

**What 'verilator' command line do we use to run your example?**

Not sure, I'm using CMake to verilate but have the CMakeLists.txt in the linked project.

**What 'verilator --version' are you using?  Did you try it with the git master version?**

`Verilator 5.006 2023-01-22 rev (Debian 5.006-3)`

I have observed the same issue with the git master version though.

**What OS and distribution are you using?**

Debian 12 from the `mcr.microsoft.com/devcontainers/cpp:debian-12` Docker image.

**May we assist you in trying to fix this in Verilator yourself?**

Sure, I can give it a shot but have no familiarity with the codebase or inner workings of Verilator.

**Comment by wsnyder** [comment]
See #3812, #4856.  You need to use --pins-inouts-enables, then read from bidir__en and bidir__out.
