### ISSUE TITLE
Dumping port widths 

### ISSUE THREAD

**Issue by rzig** [verilator/verilator#5231]
When I generate JSON or XML, I’m only able to see port types and not widths (unless I’m overlooking something… very possible). Is there any way to get the widths? If not, I’m happy to make a PR for that

**Comment by wsnyder** [comment]
Follow the data type ud:

>dtype_id="2"

To e.g.
><basicdtype loc="d,15,16,15,17" id="1" name="logic" left="2" right="0"/>
     
So this is width 2-0+1=3.
