### ISSUE TITLE
The meaning of different node colors, in the visualized DFG?

### ISSUE THREAD

**Issue by enochliang** [verilator/verilator#5232]
Following the previous question [issues/5230](https://github.com/verilator/verilator/issues/5230#issue-2393508920).
Thanks for your reply, I've successfully dumped the global DFG of my design.
I converted the `.dot` into `.pdf`.

This is what it looks like:
![image](https://github.com/verilator/verilator/assets/22961212/19803d1e-8cd9-41e2-b78d-ec4c65701213)

I found that the nodes of signal have different color.
As what I observed, the **_rectangle nodes_** are **_signals_** (including wire & register).
The **_cuboid node_** is **_array_**.
The **_circle node_** is **_operation_**
**_Green signals_** are **_input_**, **_Cyan signals_** are **_output_**.
And the rest of signals are internal, but I'm not sure about the meaning of **_Orange_**, **_Red_**, and **_White_**.

Can you tell me the difference between the nodes of these three colors?

**Comment by wsnyder** [comment]
Please refer to the sources, e
g. search for "shape=" and "fillcolor=" in https://github.com/verilator/verilator/blob/490bc63eb5b4642c1c54234b613a55232cca44a0/src/V3Dfg.cpp#L70
