### ISSUE TITLE
Add reference to Surfer waveform viewer to the Verilator FAQ

### ISSUE THREAD

**Issue by LucasKl** [verilator/verilator#5253]
Currently, the Verilator FAQ says that only GTKWave supports the FST format.
I propose to add a reference to the [Surfer](https://gitlab.com/surfer-project/surfer) waveform viewer as well.
Surfer is a relatively young but feature-rich waveform viewer with support for vcd, fst, and ghw files.
Surfer runs natively on Windows, macOS, and Linux as well as in the browser and as a VSCode extension.

The related section of the FAQ:
```
How do I view waveforms (aka dumps or traces)?

Verilator creates standard VCD (Value Change Dump) and FST files. VCD files are viewable with the open-source GTKWave (recommended), or Dinotrace (legacy) programs, or any of the many closed-source offerings; FST is supported only by GTKWave.
``` 

My proposal:
```
How do I view waveforms (aka dumps or traces)?

Verilator creates standard VCD (Value Change Dump) and FST files. VCD files are viewable with the open-source GTKWave (recommended), Surfer, or Dinotrace (legacy) programs, or any of the many closed-source offerings; FST is supported only by GTKWave and Surfer.
```

If possible, it would be nice to make the first Surfer reference a link to the project website (https://surfer-project.org/).

Thank you very much for considering mentioning Surfer!

**Comment by Kreijstal** [comment]
could there be a way to somehow simulate inside surfer?

**Comment by LucasKl** [comment]
@Kreijstal An integration between Verilator and Surfer sounds interesting. If you have any ideas, feel free to open an issue in the Surfer repository. :)

**Comment by LucasKl** [comment]
Great! Thanks for mentioning Surfer.
