### ISSUE TITLE
Verilating the parameterized block multiple times

### ISSUE THREAD

**Issue by atomlin** [verilator/verilator#5267]
I want to verilate the same block multiple times with a parameter. I can provide the parameter with -G, but I was unsure if I should use the prefix to specify the output. Is there any example of parameterized blocks?

**Comment by wsnyder** [comment]
If you want to save each different parameter verilation output separately, then you need a different -Mdir for each. if multiple will be put into the same binary then you need a different prefix and optionally different Mdir.
