### ISSUE TITLE
Unexpected Size of obj_dir folder

### ISSUE THREAD

**Issue by DenizzzGuzell** [verilator/verilator#5315]
Hi,

I am using currently Verilator 5.026 2024-06-15 rev v5.026-43-g065f36ab5 (stable branch). When I try to verilate my project using only given command :

`>verilator -f flist --cc --top-module top --debug`

To see whether or not Vtop file will be created succesfully. obj_dir folder spesifically some of .tree files for example `Vtop_035_scope.tree` file size is relatively big like 1.7GB and there are at least 4 of this .tree files as :

- 035_scope
- 036_linkdot
- 039_deadDtypesScoped
- 043_unroll

Is it related with project complexity or is there an anomality related with either project files or my command to verilate project.

I have done testing using `make test` and example projects whether my verilator installation is mistaken but no it does work as expected.

Thank you.

**Comment by wsnyder** [comment]
.tree are debug dumps, and often large. If you don't want them, don't use --debug, or use -no-dump-tree.
