### ISSUE TITLE
Support for unpacked structure

### ISSUE THREAD

**Issue by deepans88** [verilator/verilator#5321]
Hi,

Do we have support for using unpacked structures using any Verilator version :- 

Currently using following versions:-

Verilator 5.027 devel rev v5.026-2-gd5cfe1a
GCC version:-gcc (GCC) 7.3.0

**Comment by wsnyder** [comment]
Unpacked structures are generally supported though an UNSUPPORTED error indicates some more detailed thing is not supported.  If something crashes without an UNSUPPORTED error, please open a new issue with a minimal example.
