### ISSUE TITLE
Unrolling Loop Elements in AST.xml

### ISSUE THREAD

**Issue by enochliang** [verilator/verilator#5366]
Hey. I'm finding a way to unroll the for loops in a SystemVerilog design and **_also unroll the AST elements representing loop_**. So I add a metacomment above the for loop like this (The green part). (The red blocks: loop index)(The yellow blocks: circuit element)
![image](https://github.com/user-attachments/assets/436fb5fe-c5f0-48e2-9685-3afcb9edeb16)

The picture below is the AST of it. After I add the metacomment, there are still loops in the AST. These part of AST matches the above RTL code.
![image](https://github.com/user-attachments/assets/0a0c6918-877f-4021-a287-ac93782c15b7)

QUESTION:
I don't want the <while> block in the AST. _**So I want to know if there is any way I can try to achieve that?**_ 
If not, maybe I can start writing a script to transform the AST.xml.

**Comment by wsnyder** [comment]
Run with `--debugi-V3Unroll 9` and it should say why not unrolling.  It cannot unroll if it cannot determine indicies.

**Comment by wsnyder** [comment]
Assuming you got this resolved, reopen with what you think is wrong in Verilator if not, thanks.
