### ISSUE TITLE
Comparing performance between dumping vcd and not dumping.

### ISSUE THREAD

**Issue by futurehome** [verilator/verilator#5377]
How may we help - what is your question?
(If reporting a bug or requesting a feature please use one of the other issue templates.)

I tried to run simulation of my design using verilator generated cmodel(which is a large design), in 48 threads, if not dumping vcd file, it takes about 35mins to complete, if dumping vcd file, the run time will boost to 160mins, comparing with simulation with vcs, the gap will not be such huge. Is the degration of performance expected when dumping vcd?

Thanks,
Alex

**Comment by wsnyder** [comment]
Yes, vcd requires many extra computations, plus the I/O.  Use the trace off pragmas to make it take less time.
