### ISSUE TITLE
Support for wired OR and wired AND nets

### ISSUE THREAD

**Issue by Mijyuoon** [verilator/verilator#5386]
Is there a specific reason why `wor`/`trior` and `wand`/`triand` net types aren't supported? (checked on the latest master branch)

I have a project that uses them in several places and having to replace them with workarounds isn't great.

**Comment by wsnyder** [comment]
wor etc are generally not used by recent synthesizable designs, and as somewhat proof of that, you are first to ask. If you need this please consider submitting a pull to fix it (probably mostly work in V3Tristate), as we are unlikely otherwise to get to it given competing priorities.

**Comment by Mijyuoon** [comment]
Thanks for letting me know, I might actually have a go at it when I have time.

**Comment by nookfoo** [comment]
We would also interested in the support of this, as we are using `wor`!
