### ISSUE TITLE
Wrong reference to LRM in error message

### ISSUE THREAD

**Issue by goekce** [verilator/verilator#5453]
https://github.com/verilator/verilator/blob/77fc771ed00ab699d549efb9fac99eb5a4b22254/src/V3Width.cpp#L2786-L2787
I noticed that there is no reference to this in section 7.2.1 but 7.2.2:

> Members of unpacked structures containing a union as well as members of packed structures shall not be assigned individual default member values.

If someone confirms I can PR.

**Comment by wsnyder** [comment]
Agreed, trivial fix so just pushed for you.
