### ISSUE TITLE
Question about Toggle Coverage Count with --coverage-toggle

### ISSUE THREAD

**Issue by figuresudo** [verilator/verilator#5463]
I am currently using the --coverage-toggle option to collect coverage data, and I am able to retrieve the results, including signals and count information. However, I would like to understand how this count is calculated. Specifically, how can I determine whether a signal has transitioned from 1 to 0 and from 0 to 1 based on the collected counts?

For reference, I am using Verilator version 5.020.

**Comment by wsnyder** [comment]
It counts every time the signal toggles, that is 0->1, 1->0.  So a count of 1 means it must have been at least 0 and 1 once.

**Comment by figuresudo** [comment]
So, do you mean that a count of 2 means it must have encountered 0-&gt;1 one time and 1-&gt;0 one time?



---Original---
From: "Wilson ***@***.***&gt;
Date: Thu, Sep 19, 2024 19:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [verilator/verilator] Question about Toggle Coverage Count with--coverage-toggle (Issue #5463)




 
It counts every time the signal toggles, that is 0-&gt;1, 1-&gt;0.  So a count of 1 means it must have been at least 0 and 1 once.

**Comment by wsnyder** [comment]
Yes, or 1->0 then 0->1.
