### ISSUE TITLE
Regarding Verilator's fixed two-state logic

### ISSUE THREAD

**Issue by katsui97** [verilator/verilator#5464]
I understand that "Verilator" aims for high speed with two-state logic, but during debugging, I really need four-state logic.

Is it currently possible to enable this with some options or in any way? Or is it not possible? If not, is there any plan to support it in the future?

**Comment by wsnyder** [comment]
No option, and unlikely for at least several years.

**Comment by katsui97** [comment]
Thank you for your response.
