### ISSUE TITLE
problem using multi-dimensional arrays as consts

### ISSUE THREAD

**Issue by toddstrader** [verilator/verilator#5471]
See #5469 .  `t_interface_derived_type` has a `SHOW_2D_BUG` define, which if uncommented shows that multi-dimensional arrays are not being recognized as consts.  Or maybe it's only in the context of interface parameters?  I'm not sure.
```
%Error: t/t_interface_derived_type.v:12:12: Expecting expression to be constant, but variable isn't const: 'arr'
                                          : ... note: In instance 't.sub16'
   19 |     logic [arr[0][0]-1:0] other_data;
      |            ^~~
```

This test works fine if `arr` is a single-dimensional array.

**Comment by wsnyder** [comment]
See #2272.
