### ISSUE TITLE
Change `--main` and `--binary` to omit TOP name

### ISSUE THREAD

**Issue by wsnyder** [verilator/verilator#5482]
Currently `--main` (and `--binary`) uses the default top model name of "TOP". This means that the hierarchy printed in waves and VPI, etc, start with TOP, e.g. this

  ```
 module t;
     initial $display("%m");
   endmodule
```

Prints `TOP.t`.

To match other simulators the name() will be changed to `""`, this means the above will print `t`.

Be aware this may break VPI searches for signal names, and other behavior compared to previous Verilator versions.

**Comment by wsnyder** [comment]
`--main-top-name TOP` can be used to get the old behavior.

**Comment by keesj** [comment]
I am stumbling on this (having to deal with an empty scope...) and found  
https://gitlab.com/ChipFlow/surfer/-/blob/main/examples/verilator_empty_scope.vcd
The other test files in that repository do not have empty scopes hence I guess this is not  really y"like other tools". more recent versions of verilator do "simply" remove the top scope and this sounds like a better option
