### ISSUE TITLE
SIGSEGV when localparam has circular value

### ISSUE THREAD

**Issue by luizademelo** [verilator/verilator#5502]
### Description
When running `verilator --cc` on this program
```systemverilog
localparam id_1 = id_1[0];
```
Verilator crashes with the following message: 
```
%Error: test.v:1:12: Variable's initial value is circular: 'id_1'
    1 | localparam id_1 = id_1[0];
      |            ^~~~
%Error: test.v:1:23: Illegal bit or array select; type does not have a bit range, or bad dimension: data type is 'logic'
    1 | localparam id_1 = id_1[0];
      |                       ^
%Error: Verilator internal fault, sorry. Suggest trying --debug --gdbbt
%Error: Command Failed /usr/bin/verilator_bin --cc test.v
```
When running with `--debug` and `--gdbbt` options, the output is the following message: 
```
%Error: test.v:1:12: Variable's initial value is circular: 'id_1'
-node: VAR 0x555555f348a0 <e28#> {c1am} u5=0x1 @dt=0x555555f347c0@(nw1)  id_1 [VSTATIC]  LPARAM
    1 | localparam id_1 = id_1[0];
      |            ^~~~
%Error: test.v:1:23: Illegal bit or array select; type does not have a bit range, or bad dimension: data type is 'logic'
-node: SELBIT 0x555555f346b0 <e29#> {c1ax}
    1 | localparam id_1 = id_1[0];
      |                       ^

Program received signal SIGSEGV, Segmentation fault.
```
### Expected behavior
This program is incorrect and the error messages are fine, but I believe Verilator shouldn't throw a Segmentation Fault.

### Verilator's version
Verilator 4.038 2020-07-11 rev v4.036-114-g0cd4a57ad

**Comment by wsnyder** [comment]
Our general rule is as long a there is an earlier clear message, we will not debug and fix a segfault. This is simply because there are too many, and our time seems better spent on other issues.

However if you'd like to debug and submit a pull to fix, it would be welcome.
