### ISSUE TITLE
Allow multiple toplevels.

### ISSUE THREAD

**Issue by Febbe** [verilator/verilator#5508]
It would be usefull, to allow multiple toplevels because we don't want to always test a complete DUT with all its peripherals.
Imagine you want to just test and compile specific modules in your workspace and to cover all other stuff in your testbench.
Then you'll have multi toplevels, which communicate via the testbench with each other.

Here is a simple graphic:
[VerilTB-1.pdf](https://github.com/user-attachments/files/17257001/VerilTB-1.pdf)

**Comment by wsnyder** [comment]
This is already supported, just suppress the MULTTOP warning: https://verilator.org/guide/latest/warnings.html#cmdoption-arg-MULTITOP
