### ISSUE TITLE
Run Different Models on Different Threads

### ISSUE THREAD

**Issue by alpha-beta-user** [verilator/verilator#5521]
This is a gerat job!

I want to know If I can run Different models on different Threads/cores. My RTL model is a large project. Then I translate the rtl project into systmec model. 

But if I simulate the whole systemc project, it is time-consuming. It takes too much time to run over.

So I want to know if any methods to accelarated the simulated speed, maybe run parallel on different threads/cores. Maybe Varitor support generate such multi-thread systemc model.

Thanks for your attention.

**Comment by wsnyder** [comment]
Please see the documentation and notes on --sc use: https://veripool.org/guide/latest/verilating.html#multithreading

If after that you have additional questions feel free to follow up here.

**Comment by alpha-beta-user** [comment]
I find that if I set threads 4, it is much slower than single thread. even I make the design more complex.

can you tell me reason.

thanks for your answer!

**Comment by wsnyder** [comment]
Probably the design is still very small. Run thread profiling as described in the manual to see if/why.

**Comment by wsnyder** [comment]
As a general metric, anything faster than ~~10k clocks/second is small and might not benefit from threading.

**Comment by alpha-beta-user** [comment]
> As a general metric, anything faster than ~~10k clocks/second is small and might not benefit from threading.

do you mean the clock cycle should be laeger enough?

1 / 10000 = 10^(-4)s = 10^5 ns

clock cycle should be bigger than 10^5ns

Is It right?

thank you for your reply?

**Comment by wsnyder** [comment]
I mean the performance of the model relative to wall time.  I thought we printed this in the gantt report, but I guess not, you can see it in the summary:

```
- S i m u l a t i o n   R e p o r t: Verilator 5.029 devel
- Verilator: $finish at 17ps; walltime 10.005 s; speed 2.841 ns/s
```

So if your modeled clock is 1ns, this is running 2.84 clocks/second.  Make sure you simulate for many wall-seconds for this or any profile to be accurate.

**Comment by alpha-beta-user** [comment]
> I mean the performance of the model relative to wall time. I thought we printed this in the gantt report, but I guess not, you can see it in the summary:
> 
> ```
> - S i m u l a t i o n   R e p o r t: Verilator 5.029 devel
> - Verilator: $finish at 17ps; walltime 10.005 s; speed 2.841 ns/s
> ```
> 
> So if your modeled clock is 1ns, this is running 2.84 clocks/second. Make sure you simulate for many wall-seconds for this or any profile to be accurate.

Thank you for answer!

I want to know how can I get the report.

I read the verilator --help, can not get it.

Thank you!

**Comment by wsnyder** [comment]
https://veripool.org/guide/latest/simulating.html#simulation-summary-report
