### ISSUE TITLE
Regarding using verilator as a fault simulator

### ISSUE THREAD

**Issue by rafidmuttaki93** [verilator/verilator#5532]
Hi,
I am uisng one branch of verilator with fault simulation capability contributed by endrikaja1. I was ablse to inject single faults into the design, however, when trying to inject fault on multiple signals, the tool always injects fault in the last signal. I was wondering is there any support to facilitate fault injection simultaneously on multiple locations (signals)? Thanks!

**Comment by wsnyder** [comment]
You need to contact @endrikaja1 who can hopefully answer.  Welcome to reply here, but as this is outside the Verilator code base I'm closing as we won't be tracking it.
