### ISSUE TITLE
Add the UDP Table support

### ISSUE THREAD

**Issue by godblesszhouzhou** [verilator/verilator#5533]
I want to add the UDP Table support for verilator. Currently, the UDP Table will be parsed as:
AstUdpTable->
AstUdpTableLine -> AstUdpTableLine -> AstUdpTableLine  ...
For example
`    table 
           ?  1  :   1;
           1  0  :   1;
           1  1  :   1;
           0  0  :   0;
    endtable`

The current generated AstNodes will be:
AstUdpTable ->
AstUdpTableLine("?  1  :   1") -> AstUdpTableLine("1  0  :   1") -> AstUdpTableLine("1  1  :   1") -> AstUdpTableLine("0  0  :   0").

The basic algorithm I think of is that：
1. Parse the AstUdpTableLines of a AstUdpTable as a Map Node (maybe we need to add a new Ast Node like AstMapNode ).
2. Parse the string of every AstUdpTableLine and add the condition (LHS of : ) and result (RHS of :) pair to the AstMapNode. 
3. Add the Assign between the output o and the AstMapNode tableMAP, like
` if (tableMap.find(val)) o = \ <=  tableMap(val);`

So I think the key point is that I may need to add a new AstNode to represent the Map（I have not found a proper AstNode to support this）and then add the corresponding support.

**Comment by wsnyder** [comment]
See #468.
