### ISSUE TITLE
Getting fatal error as    coroutine: No such file or directory

### ISSUE THREAD

**Issue by mano009** [verilator/verilator#5535]
![Screenshot 2024-10-13 112107](https://github.com/user-attachments/assets/d88396c3-0e9b-406d-8895-8ef8f3f00c38)
Thanks for taking the time to report this.
![image](https://github.com/user-attachments/assets/2e334322-fea1-4573-be98-b3f45373f865)

command used: verilator --binary -j 0 top.v --timing
What 'verilator' command line do we use to run your example?

Version: 5.028

OS : Linux

May we assist you in trying to fix this in Verilator yourself?  Yes
![Screenshot 2024-10-13 111715](https://github.com/user-attachments/assets/27e86fa6-e0e5-41ba-95b4-be91abfb6323)

**Comment by wsnyder** [comment]
Please try the git master version.

If that does not work, post the full log, including the "configure" step, as text. please do not post images, thanks.
