### ISSUE TITLE
compile error "bear: error: unrecognized arguments: --output"

### ISSUE THREAD

**Issue by godblesszhouzhou** [verilator/verilator#5548]
Recently, when I compile verilator, there is an error "bear: error: unrecognized arguments: --output" on Ubuntu20.04.  I have tried a lot of different versions of bear and it does not work. Can anyone show the version of bear that can work? Thanks!

**Comment by wsnyder** [comment]
Verilator doesn't require bear for general use, only for some extended tests.  If you uninstall bear, or make a e.g. ~/bin/bear which has "exit 1" in it in your PATH, or edit the BEAR code in src/Makefile_obj.in, it should build OK.
