### ISSUE TITLE
Support queue's assignment like "push_back/push_front('{})"

### ISSUE THREAD

**Issue by YilouWang** [verilator/verilator#5585]
When dealing with assignment like this:
```
jagged_array.push_back('{7});
jagged_array.push_back('{8, 9, 10});
jagged_array.push_front('{0, 1});
```
Verilator will give an unsupport-warning error message.

**Comment by wsnyder** [comment]
Can you please provide a self-checking example, that works on other simulators?

Might you look at a pull to fix this?
