### ISSUE TITLE
can't compile example of 1364-2005

### ISSUE THREAD

**Issue by oldoldman** [verilator/verilator#5589]
Hi guys,
I'm reading the 1364-2005 lang spec, on page 175, there is an example
```
module split_ports(a[7:4],a[3:0]);
  input [7:0] a;
endmodule
```
this example failed to compile, I have tried the following parameters in turn
```
verilator_bin ... -language 1364-2005 ...
verilator_bin ... -default-language 1364-2005 ...
verilator_bin ... +1364-2005ext+v ...
```
all failed. Any suggestion?

**Comment by wsnyder** [comment]
Unsupported, see 2844.  Note if you are simply learning this is almost never done in real designs.
