### ISSUE TITLE
typed constructor doesn't work

### ISSUE THREAD

**Issue by solomatnikov** [verilator/verilator#5592]
From https://www.chipverify.com/systemverilog/systemverilog-class-constructor
```
class C;
endclass

class D extends C;
endclass

module tb;
   initial begin
      C c = D::new;
   end
endmodule
```

```
%Error: t/t_class_extends1.v:9:16: syntax error, unexpected new, expecting TYPE-IDENTIFIER
    9 |       C c = D::new;
      |                ^~~
%Error: Exiting due to 1 error(s)
```

VCS works

What 'verilator' command line do we use to run your example?

`verilator -cc --fdedup --debug-check --comp-limit-members 10 --x-assign unique`

What 'verilator --version' are you using?  Did you try it with the git master version?

`Verilator 5.029 devel rev v5.028-201-ga3d0cc652`

What OS and distribution are you using?

`Linux 5.14.0-427.33.1.el9_4.x86_64`

**Comment by wsnyder** [comment]
See #4199
