### ISSUE TITLE
Values of a register named mem aren't generated in VCD during OpenC910 simulation with Verilator v5.026

### ISSUE THREAD

**Issue by AruneshKma** [verilator/verilator#5621]
I am simulating the **openC910** core using **Verilator v5.026**. While running the "hello_world.s" test case, I noticed that in the generated **VCD** file, the values of a register named **mem** from the RTL file **fpga_ram.v** are not being displayed. The register is declared in the format: **reg [(DATAWIDTH-1):0] mem [(MEMDEPTH-1):0].** But other signal values from the same submodule in the RTL file are appearing in the VCD. I would appreciate any suggestions to resolve this issue.

I'll attach the contents of RTL file **fpga_ram.v** and generated VCD screenshot below.

```
module fpga_ram(
  PortAClk,
  PortAAddr,
  PortADataIn,
  PortAWriteEnable,
//  PortAChipEnable,
  PortADataOut
);

parameter  DATAWIDTH = 2;
parameter  ADDRWIDTH = 2;

input                     PortAClk;
input   [(ADDRWIDTH-1):0] PortAAddr;
input   [(DATAWIDTH-1):0] PortADataIn;
input                     PortAWriteEnable;
//input                     PortAChipEnable;
output  [(DATAWIDTH-1):0] PortADataOut; 

parameter  MEMDEPTH = 2**(ADDRWIDTH);

reg [(DATAWIDTH-1):0] mem [(MEMDEPTH-1):0] /* synthesis syn_ramstyle = "no_rw_check" */;
reg [(DATAWIDTH-1):0] PortADataOut;

always @(posedge PortAClk)
begin
  if(PortAWriteEnable)
  begin
    mem[PortAAddr]  <= PortADataIn;
    PortADataOut    <= PortADataIn;
  end
  else
  begin
    PortADataOut    <= mem[PortAAddr];
  end
end
endmodule
```

![image](https://github.com/user-attachments/assets/2f9364ee-5125-4f95-a65d-a1c083924598)

Here are the commands i used to run the simulation,
```
cd C910_RTL_FACTORY
source setup/setup.csh
cd ../smart_run
source setup/example_setup.csh
mkdir work
make clean

make compile SIM=verilator DUMP=onmake -j1 buildVerilator
make buildcase CASE=hello_world
cd ./work && obj_dir/Vtop

```

**Comment by wsnyder** [comment]
The example you sent does have 'mem' being traced.  I suspect you copied this from a larger example where the memory was much larger.  If you grep for `mem` in that larger example it will indicate why it is not traced, most likely the memory is too large. See https://verilator.org/guide/latest/exe_verilator.html#cmdoption-trace-max-array and https://verilator.org/guide/latest/exe_verilator.html#cmdoption-trace-max-width
