### ISSUE TITLE
Verilator_coverage not working with version 5.026

### ISSUE THREAD

**Issue by vinomutty** [verilator/verilator#5680]
Hi Team,

I am trying to generate coverage with verilator in cocotb.
I have added following lines to enable coverage in Makefile

EXTRA_ARGS += --coverage --coverage-line --coverage-toggle

covarage.dat file is generated but verilator_coverage coverage.dat is not working (returning nothing).

**Comment by wsnyder** [comment]
Is the file non-empty?  What is the verilator_coverage command line?  Run it outside cocotb for all discussions here please.

**Comment by vinomutty** [comment]
Yes. File is non-empty.
I used 
verilator_coverage coverage.dat

**Comment by wsnyder** [comment]
You didn't specify any outputs.  https://veripool.org/guide/latest/exe_verilator_coverage.html#verilator-coverage-example-usage
