### ISSUE TITLE
Parse various SVA statements into XML netlist

### ISSUE THREAD

**Issue by alex-maiorov** [verilator/verilator#5695]
Hello,

I was thinking it would be useful to be able to output the netlist of the design after things like assertions and coverage are read. The main usefulness that I was thinking of was that another tool could take this file and convert it to a SMT solver's format to be able to do formal verification with verilator's parsing and elaboration. From what I can tell, the current XML output does not include assertions or assume statements. Please let me know if I am missing anything, and if anyone has any further documentation of the XML format besides the docs/xml.rst I would appreciate that as well.

Thank you,
Alex Maiorov

**Comment by wsnyder** [comment]
Note XML is deprecated, JSON should be used for new applications.  If you want to add a new JSON output option to do it later I'd accept it, however please only propose adding that when you/someone has a tool that will be using it.

Specifically for SMT etc, the transforms Verilator does might be in conflict to be what is needed for another formal tool.  A better starting point may be to enhance e.g. [SymbiYosys](https://symbiyosys.readthedocs.io/en/latest/)
